// 50 High-Quality Footwear & Bags Products across 10 Subcategories (5 each)
// 5 Women Footwear + 5 Men Footwear + 5 Handbags & Totes + 5 Backpacks & Travel = 10 Subcategories × 5 items = 50 Products
module.exports = [
  // ═════════════════════════════════════════════════════════════
  // 1. HEELS & PUMPS (Women Footwear - 5 items)
  // ═════════════════════════════════════════════════════════════
  {
    _id: 'fb-footwear-heels-1',
    name: 'Women Pointed-Toe Stiletto Glossy Nude Party Pumps',
    slug: 'women-pointed-toe-stiletto-glossy-nude-party-pumps',
    brand: 'ZYRIVO STEPS',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 650,
    discountPrice: 369,
    ratings: 4.8,
    numReviews: 86,
    isFeatured: true,
    tags: ['women', 'shoes', 'footwear', 'heels & pumps', 'heels', 'pumps', 'stilettos'],
    images: [{ url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800&auto=format&fit=crop' }],
    description: 'Sleek 3.5-inch patent nude stiletto pumps with anti-skid TPR sole and memory foam cushioned arch support.',
  },
  {
    _id: 'fb-footwear-heels-2',
    name: 'Women Velvet Black D\'Orsay Pointed Evening Stilettos',
    slug: 'women-velvet-black-dorsay-pointed-evening-stilettos',
    brand: 'ZYRIVO STEPS',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 900,
    discountPrice: 569,
    ratings: 4.9,
    numReviews: 64,
    isFeatured: false,
    tags: ['women', 'shoes', 'footwear', 'heels & pumps', 'heels', 'pumps', 'party wear'],
    images: [{ url: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?q=80&w=800&auto=format&fit=crop' }],
    description: 'Midnight black luxe velvet side cut-out D\'Orsay pumps designed for black-tie soirees and glamorous evenings.',
  },
  {
    _id: 'fb-footwear-heels-3',
    name: 'Women Shimmer Metallic Rose Gold Ankle Strap Pumps',
    slug: 'women-shimmer-metallic-rose-gold-ankle-strap-pumps',
    brand: 'ZYRIVO LUXE',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1250,
    discountPrice: 769,
    ratings: 4.8,
    numReviews: 92,
    isFeatured: true,
    tags: ['women', 'shoes', 'footwear', 'heels & pumps', 'heels', 'rose gold', 'festive'],
    images: [{ url: 'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?q=80&w=800&auto=format&fit=crop' }],
    description: 'Festive metallic glitter finish pumps with adjustable buckle ankle strap and reinforced heel counters.',
  },
  {
    _id: 'fb-footwear-heels-4',
    name: 'Women Suede Kitten Heel Formal Office Work Pumps',
    slug: 'women-suede-kitten-heel-formal-office-work-pumps',
    brand: 'ZYRIVO DAILY',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1850,
    discountPrice: 1099,
    ratings: 4.7,
    numReviews: 73,
    isFeatured: false,
    tags: ['women', 'shoes', 'footwear', 'heels & pumps', 'pumps', 'kitten heel', 'office'],
    images: [{ url: 'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?q=80&w=800&auto=format&fit=crop' }],
    description: 'Comfortable 2-inch modest kitten heels crafted in rich faux suede, designed for 9-to-5 boardroom comfort.',
  },
  {
    _id: 'fb-footwear-heels-5',
    name: 'Women Sculpted Heel Statement Square Toe Formal Pumps',
    slug: 'women-sculpted-heel-statement-square-toe-formal-pumps',
    brand: 'ZYRIVO ATELIER',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 2000,
    discountPrice: 1249,
    ratings: 4.9,
    numReviews: 51,
    isFeatured: true,
    tags: ['women', 'shoes', 'footwear', 'heels & pumps', 'heels', 'square toe', 'designer'],
    images: [{ url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=800&auto=format&fit=crop' }],
    description: 'Contemporary architectural flared sculpted heel pumps with modern square toe silhouette in vegan ivory leather.',
  },

  // ═════════════════════════════════════════════════════════════
  // 2. FLATS & SANDALS (Women Footwear - 5 items)
  // ═════════════════════════════════════════════════════════════
  {
    _id: 'fb-footwear-flats-1',
    name: 'Women Braided Strappy Open-Toe Casual Slide Sandals',
    slug: 'women-braided-strappy-open-toe-casual-slide-sandals',
    brand: 'ZYRIVO DAILY',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 350,
    discountPrice: 239,
    ratings: 4.8,
    numReviews: 108,
    isFeatured: true,
    tags: ['women', 'shoes', 'footwear', 'flats & sandals', 'flats', 'sandals', 'slides'],
    images: [{ url: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?q=80&w=800&auto=format&fit=crop' }],
    description: 'Dual woven braided strap slip-on flat slides with flexible cushioned footbed and textured non-slip sole.',
  },
  {
    _id: 'fb-footwear-flats-2',
    name: 'Women Pearl Embellished Slip-On Pointed Flat Mules',
    slug: 'women-pearl-embellished-slip-on-pointed-flat-mules',
    brand: 'ZYRIVO LUXE',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 700,
    discountPrice: 439,
    ratings: 4.9,
    numReviews: 95,
    isFeatured: true,
    tags: ['women', 'shoes', 'footwear', 'flats & sandals', 'flats', 'mules', 'pearls'],
    images: [{ url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=800&auto=format&fit=crop' }],
    description: 'Elegant ivory pointed backless flat mules adorned with faux pearl clusters across the vamp.',
  },
  {
    _id: 'fb-footwear-flats-3',
    name: 'Women T-Strap Bohemian Beaded Ankle Flat Sandals',
    slug: 'women-t-strap-bohemian-beaded-ankle-flat-sandals',
    brand: 'ZYRIVO ETHNIC',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1050,
    discountPrice: 639,
    ratings: 4.7,
    numReviews: 64,
    isFeatured: false,
    tags: ['women', 'shoes', 'footwear', 'flats & sandals', 'sandals', 'boho', 'beaded'],
    images: [{ url: 'https://images.unsplash.com/photo-1562273138-f46be4ebdf33?q=80&w=800&auto=format&fit=crop' }],
    description: 'Artisanal colorful seed-bead hand-strung T-strap sandals with elasticated heel strap for custom fit.',
  },
  {
    _id: 'fb-footwear-flats-4',
    name: 'Women Criss-Cross Minimalist Tan Leather Flat Slides',
    slug: 'women-criss-cross-minimalist-tan-leather-flat-slides',
    brand: 'ZYRIVO BASICS',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1450,
    discountPrice: 839,
    ratings: 4.8,
    numReviews: 81,
    isFeatured: false,
    tags: ['women', 'shoes', 'footwear', 'flats & sandals', 'flats', 'tan slides'],
    images: [{ url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800&auto=format&fit=crop' }],
    description: 'Buttery soft tan vegan leather wide criss-cross strap flat slides paired with ergonomic contoured insole.',
  },
  {
    _id: 'fb-footwear-flats-5',
    name: 'Women Metallic Toe-Ring Comfort Everyday Kolhapuri Flats',
    slug: 'women-metallic-toe-ring-comfort-kolhapuri-flats',
    brand: 'ZYRIVO RIWAAZ',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1800,
    discountPrice: 1039,
    ratings: 4.8,
    numReviews: 76,
    isFeatured: true,
    tags: ['women', 'shoes', 'footwear', 'flats & sandals', 'kolhapuri', 'toe ring'],
    images: [{ url: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=800&auto=format&fit=crop' }],
    description: 'Contemporary metallic rose-gold braided toe-ring ethnic flats featuring cushioned footbed and handmade pom-poms.',
  },

  // ═════════════════════════════════════════════════════════════
  // 3. PUNJABI JUTTIS (Women Footwear - 5 items)
  // ═════════════════════════════════════════════════════════════
  {
    _id: 'fb-footwear-juttis-1',
    name: 'Women Pure Leather Handcrafted Floral Threadwork Juttis',
    slug: 'women-pure-leather-handcrafted-floral-juttis',
    brand: 'ZYRIVO RIWAAZ',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 550,
    discountPrice: 299,
    ratings: 4.9,
    numReviews: 114,
    isFeatured: true,
    tags: ['women', 'shoes', 'footwear', 'punjabi juttis', 'juttis', 'mojari', 'ethnic shoes'],
    images: [{ url: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=800&auto=format&fit=crop' }],
    description: '100% genuine buffalo leather sole Punjabi jutti embellished with pastel silk thread floral needlework.',
  },
  {
    _id: 'fb-footwear-juttis-2',
    name: 'Women Mirror & Dabka Work Bridal Velvet Maroon Juttis',
    slug: 'women-mirror-dabka-work-bridal-velvet-maroon-juttis',
    brand: 'ZYRIVO HERITAGE',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 750,
    discountPrice: 499,
    ratings: 4.9,
    numReviews: 98,
    isFeatured: true,
    tags: ['women', 'shoes', 'footwear', 'punjabi juttis', 'juttis', 'bridal', 'velvet juttis'],
    images: [{ url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800&auto=format&fit=crop' }],
    description: 'Opulent royal maroon velvet festive juttis adorned with antique gold dabka, cutdana, and real mirror work.',
  },
  {
    _id: 'fb-footwear-juttis-3',
    name: 'Women Ghungroo & Gota Lace Festive Mustard Yellow Juttis',
    slug: 'women-ghungroo-gota-lace-festive-mustard-yellow-juttis',
    brand: 'ZYRIVO RIWAAZ',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1150,
    discountPrice: 699,
    ratings: 4.8,
    numReviews: 83,
    isFeatured: false,
    tags: ['women', 'shoes', 'footwear', 'punjabi juttis', 'juttis', 'haldi', 'yellow juttis'],
    images: [{ url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop' }],
    description: 'Vibrant haldi/mehendi mustard silk juttis bordered with delicate musical brass ghungroos and gota patti.',
  },
  {
    _id: 'fb-footwear-juttis-4',
    name: 'Women Muted Champagne Sequin Embellished Mojari Juttis',
    slug: 'women-muted-champagne-sequin-embellished-mojari-juttis',
    brand: 'ZYRIVO LUXE',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1550,
    discountPrice: 899,
    ratings: 4.8,
    numReviews: 72,
    isFeatured: false,
    tags: ['women', 'shoes', 'footwear', 'punjabi juttis', 'juttis', 'sequin juttis'],
    images: [{ url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=800&auto=format&fit=crop' }],
    description: 'Subtle shimmering champagne sequins on raw silk base with double-cushioned bite-free heel padding.',
  },
  {
    _id: 'fb-footwear-juttis-5',
    name: 'Women Phulkari Embroidered Colorful Georgette Casual Juttis',
    slug: 'women-phulkari-embroidered-colorful-georgette-casual-juttis',
    brand: 'ZYRIVO RIWAAZ',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 2100,
    discountPrice: 1299,
    ratings: 4.7,
    numReviews: 65,
    isFeatured: true,
    tags: ['women', 'shoes', 'footwear', 'punjabi juttis', 'juttis', 'phulkari'],
    images: [{ url: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?q=80&w=800&auto=format&fit=crop' }],
    description: 'Authentic Punjabi Phulkari geometric silk floss embroidery with bite-free rolled leather borders.',
  },

  // ═════════════════════════════════════════════════════════════
  // 4. BLOCK HEEL SANDALS (Women Footwear - 5 items)
  // ═════════════════════════════════════════════════════════════
  {
    _id: 'fb-footwear-blockheels-1',
    name: 'Women Dual Band Chunky 2.5-Inch Modern Block Heels',
    slug: 'women-dual-band-chunky-modern-block-heels',
    brand: 'ZYRIVO STEPS',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 300,
    discountPrice: 199,
    ratings: 4.8,
    numReviews: 120,
    isFeatured: true,
    tags: ['women', 'shoes', 'footwear', 'block heel sandals', 'block heels', 'sandals', 'heels'],
    images: [{ url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800&auto=format&fit=crop' }],
    description: 'Everyday comfortable 2.5-inch wide cylinder block heels with cushioned dual strap bands in soft vegan leather.',
  },
  {
    _id: 'fb-footwear-blockheels-2',
    name: 'Women Strappy Metallic Gold Ankle-Buckle Block Heels',
    slug: 'women-strappy-metallic-gold-ankle-buckle-block-heels',
    brand: 'ZYRIVO LUXE',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 650,
    discountPrice: 399,
    ratings: 4.9,
    numReviews: 94,
    isFeatured: true,
    tags: ['women', 'shoes', 'footwear', 'block heel sandals', 'block heels', 'gold heels'],
    images: [{ url: 'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?q=80&w=800&auto=format&fit=crop' }],
    description: 'Party & festive block heels with delicate multi-strap cross detailing and secure adjustable metallic ankle buckle.',
  },
  {
    _id: 'fb-footwear-blockheels-3',
    name: 'Women Clear Lucite Transparent Strap Chunky Block Heels',
    slug: 'women-clear-lucite-transparent-strap-chunky-block-heels',
    brand: 'ZYRIVO TREND',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1000,
    discountPrice: 599,
    ratings: 4.7,
    numReviews: 87,
    isFeatured: false,
    tags: ['women', 'shoes', 'footwear', 'block heel sandals', 'clear heels', 'transparent heels'],
    images: [{ url: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?q=80&w=800&auto=format&fit=crop' }],
    description: 'Modern clear vinyl strap open-toe block heel mules with faux woodgrain stacked heel.',
  },
  {
    _id: 'fb-footwear-blockheels-4',
    name: 'Women Quilted Padded Strap Slip-On Low Block Heel Mules',
    slug: 'women-quilted-padded-strap-slip-on-low-block-heel-mules',
    brand: 'ZYRIVO STEPS',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 400,
    discountPrice: 249,
    ratings: 4.8,
    numReviews: 76,
    isFeatured: false,
    tags: ['women', 'shoes', 'footwear', 'block heel sandals', 'block heels', 'quilted mules'],
    images: [{ url: 'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?q=80&w=800&auto=format&fit=crop' }],
    description: 'Cloud-soft quilted padded front strap low 2-inch block heels tailored for all-day painless walking.',
  },
  {
    _id: 'fb-footwear-blockheels-5',
    name: 'Women Woven Jute Espadrille Platform Ankle Tie Block Heels',
    slug: 'women-woven-jute-espadrille-platform-ankle-tie-block-heels',
    brand: 'ZYRIVO DAILY',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1400,
    discountPrice: 799,
    ratings: 4.8,
    numReviews: 68,
    isFeatured: true,
    tags: ['women', 'shoes', 'footwear', 'block heel sandals', 'espadrilles', 'summer heels'],
    images: [{ url: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?q=80&w=800&auto=format&fit=crop' }],
    description: 'Summer holiday natural woven jute wrapped block heel sandals with wrap-around linen ankle ribbons.',
  },

  // ═════════════════════════════════════════════════════════════
  // 5. PARTY STILETTOS (Women Footwear - 5 items)
  // ═════════════════════════════════════════════════════════════
  {
    _id: 'fb-footwear-stilettos-1',
    name: 'Women Crystal Rhinestone Bow Satin Party Stiletto Heels',
    slug: 'women-crystal-rhinestone-bow-satin-party-stiletto-heels',
    brand: 'ZYRIVO LUXE',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 650,
    discountPrice: 349,
    ratings: 4.9,
    numReviews: 132,
    isFeatured: true,
    tags: ['women', 'shoes', 'footwear', 'party stilettos', 'stilettos', 'rhinestone heels', 'party wear'],
    images: [{ url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800&auto=format&fit=crop' }],
    description: 'Celebrity-inspired pointed satin stiletto pumps crowned with an intricate sparkling crystal double-bow brooch.',
  },
  {
    _id: 'fb-footwear-stilettos-2',
    name: 'Women Spiral Snake Crystal Coil Ankle Wrap Stilettos',
    slug: 'women-spiral-snake-crystal-coil-ankle-wrap-stilettos',
    brand: 'ZYRIVO ATELIER',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1550,
    discountPrice: 999,
    ratings: 5.0,
    numReviews: 89,
    isFeatured: true,
    tags: ['women', 'shoes', 'footwear', 'party stilettos', 'stilettos', 'gladiator stilettos'],
    images: [{ url: 'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?q=80&w=800&auto=format&fit=crop' }],
    description: 'Sensational spiral crystal snake winding coil strap stilettos featuring 4-inch metallic pin heels.',
  },
  {
    _id: 'fb-footwear-stilettos-3',
    name: 'Women Metallic Mirror Chrome High-Shine Open-Toe Stilettos',
    slug: 'women-metallic-mirror-chrome-high-shine-open-toe-stilettos',
    brand: 'ZYRIVO STEPS',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 750,
    discountPrice: 449,
    ratings: 4.8,
    numReviews: 76,
    isFeatured: false,
    tags: ['women', 'shoes', 'footwear', 'party stilettos', 'stilettos', 'silver stilettos'],
    images: [{ url: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?q=80&w=800&auto=format&fit=crop' }],
    description: 'Futuristic mirror silver chrome stiletto sandals with minimalist single toe band and slim ankle closure.',
  },
  {
    _id: 'fb-footwear-stilettos-4',
    name: 'Women Emerald Velvet Platform High Heel Party Stilettos',
    slug: 'women-emerald-velvet-platform-high-heel-party-stilettos',
    brand: 'ZYRIVO LUXE',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1200,
    discountPrice: 699,
    ratings: 4.8,
    numReviews: 61,
    isFeatured: false,
    tags: ['women', 'shoes', 'footwear', 'party stilettos', 'platform heels', 'velvet stilettos'],
    images: [{ url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=800&auto=format&fit=crop' }],
    description: 'Deep jewel-toned emerald green plush velvet stilettos with 1-inch front platform for effortless height balance.',
  },
  {
    _id: 'fb-footwear-stilettos-5',
    name: 'Women Neon Pink Flirty Feather Detail Cocktail Stilettos',
    slug: 'women-neon-pink-flirty-feather-detail-cocktail-stilettos',
    brand: 'ZYRIVO TREND',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 500,
    discountPrice: 299,
    ratings: 4.7,
    numReviews: 54,
    isFeatured: true,
    tags: ['women', 'shoes', 'footwear', 'party stilettos', 'feather heels', 'cocktail stilettos'],
    images: [{ url: 'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?q=80&w=800&auto=format&fit=crop' }],
    description: 'Playful cocktail party stiletto heels with fluffy marabou feather front strap and lacquered pink stiletto heel.',
  },

  // ═════════════════════════════════════════════════════════════
  // 6. TOTE BAGS (Handbags & Totes - 5 items)
  // ═════════════════════════════════════════════════════════════
  {
    _id: 'fb-bags-tote-1',
    name: 'Women Structured Canvas & Vegan Leather Dual-Handle Tote Bag',
    slug: 'women-structured-canvas-vegan-leather-tote-bag',
    brand: 'ZYRIVO BAGS',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 850,
    discountPrice: 549,
    ratings: 4.8,
    numReviews: 122,
    isFeatured: true,
    tags: ['women', 'bags', 'bag', 'tote bags', 'tote', 'canvas tote', 'shoulder bag'],
    images: [{ url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Heavyweight organic cotton canvas tote paired with saddle tan vegan leather straps, zippered inner pouch, and key leash.',
  },
  {
    _id: 'fb-bags-tote-2',
    name: 'Women Classic Black Pebbled Faux Leather Work Laptop Tote',
    slug: 'women-classic-black-pebbled-faux-leather-work-laptop-tote',
    brand: 'ZYRIVO WORK',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1350,
    discountPrice: 849,
    ratings: 4.9,
    numReviews: 148,
    isFeatured: true,
    tags: ['women', 'bags', 'bag', 'tote bags', 'laptop tote', 'office bag', 'work bag'],
    images: [{ url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop' }],
    description: 'Spacious work tote bag with dedicated 14-inch padded laptop sleeve, multiple pen holders, and water bottle pocket.',
  },
  {
    _id: 'fb-bags-tote-3',
    name: 'Women Minimalist Raw-Edge Suede Slouchy Everyday Tote',
    slug: 'women-minimalist-raw-edge-suede-slouchy-everyday-tote',
    brand: 'ZYRIVO ATELIER',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1800,
    discountPrice: 1099,
    ratings: 4.7,
    numReviews: 89,
    isFeatured: false,
    tags: ['women', 'bags', 'bag', 'tote bags', 'suede tote', 'slouchy bag'],
    images: [{ url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop' }],
    description: 'Effortlessly chic caramel brown micro-suede hobo tote bag with magnetic snap closure and removable coin purse.',
  },
  {
    _id: 'fb-bags-tote-4',
    name: 'Women Reversible Dual-Color Soft Faux Leather Shopper Tote',
    slug: 'women-reversible-dual-color-soft-faux-leather-shopper-tote',
    brand: 'ZYRIVO DAILY',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1100,
    discountPrice: 649,
    ratings: 4.8,
    numReviews: 97,
    isFeatured: false,
    tags: ['women', 'bags', 'bag', 'tote bags', 'shopper tote', 'reversible tote'],
    images: [{ url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Innovative 2-in-1 reversible tote featuring burgundy on one side and powder blush on the other with matching clutch.',
  },
  {
    _id: 'fb-bags-tote-5',
    name: 'Women Geometric Laser-Cut Pattern Handcrafted Summer Tote',
    slug: 'women-geometric-laser-cut-pattern-summer-tote',
    brand: 'ZYRIVO TREND',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1300,
    discountPrice: 749,
    ratings: 4.8,
    numReviews: 73,
    isFeatured: true,
    tags: ['women', 'bags', 'bag', 'tote bags', 'laser cut tote', 'summer tote'],
    images: [{ url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop' }],
    description: 'Airy geometric laser-cut motif tote with removable printed canvas drawstring liner pouch and sturdy gold hardware.',
  },

  // ═════════════════════════════════════════════════════════════
  // 7. CROSSBODY BAGS (Handbags & Totes - 5 items)
  // ═════════════════════════════════════════════════════════════
  {
    _id: 'fb-bags-crossbody-1',
    name: 'Women Quilted Chevron Golden Turn-Lock Crossbody Bag',
    slug: 'women-quilted-chevron-golden-turn-lock-crossbody-bag',
    brand: 'ZYRIVO LUXE',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 900,
    discountPrice: 499,
    ratings: 4.9,
    numReviews: 142,
    isFeatured: true,
    tags: ['women', 'bags', 'bag', 'crossbody bags', 'crossbody', 'quilted bag', 'sling bag'],
    images: [{ url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop' }],
    description: 'Chic chevron stitched crossbody bag with polished metallic gold turn-lock closure and interwoven leather chain strap.',
  },
  {
    _id: 'fb-bags-crossbody-2',
    name: 'Women Saddle Flap Vintage Distressed Vegan Leather Sling Bag',
    slug: 'women-saddle-flap-vintage-distressed-sling-bag',
    brand: 'ZYRIVO ATELIER',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1400,
    discountPrice: 899,
    ratings: 4.8,
    numReviews: 118,
    isFeatured: true,
    tags: ['women', 'bags', 'bag', 'crossbody bags', 'crossbody', 'saddle bag', 'sling bag'],
    images: [{ url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop' }],
    description: 'Curved equestrian-inspired saddle crossbody with antique brass hardware, magnetic snap, and adjustable shoulder belt.',
  },
  {
    _id: 'fb-bags-crossbody-3',
    name: 'Women Compact Dual-Zipper Camera Crossbody Bag with Guitar Strap',
    slug: 'women-compact-dual-zipper-camera-crossbody-bag',
    brand: 'ZYRIVO STREET',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 2000,
    discountPrice: 1199,
    ratings: 4.7,
    numReviews: 86,
    isFeatured: false,
    tags: ['women', 'bags', 'bag', 'crossbody bags', 'crossbody', 'camera bag'],
    images: [{ url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Trendy camera bag silhouette featuring twin zippered main chambers and interchangeable ethnic jacquard guitar strap.',
  },
  {
    _id: 'fb-bags-crossbody-4',
    name: 'Women Half-Moon Crescent Minimalist Vegan Leather Crossbody',
    slug: 'women-half-moon-crescent-minimalist-crossbody',
    brand: 'ZYRIVO TREND',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 600,
    discountPrice: 349,
    ratings: 4.8,
    numReviews: 74,
    isFeatured: true,
    tags: ['women', 'bags', 'bag', 'crossbody bags', 'crossbody', 'crescent bag'],
    images: [{ url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop' }],
    description: 'Modern curved half-moon silhouette crossbody bag made from smooth vegan nappa leather with sleek matte metal zippers.',
  },
  {
    _id: 'fb-bags-crossbody-5',
    name: 'Women Multi-Compartment Phone Wallet Pouch Crossbody Sling',
    slug: 'women-multi-compartment-phone-wallet-crossbody-sling',
    brand: 'ZYRIVO DAILY',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1500,
    discountPrice: 949,
    ratings: 4.7,
    numReviews: 104,
    isFeatured: false,
    tags: ['women', 'bags', 'bag', 'crossbody bags', 'crossbody', 'phone pouch', 'wallet sling'],
    images: [{ url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop' }],
    description: 'Ultra-light compact crossbody phone sling with 8 card slots, currency dividers, and clear ID window.',
  },

  // ═════════════════════════════════════════════════════════════
  // 8. EVENING PARTY CLUTCHES (Handbags & Totes - 5 items)
  // ═════════════════════════════════════════════════════════════
  {
    _id: 'fb-bags-clutch-1',
    name: 'Women Dazzling Crystal Rhinestone Minaudiere Box Clutch',
    slug: 'women-dazzling-crystal-rhinestone-minaudiere-box-clutch',
    brand: 'ZYRIVO LUXE',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 450,
    discountPrice: 279,
    ratings: 4.9,
    numReviews: 88,
    isFeatured: true,
    tags: ['women', 'bags', 'bag', 'evening party clutches', 'clutches', 'clutch', 'party clutch'],
    images: [{ url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop' }],
    description: 'Glistening hand-set rhinestone evening hard-shell box clutch with magnetic crystal clasp and detachable gold chain.',
  },
  {
    _id: 'fb-bags-clutch-2',
    name: 'Women Pleated Silk Envelope Golden Accent Cocktail Clutch',
    slug: 'women-pleated-silk-envelope-golden-accent-cocktail-clutch',
    brand: 'ZYRIVO LUXE',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 750,
    discountPrice: 479,
    ratings: 4.8,
    numReviews: 76,
    isFeatured: false,
    tags: ['women', 'bags', 'bag', 'evening party clutches', 'clutches', 'envelope clutch'],
    images: [{ url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Timeless asymmetrical envelope flap clutch crafted in shimmering pleated satin with interior slip pocket.',
  },
  {
    _id: 'fb-bags-clutch-3',
    name: 'Women Mother-of-Pearl Inlay Handcrafted Brass Minaudiere',
    slug: 'women-mother-of-pearl-inlay-brass-minaudiere',
    brand: 'ZYRIVO HERITAGE',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1100,
    discountPrice: 679,
    ratings: 5.0,
    numReviews: 62,
    isFeatured: true,
    tags: ['women', 'bags', 'bag', 'evening party clutches', 'clutches', 'clutch', 'ethnic clutch'],
    images: [{ url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop' }],
    description: 'Heritage hand-carved floral brass frame studded with iridescent natural mother-of-pearl mosaic tiles.',
  },
  {
    _id: 'fb-bags-clutch-4',
    name: 'Women Glitter Sparkle Flap Bridal Wristlet Party Clutch',
    slug: 'women-glitter-sparkle-flap-bridal-wristlet-party-clutch',
    brand: 'ZYRIVO STEPS',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1500,
    discountPrice: 879,
    ratings: 4.7,
    numReviews: 81,
    isFeatured: false,
    tags: ['women', 'bags', 'bag', 'evening party clutches', 'clutches', 'wristlet'],
    images: [{ url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop' }],
    description: 'Ultra-sparkle non-shedding metallic silver glitter clutch featuring a detachable wristlet loop for dancing.',
  },
  {
    _id: 'fb-bags-clutch-5',
    name: 'Women Antique Zardozi Embroidered Velvet Potli Clutch',
    slug: 'women-antique-zardozi-embroidered-velvet-potli-clutch',
    brand: 'ZYRIVO RIWAAZ',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1850,
    discountPrice: 1049,
    ratings: 4.9,
    numReviews: 95,
    isFeatured: true,
    tags: ['women', 'bags', 'bag', 'evening party clutches', 'clutches', 'potli bag', 'potli'],
    images: [{ url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Royal maroon velvet potli pouch bordered with shimmering golden zari cords, pearls, and pearl tassel tie-ups.',
  },

  // ═════════════════════════════════════════════════════════════
  // 9. LAPTOP BACKPACKS (Backpacks & Travel - 5 items)
  // ═════════════════════════════════════════════════════════════
  {
    _id: 'fb-bags-backpack-1',
    name: 'Unisex Anti-Theft Water-Resistant 15.6-Inch Laptop Backpack',
    slug: 'unisex-anti-theft-water-resistant-laptop-backpack',
    brand: 'ZYRIVO GEAR',
    categorySlug: 'bags-leather',
    categoryName: 'Bags & Leather',
    price: 600,
    discountPrice: 329,
    ratings: 4.9,
    numReviews: 164,
    isFeatured: true,
    tags: ['bags', 'bag', 'backpack', 'backpacks & travel', 'laptop backpacks', 'laptop bag'],
    images: [{ url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop' }],
    description: 'Heavy-duty 900D water-repellent oxford fabric backpack with TSA lock, hidden back pocket, and USB charging pass-through.',
  },
  {
    _id: 'fb-bags-backpack-2',
    name: 'Men Slim Minimalist Vegan Leather Commuter Laptop Backpack',
    slug: 'men-slim-minimalist-vegan-leather-commuter-laptop-backpack',
    brand: 'ZYRIVO ATELIER',
    categorySlug: 'bags-leather',
    categoryName: 'Bags & Leather',
    price: 800,
    discountPrice: 529,
    ratings: 4.8,
    numReviews: 129,
    isFeatured: true,
    tags: ['men', 'bags', 'bag', 'backpack', 'backpacks & travel', 'laptop backpacks', 'leather backpack'],
    images: [{ url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop' }],
    description: 'Streamlined executive commuter backpack crafted from weather-resistant matte black vegan leather with padded 16-inch compartment.',
  },
  {
    _id: 'fb-bags-backpack-3',
    name: 'Unisex Roll-Top Waterproof Urban Cycling Travel Backpack',
    slug: 'unisex-roll-top-waterproof-urban-cycling-travel-backpack',
    brand: 'ZYRIVO SPORTS',
    categorySlug: 'bags-leather',
    categoryName: 'Bags & Leather',
    price: 1200,
    discountPrice: 729,
    ratings: 4.8,
    numReviews: 93,
    isFeatured: false,
    tags: ['bags', 'bag', 'backpack', 'backpacks & travel', 'laptop backpacks', 'travel'],
    images: [{ url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop' }],
    description: 'Expandable 25L to 30L roll-top waterproof daypack with aluminum buckle and breathable airflow back padding.',
  },
  {
    _id: 'fb-bags-backpack-4',
    name: 'Women Chic Quilted Nylon Multi-Pocket College Backpack',
    slug: 'women-chic-quilted-nylon-multi-pocket-college-backpack',
    brand: 'ZYRIVO BAGS',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1650,
    discountPrice: 979,
    ratings: 4.7,
    numReviews: 112,
    isFeatured: false,
    tags: ['women', 'bags', 'bag', 'backpack', 'backpacks & travel', 'laptop backpacks', 'college backpack'],
    images: [{ url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Featherlight quilted olive nylon backpack with gold metal zippers, tablet sleeve, and water-repellent exterior.',
  },
  {
    _id: 'fb-bags-backpack-5',
    name: 'Unisex Ergonomic Orthopedic Lumbar Support Travel Backpack',
    slug: 'unisex-ergonomic-orthopedic-lumbar-travel-backpack',
    brand: 'ZYRIVO GEAR',
    categorySlug: 'bags-leather',
    categoryName: 'Bags & Leather',
    price: 1850,
    discountPrice: 1149,
    ratings: 4.9,
    numReviews: 87,
    isFeatured: true,
    tags: ['bags', 'bag', 'backpack', 'backpacks & travel', 'laptop backpacks', 'ergonomic'],
    images: [{ url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop' }],
    description: 'Doctor-endorsed S-curve ergonomic shoulder straps, integrated luggage trolley sleeve, and padded velvet laptop compartment.',
  },

  // ═════════════════════════════════════════════════════════════
  // 10. LEATHER DUFFEL BAGS (Backpacks & Travel - 5 items)
  // ═════════════════════════════════════════════════════════════
  {
    _id: 'fb-bags-duffel-1',
    name: 'Unisex Handcrafted Vintage Tan Leather Weekender Duffel Bag',
    slug: 'unisex-handcrafted-vintage-tan-leather-weekender-duffel-bag',
    brand: 'ZYRIVO ATELIER',
    categorySlug: 'bags-leather',
    categoryName: 'Bags & Leather',
    price: 350,
    discountPrice: 219,
    ratings: 4.9,
    numReviews: 138,
    isFeatured: true,
    tags: ['bags', 'bag', 'duffel bag', 'backpacks & travel', 'leather duffel bags', 'weekender', 'travel duffel'],
    images: [{ url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop' }],
    description: 'Full-grain vintage pull-up distressed leather weekender duffel with reinforced brass feet, side shoe compartment, and cotton lining.',
  },
  {
    _id: 'fb-bags-duffel-2',
    name: 'Men Waterproof Matte Black Gym & Overnight Duffel Bag',
    slug: 'men-waterproof-matte-black-gym-overnight-duffel-bag',
    brand: 'ZYRIVO SPORTS',
    categorySlug: 'bags-leather',
    categoryName: 'Bags & Leather',
    price: 650,
    discountPrice: 419,
    ratings: 4.8,
    numReviews: 104,
    isFeatured: true,
    tags: ['men', 'bags', 'bag', 'duffel bag', 'backpacks & travel', 'leather duffel bags', 'gym duffel'],
    images: [{ url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop' }],
    description: 'Sleek gym-to-office duffel featuring independent wet towel compartment, ventilated sneaker chamber, and padded shoulder strap.',
  },
  {
    _id: 'fb-bags-duffel-3',
    name: 'Unisex Heavyweight Washed Canvas & Leather Trim Duffel Bag',
    slug: 'unisex-heavyweight-washed-canvas-leather-trim-duffel-bag',
    brand: 'ZYRIVO GEAR',
    categorySlug: 'bags-leather',
    categoryName: 'Bags & Leather',
    price: 1000,
    discountPrice: 619,
    ratings: 4.8,
    numReviews: 89,
    isFeatured: false,
    tags: ['bags', 'bag', 'duffel bag', 'backpacks & travel', 'leather duffel bags', 'canvas duffel'],
    images: [{ url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Sturdy military green 16oz stonewashed canvas duffel with full-grain leather zipper pulls and detachable strap.',
  },
  {
    _id: 'fb-bags-duffel-4',
    name: 'Men Executive Monogrammed Cabin-Size Leather Carry-On Duffel',
    slug: 'men-executive-monogrammed-cabin-size-carry-on-duffel',
    brand: 'ZYRIVO ATELIER',
    categorySlug: 'bags-leather',
    categoryName: 'Bags & Leather',
    price: 1400,
    discountPrice: 819,
    ratings: 4.9,
    numReviews: 75,
    isFeatured: false,
    tags: ['men', 'bags', 'bag', 'duffel bag', 'backpacks & travel', 'leather duffel bags', 'cabin bag'],
    images: [{ url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop' }],
    description: 'Airline cabin-compliant 40L structured leather travel duffel with passport organizer and suit hanger strap.',
  },
  {
    _id: 'fb-bags-duffel-5',
    name: 'Women Blush Pink Compact Lightweight Weekend Getaway Duffel',
    slug: 'women-blush-pink-compact-lightweight-weekend-duffel',
    brand: 'ZYRIVO BAGS',
    categorySlug: 'women-footwear-bags',
    categoryName: 'Women Footwear & Bags',
    price: 1800,
    discountPrice: 1019,
    ratings: 4.7,
    numReviews: 92,
    isFeatured: true,
    tags: ['women', 'bags', 'bag', 'duffel bag', 'backpacks & travel', 'leather duffel bags', 'travel'],
    images: [{ url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop' }],
    description: 'Chic blush pink travel duffel with gold-plated metallic zippers and rear luggage trolley pass-through sleeve.',
  },
];


