// 50 High-Quality Men Products across 10 Subcategories (5 each)
module.exports = [
  // ─────────────────────────────────────────────────────────────
  // 1. T-SHIRTS (5 items)
  // ─────────────────────────────────────────────────────────────
  {
    _id: 'fb-men-tshirt-1',
    name: 'Men Solid Crewneck Pure Supima Cotton T-Shirt',
    slug: 'men-solid-crewneck-pure-supima-cotton-t-shirt',
    brand: 'ZYRIVO BASICS',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 650,
    discountPrice: 369,
    ratings: 4.8,
    numReviews: 94,
    isFeatured: true,
    tags: ['men', 'men top wear', 't-shirts', 'men t-shirts', 'crewneck', 'cotton', 'basics'],
    images: [{ url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=800&auto=format&fit=crop' }],
    description: 'Everyday staple crewneck tee crafted from 100% long-staple Supima cotton with ribbed collar and breathable finish.',
  },
  {
    _id: 'fb-men-tshirt-2',
    name: 'Men Slim Fit Classic Solid White V-Neck T-Shirt',
    slug: 'men-slim-fit-classic-solid-white-v-neck-t-shirt',
    brand: 'ZYRIVO BASICS',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 900,
    discountPrice: 569,
    ratings: 4.7,
    numReviews: 68,
    isFeatured: false,
    tags: ['men', 'men top wear', 't-shirts', 'men t-shirts', 'v-neck', 'white tee', 'slim fit'],
    images: [{ url: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?q=80&w=800&auto=format&fit=crop' }],
    description: 'Crisp minimal white V-neck t-shirt in combed organic cotton, designed with a modern contoured slim fit.',
  },
  {
    _id: 'fb-men-tshirt-3',
    name: 'Men Vintage Washed Mineral Black Bio-Wash T-Shirt',
    slug: 'men-vintage-washed-mineral-black-bio-wash-t-shirt',
    brand: 'ZYRIVO DENIM',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 1250,
    discountPrice: 769,
    ratings: 4.9,
    numReviews: 112,
    isFeatured: true,
    tags: ['men', 'men top wear', 't-shirts', 'men t-shirts', 'mineral wash', 'black tee'],
    images: [{ url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=800&auto=format&fit=crop' }],
    description: 'Acid-mineral washed vintage charcoal black t-shirt treated with bio-softening enzymes for an authentic broken-in feel.',
  },
  {
    _id: 'fb-men-tshirt-4',
    name: 'Men Bold Typography Chest Print Casual T-Shirt',
    slug: 'men-bold-typography-chest-print-casual-t-shirt',
    brand: 'ZYRIVO STREET',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 1850,
    discountPrice: 1099,
    ratings: 4.8,
    numReviews: 83,
    isFeatured: false,
    tags: ['men', 'men top wear', 't-shirts', 'men t-shirts', 'graphic tee', 'casual t-shirt'],
    images: [{ url: 'https://images.unsplash.com/photo-1527719327859-c6ce80353573?q=80&w=800&auto=format&fit=crop' }],
    description: 'Statement casual t-shirt with premium rubberized micro-typography chest print on 200 GSM breathable jersey knit.',
  },
  {
    _id: 'fb-men-tshirt-5',
    name: 'Men Nautical Breton Striped Premium Cotton T-Shirt',
    slug: 'men-nautical-breton-striped-premium-cotton-t-shirt',
    brand: 'ZYRIVO CASUALS',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 2000,
    discountPrice: 1249,
    ratings: 4.8,
    numReviews: 76,
    isFeatured: false,
    tags: ['men', 'men top wear', 't-shirts', 'men t-shirts', 'striped', 'casual t-shirt'],
    images: [{ url: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?q=80&w=800&auto=format&fit=crop' }],
    description: 'French Riviera inspired yarn-dyed navy and white Breton striped t-shirt made with ultra-soft combed cotton.',
  },

  // ─────────────────────────────────────────────────────────────
  // 2. POLO T-SHIRTS (5 items)
  // ─────────────────────────────────────────────────────────────
  {
    _id: 'fb-men-polo-1',
    name: 'Men Honeycomb Pique Textured Solid Polo T-Shirt',
    slug: 'men-honeycomb-pique-textured-solid-polo-t-shirt',
    brand: 'ZYRIVO ATELIER',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 350,
    discountPrice: 239,
    ratings: 4.9,
    numReviews: 95,
    isFeatured: true,
    tags: ['men', 'men top wear', 'polo t-shirts', 'polo', 'pique polo', 'collared'],
    images: [{ url: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?q=80&w=800&auto=format&fit=crop' }],
    description: 'Refined 240 GSM honeycomb pique knit polo t-shirt featuring ribbed flat-knit collar and mother-of-pearl buttons.',
  },
  {
    _id: 'fb-men-polo-2',
    name: 'Men Contrast Tipped Collar Slim Fit Polo T-Shirt',
    slug: 'men-contrast-tipped-collar-slim-fit-polo-t-shirt',
    brand: 'ZYRIVO SPORTS',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 700,
    discountPrice: 439,
    ratings: 4.8,
    numReviews: 72,
    isFeatured: false,
    tags: ['men', 'men top wear', 'polo t-shirts', 'polo', 'tipped polo', 'smart casual'],
    images: [{ url: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?q=80&w=800&auto=format&fit=crop' }],
    description: 'Modern preppy polo shirt featuring dual contrast tipping stripes along the collar edges and sleeve cuffs.',
  },
  {
    _id: 'fb-men-polo-3',
    name: 'Men Mercerized Cotton Luxe Smart Casual Polo T-Shirt',
    slug: 'men-mercerized-cotton-luxe-smart-casual-polo-t-shirt',
    brand: 'ZYRIVO ATELIER',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 1050,
    discountPrice: 639,
    ratings: 4.9,
    numReviews: 88,
    isFeatured: true,
    tags: ['men', 'men top wear', 'polo t-shirts', 'polo', 'luxury polo', 'mercerized cotton'],
    images: [{ url: 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?q=80&w=800&auto=format&fit=crop' }],
    description: 'High-sheen mercerized double-twisted cotton polo with an ultra-smooth silky hand-feel and clean French placket.',
  },
  {
    _id: 'fb-men-polo-4',
    name: 'Men Retro Zipper Placket Textured Knit Polo T-Shirt',
    slug: 'men-retro-zipper-placket-textured-knit-polo-t-shirt',
    brand: 'ZYRIVO CASUALS',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 1450,
    discountPrice: 839,
    ratings: 4.7,
    numReviews: 61,
    isFeatured: false,
    tags: ['men', 'men top wear', 'polo t-shirts', 'polo', 'zip polo', 'textured polo'],
    images: [{ url: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?q=80&w=800&auto=format&fit=crop' }],
    description: 'Contemporary polo shirt styled with an antique silver quarter-zip front fastener and subtle micro-waffle weave.',
  },
  {
    _id: 'fb-men-polo-5',
    name: 'Men Colorblock Athletic Moisture-Wicking Polo T-Shirt',
    slug: 'men-colorblock-athletic-moisture-wicking-polo-t-shirt',
    brand: 'ZYRIVO SPORTS',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 1800,
    discountPrice: 1039,
    ratings: 4.8,
    numReviews: 54,
    isFeatured: false,
    tags: ['men', 'men top wear', 'polo t-shirts', 'polo', 'sports polo', 'quick dry'],
    images: [{ url: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=800&auto=format&fit=crop' }],
    description: 'Performance-ready sports polo engineered with quick-dry breathable polyester mesh fabric and contrast raglan sleeves.',
  },

  // ─────────────────────────────────────────────────────────────
  // 3. OVERSIZED STREETWEAR TEES (5 items)
  // ─────────────────────────────────────────────────────────────
  {
    _id: 'fb-men-oversized-1',
    name: 'Tokyo Underground Acid-Wash Oversized Graphic Tee',
    slug: 'tokyo-underground-acid-wash-oversized-graphic-tee',
    brand: 'ZYRIVO STREET',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 550,
    discountPrice: 299,
    ratings: 4.9,
    numReviews: 128,
    isFeatured: true,
    tags: ['men', 'men top wear', 'oversized streetwear tees', 'oversized tee', 'streetwear', 'drop shoulder'],
    images: [{ url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=800&auto=format&fit=crop' }],
    description: 'Heavyweight 260 GSM drop-shoulder boxy silhouette tee featuring Japanese cyberpunk typography back artwork.',
  },
  {
    _id: 'fb-men-oversized-2',
    name: 'Minimalist Monolith Heavyweight Drop-Shoulder Tee',
    slug: 'minimalist-monolith-heavyweight-drop-shoulder-tee',
    brand: 'ZYRIVO STREET',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 750,
    discountPrice: 499,
    ratings: 4.8,
    numReviews: 91,
    isFeatured: false,
    tags: ['men', 'men top wear', 'oversized streetwear tees', 'oversized tee', 'drop shoulder', 'minimalist'],
    images: [{ url: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=800&auto=format&fit=crop' }],
    description: 'Ultra-heavyweight 280 GSM French Terry oversized t-shirt in washed earth tone with thick ribbed neckband.',
  },
  {
    _id: 'fb-men-oversized-3',
    name: 'Rebel Horizon Distressed Raw-Hem Oversized T-Shirt',
    slug: 'rebel-horizon-distressed-raw-hem-oversized-t-shirt',
    brand: 'ZYRIVO STREET',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 1150,
    discountPrice: 699,
    ratings: 4.8,
    numReviews: 77,
    isFeatured: true,
    tags: ['men', 'men top wear', 'oversized streetwear tees', 'oversized tee', 'distressed', 'skater tee'],
    images: [{ url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=800&auto=format&fit=crop' }],
    description: 'Vintage-washed streetwear boxy t-shirt with subtle distress grinding along the collar and raw unfinished hemline.',
  },
  {
    _id: 'fb-men-oversized-4',
    name: 'Neo Cyber Aesthetic Back-Print Oversized Skater Tee',
    slug: 'neo-cyber-aesthetic-back-print-oversized-skater-tee',
    brand: 'ZYRIVO STREET',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 1550,
    discountPrice: 899,
    ratings: 4.7,
    numReviews: 64,
    isFeatured: false,
    tags: ['men', 'men top wear', 'oversized streetwear tees', 'oversized tee', 'skater tee', 'graphic'],
    images: [{ url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=800&auto=format&fit=crop' }],
    description: 'Loose oversized fit skate tee with high-density gradient puff-print on chest and expansive abstract cyber graphic across back.',
  },
  {
    _id: 'fb-men-oversized-5',
    name: 'Urban Monochrome Boxy Relaxed Cotton Streetwear Tee',
    slug: 'urban-monochrome-boxy-relaxed-cotton-streetwear-tee',
    brand: 'ZYRIVO STREET',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 2100,
    discountPrice: 1299,
    ratings: 4.8,
    numReviews: 82,
    isFeatured: false,
    tags: ['men', 'men top wear', 'oversized streetwear tees', 'oversized tee', 'boxy tee', 'monochrome'],
    images: [{ url: 'https://images.unsplash.com/photo-1507680434567-5739c80be1ac?q=80&w=800&auto=format&fit=crop' }],
    description: 'Clean monochrome oversized tee tailored with wider sleeves and a slouchy dropped shoulder for relaxed modern layering.',
  },

  // ─────────────────────────────────────────────────────────────
  // 4. CASUAL LINEN SHIRTS (5 items)
  // ─────────────────────────────────────────────────────────────
  {
    _id: 'fb-men-linenshirt-1',
    name: 'Pure French Flax Relaxed Mandarin Collar Linen Shirt',
    slug: 'pure-french-flax-relaxed-mandarin-collar-linen-shirt',
    brand: 'ZYRIVO ATELIER',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 300,
    discountPrice: 199,
    ratings: 4.9,
    numReviews: 104,
    isFeatured: true,
    tags: ['men', 'men top wear', 'casual linen shirts', 'linen shirts', 'linen', 'mandarin collar'],
    images: [{ url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=800&auto=format&fit=crop' }],
    description: '100% Normandy French flax linen shirt in relaxed band-collar design with natural shell buttons and airy breathable drape.',
  },
  {
    _id: 'fb-men-linenshirt-2',
    name: 'Washed Indigo Chambray-Linen Spread Collar Casual Shirt',
    slug: 'washed-indigo-chambray-linen-spread-collar-casual-shirt',
    brand: 'ZYRIVO CASUALS',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 650,
    discountPrice: 399,
    ratings: 4.8,
    numReviews: 79,
    isFeatured: false,
    tags: ['men', 'men top wear', 'casual linen shirts', 'linen shirts', 'chambray', 'spread collar'],
    images: [{ url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=800&auto=format&fit=crop' }],
    description: 'Garment-washed linen-cotton blend casual shirt featuring an easy spread collar, patch chest pocket, and curved hem.',
  },
  {
    _id: 'fb-men-linenshirt-3',
    name: 'Cuban Camp Collar Breathable Summer Striped Linen Shirt',
    slug: 'cuban-camp-collar-breathable-summer-striped-linen-shirt',
    brand: 'ZYRIVO RESORT',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 1000,
    discountPrice: 599,
    ratings: 4.8,
    numReviews: 66,
    isFeatured: true,
    tags: ['men', 'men top wear', 'casual linen shirts', 'linen shirts', 'cuban collar', 'resort wear'],
    images: [{ url: 'https://images.unsplash.com/photo-1598032895397-b9472444bf93?q=80&w=800&auto=format&fit=crop' }],
    description: 'Resort-ready Cuban notched collar linen shirt with vertical awning stripes, boxy short cut, and lightweight texture.',
  },
  {
    _id: 'fb-men-linenshirt-4',
    name: 'Solid Olive Green Pre-Washed Roll-Tab Sleeve Linen Shirt',
    slug: 'solid-olive-green-pre-washed-roll-tab-sleeve-linen-shirt',
    brand: 'ZYRIVO CASUALS',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 400,
    discountPrice: 249,
    ratings: 4.7,
    numReviews: 53,
    isFeatured: false,
    tags: ['men', 'men top wear', 'casual linen shirts', 'linen shirts', 'roll-tab', 'casual shirt'],
    images: [{ url: 'https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?q=80&w=800&auto=format&fit=crop' }],
    description: 'Earthy olive hue linen shirt with adjustable roll-tab sleeve loops, double chest flap pockets, and washed finish.',
  },
  {
    _id: 'fb-men-linenshirt-5',
    name: 'Coastal Beige Button-Down Classic Fit Pure Linen Shirt',
    slug: 'coastal-beige-button-down-classic-fit-pure-linen-shirt',
    brand: 'ZYRIVO ATELIER',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 1400,
    discountPrice: 799,
    ratings: 4.9,
    numReviews: 87,
    isFeatured: false,
    tags: ['men', 'men top wear', 'casual linen shirts', 'linen shirts', 'pure linen', 'button down'],
    images: [{ url: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=800&auto=format&fit=crop' }],
    description: 'Timeless beige pure linen button-down casual shirt with box pleat back and natural thermoregulating properties.',
  },

  // ─────────────────────────────────────────────────────────────
  // 5. FORMAL SHIRTS (5 items)
  // ─────────────────────────────────────────────────────────────
  {
    _id: 'fb-men-formalshirt-1',
    name: 'Men Executive Crisp White 100s Two-Ply Formal Shirt',
    slug: 'men-executive-crisp-white-100s-two-ply-formal-shirt',
    brand: 'ZYRIVO FORMAL',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 650,
    discountPrice: 349,
    ratings: 4.9,
    numReviews: 142,
    isFeatured: true,
    tags: ['men', 'men top wear', 'formal shirts', 'formal shirt', 'white formal shirt', 'office wear'],
    images: [{ url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=800&auto=format&fit=crop' }],
    description: 'Impeccably tailored 100s 2-ply Egyptian cotton executive shirt with stiff semi-spread collar and single cuff link option.',
  },
  {
    _id: 'fb-men-formalshirt-2',
    name: 'Men Sky Blue Fine Herringbone Weave Tailored Formal Shirt',
    slug: 'men-sky-blue-fine-herringbone-weave-tailored-formal-shirt',
    brand: 'ZYRIVO FORMAL',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 1550,
    discountPrice: 999,
    ratings: 4.8,
    numReviews: 96,
    isFeatured: false,
    tags: ['men', 'men top wear', 'formal shirts', 'formal shirt', 'blue formal', 'herringbone'],
    images: [{ url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=800&auto=format&fit=crop' }],
    description: 'Distinguished sky-blue tailored shirt in subtle herringbone dobby weave with wrinkle-resistant easy-iron finish.',
  },
  {
    _id: 'fb-men-formalshirt-3',
    name: 'Men Royal Oxford Weave Cutaway Collar Slim Formal Shirt',
    slug: 'men-royal-oxford-weave-cutaway-collar-slim-formal-shirt',
    brand: 'ZYRIVO FORMAL',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 750,
    discountPrice: 449,
    ratings: 4.8,
    numReviews: 81,
    isFeatured: true,
    tags: ['men', 'men top wear', 'formal shirts', 'formal shirt', 'oxford shirt', 'cutaway collar'],
    images: [{ url: 'https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?q=80&w=800&auto=format&fit=crop' }],
    description: 'Lustrous royal Oxford weave formal shirt equipped with modern wide cutaway collar built to accommodate full Windsor tie knots.',
  },
  {
    _id: 'fb-men-formalshirt-4',
    name: 'Men Subtle Micro-Check Executive French Cuff Formal Shirt',
    slug: 'men-subtle-micro-check-executive-french-cuff-formal-shirt',
    brand: 'ZYRIVO FORMAL',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 1200,
    discountPrice: 699,
    ratings: 4.9,
    numReviews: 69,
    isFeatured: false,
    tags: ['men', 'men top wear', 'formal shirts', 'formal shirt', 'french cuff', 'micro-check'],
    images: [{ url: 'https://images.unsplash.com/photo-1598032895397-b9472444bf93?q=80&w=800&auto=format&fit=crop' }],
    description: 'Boardroom-ready micro-grid check formal shirt finished with double French cuffs for cufflinks and a streamlined darted back.',
  },
  {
    _id: 'fb-men-formalshirt-5',
    name: 'Men Midnight Navy Luxe Satin-Finish Formal Evening Shirt',
    slug: 'men-midnight-navy-luxe-satin-finish-formal-evening-shirt',
    brand: 'ZYRIVO FORMAL',
    categorySlug: 'men-top-wear',
    categoryName: 'Men Top Wear',
    price: 500,
    discountPrice: 299,
    ratings: 4.8,
    numReviews: 58,
    isFeatured: false,
    tags: ['men', 'men top wear', 'formal shirts', 'formal shirt', 'navy formal', 'evening shirt'],
    images: [{ url: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=800&auto=format&fit=crop' }],
    description: 'Sophisticated midnight navy evening dress shirt in silk-cotton sateen with clean concealed button placket.',
  },

  // ─────────────────────────────────────────────────────────────
  // 6. DENIM JEANS (MEN) (5 items)
  // ─────────────────────────────────────────────────────────────
  {
    _id: 'fb-men-jeans-1',
    name: 'Men Slim Tapered Indigo Stretch Washed Denim Jeans',
    slug: 'men-slim-tapered-indigo-stretch-washed-denim-jeans',
    brand: 'ZYRIVO DENIM',
    categorySlug: 'men-bottom-wear',
    categoryName: 'Men Bottom Wear',
    price: 850,
    discountPrice: 549,
    ratings: 4.8,
    numReviews: 156,
    isFeatured: true,
    tags: ['men', 'men bottom wear', 'denim jeans', 'men denim jeans', 'jeans', 'indigo denim', 'slim tapered'],
    images: [{ url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=800&auto=format&fit=crop' }],
    description: 'Premium 12.5 oz comfort-stretch indigo denim jeans with authentic whiskering, hand-sanding, and a tailored slim tapered leg.',
  },
  {
    _id: 'fb-men-jeans-2',
    name: 'Men Vintage Washed Straight-Fit Rigid Selvedge Jeans',
    slug: 'men-vintage-washed-straight-fit-rigid-selvedge-jeans',
    brand: 'ZYRIVO DENIM',
    categorySlug: 'men-bottom-wear',
    categoryName: 'Men Bottom Wear',
    price: 1350,
    discountPrice: 849,
    ratings: 4.9,
    numReviews: 92,
    isFeatured: false,
    tags: ['men', 'men bottom wear', 'denim jeans', 'men denim jeans', 'jeans', 'selvedge', 'straight fit'],
    images: [{ url: 'https://images.unsplash.com/photo-1555689502-c4b22d76c56f?q=80&w=800&auto=format&fit=crop' }],
    description: 'Heritage straight-fit jeans crafted from 13.5 oz red-line shuttle-loom selvedge denim with antique brass hardware.',
  },
  {
    _id: 'fb-men-jeans-3',
    name: 'Men Jet Black Stay-Black Slim-Straight Denim Jeans',
    slug: 'men-jet-black-stay-black-slim-straight-denim-jeans',
    brand: 'ZYRIVO DENIM',
    categorySlug: 'men-bottom-wear',
    categoryName: 'Men Bottom Wear',
    price: 1800,
    discountPrice: 1099,
    ratings: 4.8,
    numReviews: 114,
    isFeatured: true,
    tags: ['men', 'men bottom wear', 'denim jeans', 'men denim jeans', 'jeans', 'black jeans', 'slim fit'],
    images: [{ url: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=800&auto=format&fit=crop' }],
    description: 'Fade-resistant jet black reactive-dyed denim jeans designed to retain rich black intensity through 40+ washes.',
  },
  {
    _id: 'fb-men-jeans-4',
    name: 'Men Light Acid Washed Relaxed Baggy Skate Denim Jeans',
    slug: 'men-light-acid-washed-relaxed-baggy-skate-denim-jeans',
    brand: 'ZYRIVO STREET',
    categorySlug: 'men-bottom-wear',
    categoryName: 'Men Bottom Wear',
    price: 1100,
    discountPrice: 649,
    ratings: 4.7,
    numReviews: 73,
    isFeatured: false,
    tags: ['men', 'men bottom wear', 'denim jeans', 'men denim jeans', 'jeans', 'baggy jeans', 'streetwear'],
    images: [{ url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=800&auto=format&fit=crop' }],
    description: '90s skate-inspired baggy loose denim jeans featuring bleached marble wash, wide straight cuffs, and deep utility pockets.',
  },
  {
    _id: 'fb-men-jeans-5',
    name: 'Men Charcoal Grey Cloud-Wash Tapered Fit Denim Jeans',
    slug: 'men-charcoal-grey-cloud-wash-tapered-fit-denim-jeans',
    brand: 'ZYRIVO DENIM',
    categorySlug: 'men-bottom-wear',
    categoryName: 'Men Bottom Wear',
    price: 1300,
    discountPrice: 749,
    ratings: 4.8,
    numReviews: 64,
    isFeatured: false,
    tags: ['men', 'men bottom wear', 'denim jeans', 'men denim jeans', 'jeans', 'grey jeans', 'tapered'],
    images: [{ url: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Modern muted charcoal grey denim jeans with cloud washing, 2% elastane flex stretch, and clean tonal stitching.',
  },

  // ─────────────────────────────────────────────────────────────
  // 7. CHINOS & TROUSERS (5 items)
  // ─────────────────────────────────────────────────────────────
  {
    _id: 'fb-men-chinos-1',
    name: 'Men Tailored Stretch Cotton Khaki Slim Fit Chinos',
    slug: 'men-tailored-stretch-cotton-khaki-slim-fit-chinos',
    brand: 'ZYRIVO CASUALS',
    categorySlug: 'men-bottom-wear',
    categoryName: 'Men Bottom Wear',
    price: 900,
    discountPrice: 499,
    ratings: 4.9,
    numReviews: 135,
    isFeatured: true,
    tags: ['men', 'men bottom wear', 'chinos & trousers', 'chinos', 'trousers', 'khakis', 'smart casual'],
    images: [{ url: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=800&auto=format&fit=crop' }],
    description: 'Essential British khaki chinos tailored in high-density cotton twill with 3% spandex for all-day comfort and sharp crease.',
  },
  {
    _id: 'fb-men-chinos-2',
    name: 'Men Smart Wrinkle-Free Navy Pleated Dress Trousers',
    slug: 'men-smart-wrinkle-free-navy-pleated-dress-trousers',
    brand: 'ZYRIVO FORMAL',
    categorySlug: 'men-bottom-wear',
    categoryName: 'Men Bottom Wear',
    price: 1400,
    discountPrice: 899,
    ratings: 4.8,
    numReviews: 97,
    isFeatured: false,
    tags: ['men', 'men bottom wear', 'chinos & trousers', 'trousers', 'formal trousers', 'pleated trousers'],
    images: [{ url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=800&auto=format&fit=crop' }],
    description: 'Classic navy dress trousers with single front pleats, expandable flex waistband, and stain-resistant poly-viscose finish.',
  },
  {
    _id: 'fb-men-chinos-3',
    name: 'Men Olive Green Heavyweight Garment-Dyed Chino Pants',
    slug: 'men-olive-green-heavyweight-garment-dyed-chino-pants',
    brand: 'ZYRIVO CASUALS',
    categorySlug: 'men-bottom-wear',
    categoryName: 'Men Bottom Wear',
    price: 2000,
    discountPrice: 1199,
    ratings: 4.8,
    numReviews: 76,
    isFeatured: true,
    tags: ['men', 'men bottom wear', 'chinos & trousers', 'chinos', 'trousers', 'olive chinos'],
    images: [{ url: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Garment-dyed military olive chinos with vintage-washed seams, angled coin pocket, and durable bar-tack reinforcement.',
  },
  {
    _id: 'fb-men-chinos-4',
    name: 'Men Minimalist Charcoal Grey Wool-Touch Formal Trousers',
    slug: 'men-minimalist-charcoal-grey-wool-touch-formal-trousers',
    brand: 'ZYRIVO FORMAL',
    categorySlug: 'men-bottom-wear',
    categoryName: 'Men Bottom Wear',
    price: 600,
    discountPrice: 349,
    ratings: 4.9,
    numReviews: 84,
    isFeatured: false,
    tags: ['men', 'men bottom wear', 'chinos & trousers', 'trousers', 'formal trousers', 'charcoal trousers'],
    images: [{ url: 'https://images.unsplash.com/photo-1555689502-c4b22d76c56f?q=80&w=800&auto=format&fit=crop' }],
    description: 'Sophisticated flat-front formal trousers in micro-textured charcoal grey wool-touch fabric with French fly and blind hem.',
  },
  {
    _id: 'fb-men-chinos-5',
    name: 'Men Sand Beige Elasticated Drawstring Comfort Chinos',
    slug: 'men-sand-beige-elasticated-drawstring-comfort-chinos',
    brand: 'ZYRIVO CASUALS',
    categorySlug: 'men-bottom-wear',
    categoryName: 'Men Bottom Wear',
    price: 1500,
    discountPrice: 949,
    ratings: 4.7,
    numReviews: 61,
    isFeatured: false,
    tags: ['men', 'men bottom wear', 'chinos & trousers', 'chinos', 'trousers', 'drawstring chinos'],
    images: [{ url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=800&auto=format&fit=crop' }],
    description: 'Modern hybrid pants blending crisp chino styling with an interior drawstring elastic waistband for smart casual ease.',
  },

  // ─────────────────────────────────────────────────────────────
  // 8. TRACK PANTS & JOGGERS (5 items)
  // ─────────────────────────────────────────────────────────────
  {
    _id: 'fb-men-joggers-1',
    name: 'Men Heavyweight French Terry Cuffed Athletic Joggers',
    slug: 'men-heavyweight-french-terry-cuffed-athletic-joggers',
    brand: 'ZYRIVO SPORTS',
    categorySlug: 'men-bottom-wear',
    categoryName: 'Men Bottom Wear',
    price: 450,
    discountPrice: 279,
    ratings: 4.9,
    numReviews: 148,
    isFeatured: true,
    tags: ['men', 'men bottom wear', 'track pants & joggers', 'joggers', 'track pants', 'sweatpants', 'gym wear'],
    images: [{ url: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?q=80&w=800&auto=format&fit=crop' }],
    description: '320 GSM dense French Terry cotton joggers equipped with zippered hip pockets, metal-tipped drawcord, and snug ankle cuffs.',
  },
  {
    _id: 'fb-men-joggers-2',
    name: 'Men Tactical Multi-Pocket Cargo Utility Track Pants',
    slug: 'men-tactical-multi-pocket-cargo-utility-track-pants',
    brand: 'ZYRIVO STREET',
    categorySlug: 'men-bottom-wear',
    categoryName: 'Men Bottom Wear',
    price: 750,
    discountPrice: 479,
    ratings: 4.8,
    numReviews: 103,
    isFeatured: true,
    tags: ['men', 'men bottom wear', 'track pants & joggers', 'joggers', 'cargo pants', 'utility pants'],
    images: [{ url: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Urban streetwear cargo track pants with 6 functional compartments, D-ring loop, water-resistant stretch twill, and tapered legs.',
  },
  {
    _id: 'fb-men-joggers-3',
    name: 'Men Dry-Fit Moisture-Wicking Performance Gym Joggers',
    slug: 'men-dry-fit-moisture-wicking-performance-gym-joggers',
    brand: 'ZYRIVO SPORTS',
    categorySlug: 'men-bottom-wear',
    categoryName: 'Men Bottom Wear',
    price: 1100,
    discountPrice: 679,
    ratings: 4.8,
    numReviews: 89,
    isFeatured: false,
    tags: ['men', 'men bottom wear', 'track pants & joggers', 'joggers', 'dry fit', 'training pants'],
    images: [{ url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=800&auto=format&fit=crop' }],
    description: 'Breathable 4-way stretch polyester elastane running joggers with laser-perforated knee ventilation and reflective calf logos.',
  },
  {
    _id: 'fb-men-joggers-4',
    name: 'Men Contrast Side-Stripe Classic Knit Track Pants',
    slug: 'men-contrast-side-stripe-classic-knit-track-pants',
    brand: 'ZYRIVO SPORTS',
    categorySlug: 'men-bottom-wear',
    categoryName: 'Men Bottom Wear',
    price: 1500,
    discountPrice: 879,
    ratings: 4.7,
    numReviews: 71,
    isFeatured: false,
    tags: ['men', 'men bottom wear', 'track pants & joggers', 'track pants', 'side stripe', 'sweatpants'],
    images: [{ url: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?q=80&w=800&auto=format&fit=crop' }],
    description: 'Retro 90s athletic track pants with dual contrast side tape stripes, open straight hem with ankle zips, and elastic waist.',
  },
  {
    _id: 'fb-men-joggers-5',
    name: 'Men Melange Grey Loungewear Everyday Fleece Joggers',
    slug: 'men-melange-grey-loungewear-everyday-fleece-joggers',
    brand: 'ZYRIVO BASICS',
    categorySlug: 'men-bottom-wear',
    categoryName: 'Men Bottom Wear',
    price: 1850,
    discountPrice: 1049,
    ratings: 4.8,
    numReviews: 82,
    isFeatured: false,
    tags: ['men', 'men bottom wear', 'track pants & joggers', 'joggers', 'fleece joggers', 'loungewear'],
    images: [{ url: 'https://images.unsplash.com/photo-1554412933-514a83d2f3c8?q=80&w=800&auto=format&fit=crop' }],
    description: 'Ultra-soft brushed fleece joggers in heather melange grey, tailored for maximum lounge coziness and easy casual wear.',
  },

  // ─────────────────────────────────────────────────────────────
  // 9. CASUAL SNEAKERS (5 items)
  // ─────────────────────────────────────────────────────────────
  {
    _id: 'fb-men-sneakers-1',
    name: 'Men Retro Leather Low-Top Street Court Casual Sneakers',
    slug: 'men-retro-leather-low-top-street-court-casual-sneakers',
    brand: 'ZYRIVO FOOTWEAR',
    categorySlug: 'footwear-sneakers',
    categoryName: 'Footwear & Sneakers',
    price: 600,
    discountPrice: 329,
    ratings: 4.9,
    numReviews: 182,
    isFeatured: true,
    tags: ['men', 'footwear', 'casual sneakers', 'sneakers', 'court sneakers', 'shoes'],
    images: [{ url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=800&auto=format&fit=crop' }],
    description: 'Classic minimalist low-top court sneakers handcrafted from full-grain leather with cushioned Ortholite insoles and gum rubber cupsole.',
  },
  {
    _id: 'fb-men-sneakers-2',
    name: 'Men Air-Cushioned Lightweight Athletic Running Sneakers',
    slug: 'men-air-cushioned-lightweight-athletic-running-sneakers',
    brand: 'ZYRIVO SPORTS',
    categorySlug: 'footwear-sneakers',
    categoryName: 'Footwear & Sneakers',
    price: 800,
    discountPrice: 529,
    ratings: 4.9,
    numReviews: 215,
    isFeatured: true,
    tags: ['men', 'footwear', 'casual sneakers', 'sneakers', 'running shoes', 'sports sneakers'],
    images: [{ url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop' }],
    description: 'High-rebound responsive EVA foam midsole running sneakers with dynamic mesh upper and slip-resistant rubber traction pod sole.',
  },
  {
    _id: 'fb-men-sneakers-3',
    name: 'Men Chunky Platform Triple-White Urban Streetwear Sneakers',
    slug: 'men-chunky-platform-triple-white-urban-streetwear-sneakers',
    brand: 'ZYRIVO STREET',
    categorySlug: 'footwear-sneakers',
    categoryName: 'Footwear & Sneakers',
    price: 1200,
    discountPrice: 729,
    ratings: 4.8,
    numReviews: 142,
    isFeatured: false,
    tags: ['men', 'footwear', 'casual sneakers', 'sneakers', 'white sneakers', 'chunky sneakers'],
    images: [{ url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=800&auto=format&fit=crop' }],
    description: 'Statement triple-white chunky streetwear silhouette with layered vegan leather panels and an elevated sculpted midsole.',
  },
  {
    _id: 'fb-men-sneakers-4',
    name: 'Men Canvas Vulcanized Skate Low-Profile Casual Sneakers',
    slug: 'men-canvas-vulcanized-skate-low-profile-casual-sneakers',
    brand: 'ZYRIVO CASUALS',
    categorySlug: 'footwear-sneakers',
    categoryName: 'Footwear & Sneakers',
    price: 1650,
    discountPrice: 979,
    ratings: 4.7,
    numReviews: 118,
    isFeatured: false,
    tags: ['men', 'footwear', 'casual sneakers', 'sneakers', 'canvas shoes', 'skate sneakers'],
    images: [{ url: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=800&auto=format&fit=crop' }],
    description: 'Durable 16 oz heavy canvas skate sneakers with waffle vulcanized rubber outsoles and reinforced double-stitched toe caps.',
  },
  {
    _id: 'fb-men-sneakers-5',
    name: 'Men Suede Panel Vintage Runner Breathable Casual Sneakers',
    slug: 'men-suede-panel-vintage-runner-breathable-casual-sneakers',
    brand: 'ZYRIVO FOOTWEAR',
    categorySlug: 'footwear-sneakers',
    categoryName: 'Footwear & Sneakers',
    price: 1850,
    discountPrice: 1149,
    ratings: 4.8,
    numReviews: 95,
    isFeatured: false,
    tags: ['men', 'footwear', 'casual sneakers', 'sneakers', 'suede sneakers', 'vintage runner'],
    images: [{ url: 'https://images.unsplash.com/photo-1582845512747-e42001c95638?q=80&w=800&auto=format&fit=crop' }],
    description: 'Retro 80s runner styling with genuine suede overlays, breathable ripstop nylon mesh, and dual-density comfort midsole.',
  },

  // ─────────────────────────────────────────────────────────────
  // 10. DERBY LEATHER SHOES (5 items)
  // ─────────────────────────────────────────────────────────────
  {
    _id: 'fb-men-derby-1',
    name: 'Men Handcrafted Tan Genuine Leather Classic Derby Shoes',
    slug: 'men-handcrafted-tan-genuine-leather-classic-derby-shoes',
    brand: 'ZYRIVO FOOTWEAR',
    categorySlug: 'footwear-sneakers',
    categoryName: 'Footwear & Sneakers',
    price: 350,
    discountPrice: 219,
    ratings: 4.9,
    numReviews: 124,
    isFeatured: true,
    tags: ['men', 'footwear', 'derby leather shoes', 'derby shoes', 'formal shoes', 'leather shoes'],
    images: [{ url: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?q=80&w=800&auto=format&fit=crop' }],
    description: 'Artisanal hand-burnished tan crust leather Derby shoes with Blake-stitched leather soles and memory foam cushioned footbed.',
  },
  {
    _id: 'fb-men-derby-2',
    name: 'Men Black Polished Calfskin Plain-Toe Formal Derby Shoes',
    slug: 'men-black-polished-calfskin-plain-toe-formal-derby-shoes',
    brand: 'ZYRIVO FOOTWEAR',
    categorySlug: 'footwear-sneakers',
    categoryName: 'Footwear & Sneakers',
    price: 650,
    discountPrice: 419,
    ratings: 4.9,
    numReviews: 168,
    isFeatured: true,
    tags: ['men', 'footwear', 'derby leather shoes', 'derby shoes', 'formal shoes', 'black shoes'],
    images: [{ url: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?q=80&w=800&auto=format&fit=crop' }],
    description: 'Sleek formal plain-toe black Derby shoes crafted from mirror-polished full calfskin leather with durable non-slip stacked heels.',
  },
  {
    _id: 'fb-men-derby-3',
    name: 'Men Wingtip Brogue Detail Hand-Burnished Brown Derby Shoes',
    slug: 'men-wingtip-brogue-detail-hand-burnished-brown-derby-shoes',
    brand: 'ZYRIVO FOOTWEAR',
    categorySlug: 'footwear-sneakers',
    categoryName: 'Footwear & Sneakers',
    price: 1000,
    discountPrice: 619,
    ratings: 4.8,
    numReviews: 96,
    isFeatured: false,
    tags: ['men', 'footwear', 'derby leather shoes', 'derby shoes', 'brogues', 'formal shoes'],
    images: [{ url: 'https://images.unsplash.com/photo-1617606002779-51d866bdd1d1?q=80&w=800&auto=format&fit=crop' }],
    description: 'Exquisite wingtip brogue perforations embellish these rich cognac brown Derby shoes featuring Goodyear welt construction.',
  },
  {
    _id: 'fb-men-derby-4',
    name: 'Men Contemporary Commando-Sole Rugged Leather Derby Shoes',
    slug: 'men-contemporary-commando-sole-rugged-leather-derby-shoes',
    brand: 'ZYRIVO ATELIER',
    categorySlug: 'footwear-sneakers',
    categoryName: 'Footwear & Sneakers',
    price: 1400,
    discountPrice: 819,
    ratings: 4.8,
    numReviews: 83,
    isFeatured: false,
    tags: ['men', 'footwear', 'derby leather shoes', 'derby shoes', 'commando sole', 'smart casual'],
    images: [{ url: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=800&auto=format&fit=crop' }],
    description: 'Modern heavy-tread Derby shoes combining oiled matte pull-up cowhide leather with a rugged lightweight commando lug sole.',
  },
  {
    _id: 'fb-men-derby-5',
    name: 'Men Suede Leather Apron-Toe Derby Casual Dress Shoes',
    slug: 'men-suede-leather-apron-toe-derby-casual-dress-shoes',
    brand: 'ZYRIVO FOOTWEAR',
    categorySlug: 'footwear-sneakers',
    categoryName: 'Footwear & Sneakers',
    price: 1800,
    discountPrice: 1019,
    ratings: 4.8,
    numReviews: 71,
    isFeatured: false,
    tags: ['men', 'footwear', 'derby leather shoes', 'derby shoes', 'suede shoes', 'derby'],
    images: [{ url: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?q=80&w=800&auto=format&fit=crop' }],
    description: 'Supple snuff suede apron-toe Derby shoes featuring contrast edge stitching and flexible crepe rubber soles.',
  },
];


