// 100 Complete, Ultra-High Quality Products across 4 Main Categories (20 Subcategories × 5 Distinct Items Each):
// 1. Watches & Timepieces (25 items)
// 2. Kids & Infant Fashion (25 items)
// 3. Home & Living (25 items)
// 4. Beauty & Personal Care (25 items)

module.exports = [
  // ═════════════════════════════════════════════════════════════
  // 1. WATCHES & TIMEPIECES (25 products: 5 Subcategories × 5 items)
  // ═════════════════════════════════════════════════════════════

  // 1.1 Chronograph Watches (5 items)
  {
    _id: 'prod-watch-chrono-1',
    name: 'Heritage Chronograph Tachymeter Stainless Steel Watch',
    slug: 'heritage-chronograph-tachymeter-stainless-steel-watch',
    brand: 'ZYRIVO HOROLOGY',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 650,
    discountPrice: 369,
    ratings: 4.9,
    numReviews: 114,
    isFeatured: true,
    tags: ['watches', 'watch', 'chronograph watches', 'chronograph', 'accessories', 'luxury watch'],
    images: [{ url: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=800&auto=format&fit=crop' }],
    description: 'Precision Japanese quartz movement chronograph featuring triple sub-dials, sapphire crystal glass, and 316L solid surgical steel link bracelet.',
  },
  {
    _id: 'prod-watch-chrono-2',
    name: 'Midnight Black Chrono Dial Leather Strap Watch',
    slug: 'midnight-black-chrono-dial-leather-strap-watch',
    brand: 'ZYRIVO HOROLOGY',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 900,
    discountPrice: 569,
    ratings: 4.8,
    numReviews: 87,
    isFeatured: false,
    tags: ['watches', 'watch', 'chronograph watches', 'chronograph', 'leather strap watch', 'accessories'],
    images: [{ url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop' }],
    description: 'Matte black ion-plated case with contrasting bronze hands, calendar aperture, and hand-stitched Italian genuine cowhide leather strap.',
  },
  {
    _id: 'prod-watch-chrono-3',
    name: 'Navy Blue Sunray Chronograph Aviation Pilot Watch',
    slug: 'navy-blue-sunray-chronograph-aviation-pilot-watch',
    brand: 'ZYRIVO HOROLOGY',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 1250,
    discountPrice: 769,
    ratings: 4.9,
    numReviews: 92,
    isFeatured: true,
    tags: ['watches', 'watch', 'chronograph watches', 'chronograph', 'pilot watch', 'accessories'],
    images: [{ url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format&fit=crop' }],
    description: 'Aeronautic-inspired sunray royal blue dial with high-contrast luminous indices, stop-seconds function, and stainless steel deployant clasp.',
  },
  {
    _id: 'prod-watch-chrono-4',
    name: 'Silver Classic Sport Multi-Function Date Chronograph',
    slug: 'silver-classic-sport-multi-function-date-chronograph',
    brand: 'ZYRIVO HOROLOGY',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 1850,
    discountPrice: 1099,
    ratings: 4.7,
    numReviews: 69,
    isFeatured: false,
    tags: ['watches', 'watch', 'chronograph watches', 'chronograph', 'sport watch', 'accessories'],
    images: [{ url: 'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?q=80&w=800&auto=format&fit=crop' }],
    description: 'Brushed silver stainless steel bezel with tachymetric inner scale, 50-meter water resistance, and polished push buttons.',
  },
  {
    _id: 'prod-watch-chrono-5',
    name: 'Dual-Time Zone World Timer Brown Leather Chronograph',
    slug: 'dual-time-zone-world-timer-brown-leather-chronograph',
    brand: 'ZYRIVO HOROLOGY',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 2000,
    discountPrice: 1249,
    ratings: 4.9,
    numReviews: 76,
    isFeatured: true,
    tags: ['watches', 'watch', 'chronograph watches', 'chronograph', 'world timer', 'accessories'],
    images: [{ url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=800&auto=format&fit=crop' }],
    description: 'Executive globetrotter timepiece with dual 24-hour sub-dial, ivory dial face, and embossed crocodile pattern genuine leather strap.',
  },

  // 1.2 Skeleton Automatic Watches (5 items)
  {
    _id: 'prod-watch-skel-1',
    name: 'Open-Heart Automatic Self-Winding Skeleton Watch',
    slug: 'open-heart-automatic-self-winding-skeleton-watch',
    brand: 'ZYRIVO HOROLOGY',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 350,
    discountPrice: 239,
    ratings: 4.9,
    numReviews: 130,
    isFeatured: true,
    tags: ['watches', 'watch', 'skeleton automatic watches', 'skeleton watch', 'automatic watch', 'luxury watch'],
    images: [{ url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?q=80&w=800&auto=format&fit=crop' }],
    description: 'Exquisite 21-jewel self-winding mechanical engine exposed front and back through exhibition caseback, requiring no battery.',
  },
  {
    _id: 'prod-watch-skel-2',
    name: 'Gunmetal Grey Steampunk Architectural Skeleton Watch',
    slug: 'gunmetal-grey-steampunk-architectural-skeleton-watch',
    brand: 'ZYRIVO HOROLOGY',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 700,
    discountPrice: 439,
    ratings: 4.8,
    numReviews: 82,
    isFeatured: false,
    tags: ['watches', 'watch', 'skeleton automatic watches', 'skeleton watch', 'mechanical watch'],
    images: [{ url: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?q=80&w=800&auto=format&fit=crop' }],
    description: 'Bold industrial geometric open bridge construction in brushed gunmetal grey with blued screws and exhibition glass.',
  },
  {
    _id: 'prod-watch-skel-3',
    name: 'Gold Accent Luxury Automatic Tourbillon-Style Skeleton Watch',
    slug: 'gold-accent-luxury-automatic-skeleton-watch',
    brand: 'ZYRIVO HOROLOGY',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 1050,
    discountPrice: 639,
    ratings: 5.0,
    numReviews: 95,
    isFeatured: true,
    tags: ['watches', 'watch', 'skeleton automatic watches', 'skeleton watch', 'gold watch'],
    images: [{ url: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Ornate 18K yellow gold ion-plated skeletonized bridge showing oscillating balance wheel with Roman numeral bezel.',
  },
  {
    _id: 'prod-watch-skel-4',
    name: 'Matte Ceramic Black Hollow Mechanical Skeleton Watch',
    slug: 'matte-ceramic-black-hollow-mechanical-skeleton-watch',
    brand: 'ZYRIVO HOROLOGY',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 1450,
    discountPrice: 839,
    ratings: 4.8,
    numReviews: 64,
    isFeatured: false,
    tags: ['watches', 'watch', 'skeleton automatic watches', 'skeleton watch', 'black watch'],
    images: [{ url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format&fit=crop' }],
    description: 'Monochromatic ultra-modern silhouette featuring scratch-resistant ceramic-coated steel and transparent balance escapement.',
  },
  {
    _id: 'prod-watch-skel-5',
    name: 'Bespoke Rose Gold Skeleton Watch with Alligator Texture Strap',
    slug: 'bespoke-rose-gold-skeleton-watch-alligator-strap',
    brand: 'ZYRIVO HOROLOGY',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 1800,
    discountPrice: 1039,
    ratings: 4.9,
    numReviews: 88,
    isFeatured: true,
    tags: ['watches', 'watch', 'skeleton automatic watches', 'skeleton watch', 'rose gold'],
    images: [{ url: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=800&auto=format&fit=crop' }],
    description: 'Regal warm rose gold casing displaying intricate gear train mechanics, paired with deep espresso brown genuine leather.',
  },

  // 1.3 Rose Gold & Minimalist Mesh Analog Watches (5 items)
  {
    _id: 'prod-watch-mesh-1',
    name: 'Ultra-Slim Rose Gold Mesh Strap Minimalist Analog Watch',
    slug: 'ultra-slim-rose-gold-mesh-strap-analog-watch',
    brand: 'ZYRIVO HOROLOGY',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 550,
    discountPrice: 299,
    ratings: 4.8,
    numReviews: 142,
    isFeatured: true,
    tags: ['watches', 'watch', 'rose gold analog watches', 'minimalist mesh watches', 'rose gold', 'mesh watch'],
    images: [{ url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop' }],
    description: 'Sleek 6.8mm ultra-thin profile with sunray champagne dial and infinitely adjustable Milanese stainless steel magnetic mesh band.',
  },
  {
    _id: 'prod-watch-mesh-2',
    name: 'Silver Sunburst Dial Scandinavian Mesh Analog Watch',
    slug: 'silver-sunburst-dial-scandinavian-mesh-analog-watch',
    brand: 'ZYRIVO HOROLOGY',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 750,
    discountPrice: 499,
    ratings: 4.7,
    numReviews: 98,
    isFeatured: false,
    tags: ['watches', 'watch', 'minimalist mesh watches', 'rose gold analog watches', 'silver watch'],
    images: [{ url: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=800&auto=format&fit=crop' }],
    description: 'Nordic minimalist aesthetics with two-hand movement, crisp silver brushed dial, and hypoallergenic stainless steel woven mesh.',
  },
  {
    _id: 'prod-watch-mesh-3',
    name: 'All-Black Stealth Minimalist Mesh Unisex Dress Watch',
    slug: 'all-black-stealth-minimalist-mesh-dress-watch',
    brand: 'ZYRIVO HOROLOGY',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 1150,
    discountPrice: 699,
    ratings: 4.9,
    numReviews: 110,
    isFeatured: true,
    tags: ['watches', 'watch', 'minimalist mesh watches', 'black watch', 'unisex watch'],
    images: [{ url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=800&auto=format&fit=crop' }],
    description: 'Deep obsidian matte black finish with gloss black stick indices and ultra-durable PVD coated fluid mesh strap.',
  },
  {
    _id: 'prod-watch-mesh-4',
    name: 'Mother of Pearl Dial Crystal Bezel Rose Gold Watch',
    slug: 'mother-of-pearl-dial-crystal-bezel-rose-gold-watch',
    brand: 'ZYRIVO HOROLOGY',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 1550,
    discountPrice: 899,
    ratings: 4.9,
    numReviews: 125,
    isFeatured: true,
    tags: ['watches', 'watch', 'rose gold analog watches', 'women watch', 'crystal watch'],
    images: [{ url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop' }],
    description: 'Iridescent natural mother-of-pearl face framed with micro-pave Austrian crystals and refined rose gold case.',
  },
  {
    _id: 'prod-watch-mesh-5',
    name: 'Champagne Gold Textured Dial Classic Mesh Dress Watch',
    slug: 'champagne-gold-textured-dial-classic-mesh-dress-watch',
    brand: 'ZYRIVO HOROLOGY',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 2100,
    discountPrice: 1299,
    ratings: 4.8,
    numReviews: 83,
    isFeatured: false,
    tags: ['watches', 'watch', 'minimalist mesh watches', 'gold watch', 'analog watch'],
    images: [{ url: 'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?q=80&w=800&auto=format&fit=crop' }],
    description: 'Vintage-inspired guilloche patterned dial with golden faceted lance hands and quick-release interchangeable mesh bracelet.',
  },

  // 1.4 Smartwatches & Fitness Trackers (5 items)
  {
    _id: 'prod-watch-smart-1',
    name: 'Titanium Smartwatch with AMOLED Display & Bluetooth Calling',
    slug: 'titanium-smartwatch-amoled-display-bluetooth-calling',
    brand: 'ZYRIVO TECH',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 300,
    discountPrice: 199,
    ratings: 4.8,
    numReviews: 210,
    isFeatured: true,
    tags: ['watches', 'watch', 'smartwatches', 'smartwatch', 'fitness tracker', 'amoled'],
    images: [{ url: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800&auto=format&fit=crop' }],
    description: 'Vibrant 1.43-inch Always-On AMOLED screen with 60Hz refresh rate, continuous SpO2/heart rate monitoring, and 7-day battery life.',
  },
  {
    _id: 'prod-watch-smart-2',
    name: 'Rose Gold Smartwatch with Floral Milanese Strap',
    slug: 'rose-gold-smartwatch-floral-milanese-strap',
    brand: 'ZYRIVO TECH',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 650,
    discountPrice: 399,
    ratings: 4.9,
    numReviews: 175,
    isFeatured: true,
    tags: ['watches', 'watch', 'smartwatches', 'smartwatch', 'women smartwatch'],
    images: [{ url: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=800&auto=format&fit=crop' }],
    description: 'Elegant jewelry-styled smartwatch designed for women with menstrual cycle tracking, sleep stages, and customized designer watch faces.',
  },
  {
    _id: 'prod-watch-smart-3',
    name: 'Rugged Military Outdoor GPS Sport Smartwatch',
    slug: 'rugged-military-outdoor-gps-sport-smartwatch',
    brand: 'ZYRIVO TECH',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 1000,
    discountPrice: 599,
    ratings: 4.8,
    numReviews: 130,
    isFeatured: false,
    tags: ['watches', 'watch', 'smartwatches', 'smartwatch', 'sports smartwatch', 'gps'],
    images: [{ url: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?q=80&w=800&auto=format&fit=crop' }],
    description: 'Impact-resistant reinforced polycarbonate body with dual-satellite GPS, 100+ workout modes, and 5ATM waterproof certification.',
  },
  {
    _id: 'prod-watch-smart-4',
    name: 'Minimalist Square Smart Watch with Silicone Sport Band',
    slug: 'minimalist-square-smart-watch-silicone-sport-band',
    brand: 'ZYRIVO TECH',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 400,
    discountPrice: 249,
    ratings: 4.7,
    numReviews: 188,
    isFeatured: false,
    tags: ['watches', 'watch', 'smartwatches', 'smartwatch', 'smart fitness'],
    images: [{ url: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?q=80&w=800&auto=format&fit=crop' }],
    description: 'Feather-light 38g ergonomic square form factor with IP68 dust-waterproof rating, camera shutter remote, and music control.',
  },
  {
    _id: 'prod-watch-smart-5',
    name: 'Executive Ceramic Bezel Smartwatch with Leather Hybrid Strap',
    slug: 'executive-ceramic-bezel-smartwatch-leather-strap',
    brand: 'ZYRIVO TECH',
    categorySlug: 'watches-timepieces',
    categoryName: 'Watches & Timepieces',
    price: 1400,
    discountPrice: 799,
    ratings: 4.9,
    numReviews: 95,
    isFeatured: true,
    tags: ['watches', 'watch', 'smartwatches', 'smartwatch', 'executive smartwatch'],
    images: [{ url: 'https://images.unsplash.com/photo-1510017803434-a899398421b3?q=80&w=800&auto=format&fit=crop' }],
    description: 'Seamlessly pairs executive boardroom styling with full digital capabilities, voice assistant integration, and wireless fast charging.',
  },

  // 1.5 Polarized & Aviator Sunglasses (5 items)
  {
    _id: 'prod-watch-sunglass-1',
    name: 'Classic Gold Frame Green Polarized Aviator Sunglasses',
    slug: 'classic-gold-frame-green-polarized-aviator-sunglasses',
    brand: 'ZYRIVO EYEWEAR',
    categorySlug: 'accessories-jewelry',
    categoryName: 'Accessories & Jewelry',
    price: 650,
    discountPrice: 349,
    ratings: 4.9,
    numReviews: 165,
    isFeatured: true,
    tags: ['sunglasses', 'polarized sunglasses', 'aviator sunglasses', 'aviators', 'accessories'],
    images: [{ url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=800&auto=format&fit=crop' }],
    description: 'Timeless teardrop aviator silhouette with scratch-resistant polarized G-15 crystal glass lenses offering 100% UV400 defense.',
  },
  {
    _id: 'prod-watch-sunglass-2',
    name: 'Retro Square Acetate Polarized Sunglasses in Gloss Black',
    slug: 'retro-square-acetate-polarized-sunglasses-gloss-black',
    brand: 'ZYRIVO EYEWEAR',
    categorySlug: 'accessories-jewelry',
    categoryName: 'Accessories & Jewelry',
    price: 1550,
    discountPrice: 999,
    ratings: 4.8,
    numReviews: 120,
    isFeatured: false,
    tags: ['sunglasses', 'polarized sunglasses', 'square sunglasses', 'accessories'],
    images: [{ url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=800&auto=format&fit=crop' }],
    description: 'Handcrafted Italian cellulose acetate frames with five-barrel hinges and anti-glare polarized grey gradient lenses.',
  },
  {
    _id: 'prod-watch-sunglass-3',
    name: 'Vintage Tortoise Shell Round Polarized Sunglasses',
    slug: 'vintage-tortoise-shell-round-polarized-sunglasses',
    brand: 'ZYRIVO EYEWEAR',
    categorySlug: 'accessories-jewelry',
    categoryName: 'Accessories & Jewelry',
    price: 750,
    discountPrice: 449,
    ratings: 4.8,
    numReviews: 94,
    isFeatured: true,
    tags: ['sunglasses', 'polarized sunglasses', 'round sunglasses', 'tortoise shell', 'accessories'],
    images: [{ url: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?q=80&w=800&auto=format&fit=crop' }],
    description: 'Warm amber tortoise finish with keyhole nose bridge and copper-tinted polarized optics that elevate contrast in bright sun.',
  },
  {
    _id: 'prod-watch-sunglass-4',
    name: 'Gunmetal Modern Rimless Lightweight Aviator Sunglasses',
    slug: 'gunmetal-modern-rimless-lightweight-aviator-sunglasses',
    brand: 'ZYRIVO EYEWEAR',
    categorySlug: 'accessories-jewelry',
    categoryName: 'Accessories & Jewelry',
    price: 1200,
    discountPrice: 699,
    ratings: 4.7,
    numReviews: 88,
    isFeatured: false,
    tags: ['sunglasses', 'aviator sunglasses', 'polarized sunglasses', 'rimless', 'accessories'],
    images: [{ url: 'https://images.unsplash.com/photo-1577803645773-f96470509666?q=80&w=800&auto=format&fit=crop' }],
    description: 'Aerodynamic feather-weight titanium alloy construction with flexible spring temples and shatterproof polycarbonate lenses.',
  },
  {
    _id: 'prod-watch-sunglass-5',
    name: 'Mirrored Blue Lens Polarized Sports Sunglasses',
    slug: 'mirrored-blue-lens-polarized-sports-sunglasses',
    brand: 'ZYRIVO EYEWEAR',
    categorySlug: 'accessories-jewelry',
    categoryName: 'Accessories & Jewelry',
    price: 500,
    discountPrice: 299,
    ratings: 4.9,
    numReviews: 105,
    isFeatured: true,
    tags: ['sunglasses', 'polarized sunglasses', 'sport sunglasses', 'mirrored sunglasses', 'accessories'],
    images: [{ url: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?q=80&w=800&auto=format&fit=crop' }],
    description: 'High-energy sapphire blue flash mirror coating with rubberized non-slip nose grips, ideal for driving, outdoor sports, and beach.',
  },

  // ═════════════════════════════════════════════════════════════
  // 2. KIDS & INFANT FASHION (25 products: 5 Subcategories × 5 items)
  // ═════════════════════════════════════════════════════════════

  // 2.1 Boys T-Shirts & Polos (5 items)
  {
    _id: 'prod-kids-boy-tee-1',
    name: 'Boys Pure Organic Cotton Dinosaur Graphic Print T-Shirt',
    slug: 'boys-pure-cotton-dinosaur-graphic-t-shirt',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 850,
    discountPrice: 549,
    ratings: 4.8,
    numReviews: 85,
    isFeatured: true,
    tags: ['kids', 'boys', 'boys t-shirts', 'boys tees', 't-shirt', 'graphic tee'],
    images: [{ url: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=800&auto=format&fit=crop' }],
    description: '100% combed skin-friendly breathable cotton t-shirt with cheerful non-toxic water-based dinosaur screen print and tagless neck label.',
  },
  {
    _id: 'prod-kids-boy-tee-2',
    name: 'Boys Striped Collar Pique Cotton Casual Polo T-Shirt',
    slug: 'boys-striped-collar-pique-cotton-polo-t-shirt',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 1350,
    discountPrice: 849,
    ratings: 4.9,
    numReviews: 64,
    isFeatured: false,
    tags: ['kids', 'boys', 'boys t-shirts', 'polo', 'boys polo'],
    images: [{ url: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=800&auto=format&fit=crop' }],
    description: 'Smart ribbed collar with color-block dual tipping, two-button placket placket, and breathable honeycomb knit fabric.',
  },
  {
    _id: 'prod-kids-boy-tee-3',
    name: 'Boys Super-Hero Space Astronaut Soft Cotton T-Shirt',
    slug: 'boys-space-astronaut-soft-cotton-t-shirt',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 1800,
    discountPrice: 1099,
    ratings: 4.8,
    numReviews: 72,
    isFeatured: true,
    tags: ['kids', 'boys', 'boys t-shirts', 'astronaut', 't-shirt'],
    images: [{ url: 'https://images.unsplash.com/photo-1503945438517-f65904a52ce6?q=80&w=800&auto=format&fit=crop' }],
    description: 'Deep galaxy navy blue graphic tee with glow-in-the-dark space shuttle elements and reinforced double needle hems.',
  },
  {
    _id: 'prod-kids-boy-tee-4',
    name: 'Boys Color-Blocked Cotton Raglan Sleeve Everyday Tee',
    slug: 'boys-color-blocked-raglan-sleeve-everyday-tee',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 1100,
    discountPrice: 649,
    ratings: 4.7,
    numReviews: 53,
    isFeatured: false,
    tags: ['kids', 'boys', 'boys t-shirts', 'raglan tee', 'cotton'],
    images: [{ url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Sporty baseball style raglan cut sleeves offering complete freedom of movement during playground running and sports.',
  },
  {
    _id: 'prod-kids-boy-tee-5',
    name: 'Boys Summer Tropical Surf Board Graphic Crew Neck T-Shirt',
    slug: 'boys-summer-surf-board-graphic-t-shirt',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 1300,
    discountPrice: 749,
    ratings: 4.8,
    numReviews: 61,
    isFeatured: true,
    tags: ['kids', 'boys', 'boys t-shirts', 'summer tee', 'kids clothing'],
    images: [{ url: 'https://images.unsplash.com/photo-1485546246426-74dc88dec4d9?q=80&w=800&auto=format&fit=crop' }],
    description: 'Vibrant sun yellow t-shirt with coastal surf artwork, made from pre-shrunk cotton that stays soft after dozens of washes.',
  },

  // 2.2 Boys Jeans & Joggers (5 items)
  {
    _id: 'prod-kids-boy-jean-1',
    name: 'Boys Elastic Waistband Comfort Stretch Denim Jeans',
    slug: 'boys-elastic-waistband-comfort-stretch-denim-jeans',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 900,
    discountPrice: 499,
    ratings: 4.8,
    numReviews: 92,
    isFeatured: true,
    tags: ['kids', 'boys', 'boys jeans', 'kids jeans', 'denim'],
    images: [{ url: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=800&auto=format&fit=crop' }],
    description: 'Easy pull-on elastic waistband with internal adjustable drawcord, flexible spandex stretch denim, and soft interior seams.',
  },
  {
    _id: 'prod-kids-boy-jean-2',
    name: 'Boys Ribbed Cuff French Terry Cargo Jogger Pants',
    slug: 'boys-ribbed-cuff-french-terry-cargo-jogger-pants',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 1400,
    discountPrice: 899,
    ratings: 4.9,
    numReviews: 78,
    isFeatured: false,
    tags: ['kids', 'boys', 'boys jeans', 'boys joggers', 'cargo pants'],
    images: [{ url: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=800&auto=format&fit=crop' }],
    description: 'Cozy combed cotton loopback terry with dual utilitarian cargo pockets and snug ankle cuffs for all-day active play.',
  },
  {
    _id: 'prod-kids-boy-jean-3',
    name: 'Boys Slim Fit Washed Blue Denim Jeans with Pockets',
    slug: 'boys-slim-fit-washed-blue-denim-jeans',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 2000,
    discountPrice: 1199,
    ratings: 4.7,
    numReviews: 66,
    isFeatured: true,
    tags: ['kids', 'boys', 'boys jeans', 'slim jeans', 'denim'],
    images: [{ url: 'https://images.unsplash.com/photo-1503945438517-f65904a52ce6?q=80&w=800&auto=format&fit=crop' }],
    description: 'Trendy stone-washed fade aesthetic with functional 5-pocket design, rivet accents, and child-safe snap closure.',
  },
  {
    _id: 'prod-kids-boy-jean-4',
    name: 'Boys Camouflage Print Athletic Cotton Track Pants',
    slug: 'boys-camouflage-print-athletic-cotton-track-pants',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 600,
    discountPrice: 349,
    ratings: 4.8,
    numReviews: 57,
    isFeatured: false,
    tags: ['kids', 'boys', 'boys jeans', 'track pants', 'camo'],
    images: [{ url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Tactical woodland green camo print joggers crafted with reinforced knee panels to prevent wear and tear during play.',
  },
  {
    _id: 'prod-kids-boy-jean-5',
    name: 'Boys Khaki Chino Trousers with Adjustable Waistband',
    slug: 'boys-khaki-chino-trousers-adjustable-waistband',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 1500,
    discountPrice: 949,
    ratings: 4.9,
    numReviews: 81,
    isFeatured: true,
    tags: ['kids', 'boys', 'boys jeans', 'chinos', 'boys trousers'],
    images: [{ url: 'https://images.unsplash.com/photo-1485546246426-74dc88dec4d9?q=80&w=800&auto=format&fit=crop' }],
    description: 'Crisp pre-washed cotton twill chinos suitable for birthdays, school functions, and family gatherings.',
  },

  // 2.3 Girls Frocks & Party Dresses (5 items)
  {
    _id: 'prod-kids-girl-frock-1',
    name: 'Girls Pastel Floral Print Cotton Tiered Summer Frock',
    slug: 'girls-pastel-floral-print-cotton-summer-frock',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 450,
    discountPrice: 279,
    ratings: 4.9,
    numReviews: 108,
    isFeatured: true,
    tags: ['kids', 'girls', 'girls frocks & dresses', 'frocks', 'dresses', 'girls dress'],
    images: [{ url: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?q=80&w=800&auto=format&fit=crop' }],
    description: 'Flowing tiered A-line cotton dress with delicate wildflower prints, flutter butterfly sleeves, and soft inner lining.',
  },
  {
    _id: 'prod-kids-girl-frock-2',
    name: 'Girls Sequin Embellished Fluffy Net Party Tutu Dress',
    slug: 'girls-sequin-embellished-net-party-tutu-dress',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 750,
    discountPrice: 479,
    ratings: 4.9,
    numReviews: 124,
    isFeatured: true,
    tags: ['kids', 'girls', 'girls frocks & dresses', 'party dress', 'tutu dress'],
    images: [{ url: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Birthday princess aesthetic with shimmering sequined bodice, multi-layer puffy tulle skirt, and satin waist bow tie.',
  },
  {
    _id: 'prod-kids-girl-frock-3',
    name: 'Girls Yellow Polka Dot Ruffled Hem Casual Sundress',
    slug: 'girls-yellow-polka-dot-ruffled-hem-sundress',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 1100,
    discountPrice: 679,
    ratings: 4.8,
    numReviews: 89,
    isFeatured: false,
    tags: ['kids', 'girls', 'girls frocks & dresses', 'polka dot', 'frock'],
    images: [{ url: 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?q=80&w=800&auto=format&fit=crop' }],
    description: 'Cheerful retro sunshine yellow frock with white polka dots, cross-back button straps, and playful ruffled bottom hem.',
  },
  {
    _id: 'prod-kids-girl-frock-4',
    name: 'Girls Lace Collar Embroidery Velvet Winter Party Frock',
    slug: 'girls-lace-collar-velvet-winter-party-frock',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 1500,
    discountPrice: 879,
    ratings: 4.9,
    numReviews: 76,
    isFeatured: true,
    tags: ['kids', 'girls', 'girls frocks & dresses', 'velvet dress', 'winter frock'],
    images: [{ url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=800&auto=format&fit=crop' }],
    description: 'Rich royal ruby velvet with vintage Peter Pan lace collar, gathered waistline, and back zipper closure.',
  },
  {
    _id: 'prod-kids-girl-frock-5',
    name: 'Girls Rainbow Striped Knit Cotton Skater Dress',
    slug: 'girls-rainbow-striped-knit-cotton-skater-dress',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 1850,
    discountPrice: 1049,
    ratings: 4.7,
    numReviews: 63,
    isFeatured: false,
    tags: ['kids', 'girls', 'girls frocks & dresses', 'rainbow dress', 'cotton dress'],
    images: [{ url: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?q=80&w=800&auto=format&fit=crop' }],
    description: 'Bright cheerful horizontal rainbow stripes in stretchy rib-knit cotton, perfect for school picnics and everyday wear.',
  },

  // 2.4 Baby Rompers & Onesies (5 items)
  {
    _id: 'prod-kids-baby-romp-1',
    name: 'Newborn 100% Organic Bamboo Cotton Snap-Button Romper',
    slug: 'newborn-organic-bamboo-cotton-snap-romper',
    brand: 'ZYRIVO BABY',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 600,
    discountPrice: 329,
    ratings: 4.9,
    numReviews: 145,
    isFeatured: true,
    tags: ['kids', 'baby', 'baby rompers', 'onesie', 'infant wear'],
    images: [{ url: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?q=80&w=800&auto=format&fit=crop' }],
    description: 'Hypoallergenic silky-soft organic bamboo fabric with full crotch snap buttons for swift and hassle-free diaper changes.',
  },
  {
    _id: 'prod-kids-baby-romp-2',
    name: 'Infant Animal Ears Hooded Fleece Cozy Winter Sleepsuit',
    slug: 'infant-animal-ears-hooded-fleece-winter-sleepsuit',
    brand: 'ZYRIVO BABY',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 800,
    discountPrice: 529,
    ratings: 5.0,
    numReviews: 160,
    isFeatured: true,
    tags: ['kids', 'baby', 'baby rompers', 'sleepsuit', 'baby fleece'],
    images: [{ url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=800&auto=format&fit=crop' }],
    description: 'Adorable bear ear hood with ultra-plush sherpa fleece, enclosed footies, and two-way zipper from neck to feet.',
  },
  {
    _id: 'prod-kids-baby-romp-3',
    name: 'Baby Unisex Pastel Cloud Print Cotton Sleeveless Jumpsuit',
    slug: 'baby-unisex-pastel-cloud-cotton-sleeveless-jumpsuit',
    brand: 'ZYRIVO BABY',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 1200,
    discountPrice: 729,
    ratings: 4.8,
    numReviews: 94,
    isFeatured: false,
    tags: ['kids', 'baby', 'baby rompers', 'onesie', 'baby jumpsuit'],
    images: [{ url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?q=80&w=800&auto=format&fit=crop' }],
    description: 'Airy combed cotton muslin blend keeping baby cool during sweltering summers, with flatlock non-scratch seams.',
  },
  {
    _id: 'prod-kids-baby-romp-4',
    name: 'Infant Striped Cotton Dungaree Romper with Mock T-Shirt',
    slug: 'infant-striped-cotton-dungaree-romper-mock-tee',
    brand: 'ZYRIVO BABY',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 1650,
    discountPrice: 979,
    ratings: 4.8,
    numReviews: 76,
    isFeatured: true,
    tags: ['kids', 'baby', 'baby rompers', 'dungaree', 'baby wear'],
    images: [{ url: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?q=80&w=800&auto=format&fit=crop' }],
    description: 'Charming 2-in-1 layered effect dungaree suit featuring anchor embroidery, adjustable shoulder straps, and soft rib knit.',
  },
  {
    _id: 'prod-kids-baby-romp-5',
    name: 'Pack of 3 Cotton Short Sleeve Bodysuits for Babies',
    slug: 'pack-of-3-cotton-short-sleeve-bodysuits-babies',
    brand: 'ZYRIVO BABY',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 1850,
    discountPrice: 1149,
    ratings: 4.9,
    numReviews: 182,
    isFeatured: false,
    tags: ['kids', 'baby', 'baby rompers', 'bodysuit', 'multipack'],
    images: [{ url: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?q=80&w=800&auto=format&fit=crop' }],
    description: 'Envelope neck design stretches gently over baby head without stretching out, crafted from 100% natural pure cotton.',
  },

  // 2.5 Kids Sneakers & Footwear (5 items)
  {
    _id: 'prod-kids-shoes-1',
    name: 'Kids Lightweight Breathable Mesh Velcro Sport Sneakers',
    slug: 'kids-lightweight-breathable-mesh-velcro-sneakers',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 350,
    discountPrice: 219,
    ratings: 4.8,
    numReviews: 115,
    isFeatured: true,
    tags: ['kids', 'kids sneakers', 'kids shoes', 'footwear', 'velcro shoes'],
    images: [{ url: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?q=80&w=800&auto=format&fit=crop' }],
    description: 'Self-fastening hook-and-loop velcro closure, featherweight shock-absorbing EVA foam sole, and anti-slip rubber traction.',
  },
  {
    _id: 'prod-kids-shoes-2',
    name: 'Kids Classic White Low-Top Leather Court Sneakers',
    slug: 'kids-classic-white-low-top-leather-court-sneakers',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 650,
    discountPrice: 419,
    ratings: 4.9,
    numReviews: 98,
    isFeatured: true,
    tags: ['kids', 'kids sneakers', 'kids shoes', 'white sneakers'],
    images: [{ url: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=800&auto=format&fit=crop' }],
    description: 'Easy-to-clean synthetic leather upper with cushioned OrthoLite insole and non-marking vulcanized rubber cupsole.',
  },
  {
    _id: 'prod-kids-shoes-3',
    name: 'Kids LED Light-Up Sole Casual Running Shoes',
    slug: 'kids-led-light-up-sole-casual-running-shoes',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 1000,
    discountPrice: 619,
    ratings: 4.9,
    numReviews: 140,
    isFeatured: false,
    tags: ['kids', 'kids sneakers', 'kids shoes', 'led shoes', 'light up shoes'],
    images: [{ url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=800&auto=format&fit=crop' }],
    description: 'Multi-colored flashing heel lights that ignite with every jump and step, housed in a waterproof sealed transparent midsole.',
  },
  {
    _id: 'prod-kids-shoes-4',
    name: 'Kids Canvas Slip-On Casual Loafers with Elastic Gores',
    slug: 'kids-canvas-slip-on-casual-loafers',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 1400,
    discountPrice: 819,
    ratings: 4.7,
    numReviews: 83,
    isFeatured: true,
    tags: ['kids', 'kids sneakers', 'kids shoes', 'canvas shoes', 'slip on'],
    images: [{ url: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=800&auto=format&fit=crop' }],
    description: 'Durable washed canvas with dual stretch elastic gores for effortless slip-on wear, padded collars, and waffle tread.',
  },
  {
    _id: 'prod-kids-shoes-5',
    name: 'Kids Smart Formal Uniform School Shoes with Cushioned Sole',
    slug: 'kids-smart-formal-uniform-school-shoes',
    brand: 'ZYRIVO KIDS',
    categorySlug: 'kids-wear',
    categoryName: 'Kids Wear',
    price: 1800,
    discountPrice: 1019,
    ratings: 4.8,
    numReviews: 112,
    isFeatured: false,
    tags: ['kids', 'kids sneakers', 'school shoes', 'kids shoes', 'formal'],
    images: [{ url: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?q=80&w=800&auto=format&fit=crop' }],
    description: 'High-shine scuff-resistant polished black upper with antibacterial sanitized insole, built for rigorous daily school routine.',
  },

  // ═════════════════════════════════════════════════════════════
  // 3. HOME & LIVING (25 products: 5 Subcategories × 5 items)
  // ═════════════════════════════════════════════════════════════

  // 3.1 Pure Cotton Bedsheets & Bedding (5 items)
  {
    _id: 'prod-home-bed-1',
    name: '300 TC 100% Pure Glace Cotton King Size Bedsheet with 2 Pillow Covers',
    slug: '300-tc-glace-cotton-king-size-bedsheet',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 650,
    discountPrice: 369,
    ratings: 4.9,
    numReviews: 180,
    isFeatured: true,
    tags: ['home', 'home & living', 'cotton bedsheets', 'bedsheets', 'bedding', 'king size'],
    images: [{ url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=800&auto=format&fit=crop' }],
    description: 'Luxurious 300 thread count long-staple combed cotton bedsheet with geometric damask print, color-fast dyeing, and breathable weave.',
  },
  {
    _id: 'prod-home-bed-2',
    name: 'Floral Jaipuri Hand-Block Print Sanganeri Cotton Bedsheet',
    slug: 'floral-jaipuri-hand-block-print-bedsheet',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 900,
    discountPrice: 569,
    ratings: 4.8,
    numReviews: 142,
    isFeatured: false,
    tags: ['home', 'home & living', 'cotton bedsheets', 'bedsheets', 'jaipuri', 'block print'],
    images: [{ url: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=800&auto=format&fit=crop' }],
    description: 'Traditional artisan hand-block stamped bedsheet crafted in pure Rajasthani cotton with matching border-printed envelope pillow covers.',
  },
  {
    _id: 'prod-home-bed-3',
    name: 'Hotel Luxury Egyptian Satin Striped White King Fitted Sheet',
    slug: 'hotel-luxury-egyptian-satin-striped-white-bedsheet',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 1250,
    discountPrice: 769,
    ratings: 5.0,
    numReviews: 215,
    isFeatured: true,
    tags: ['home', 'home & living', 'cotton bedsheets', 'bedsheets', 'hotel luxury', 'white bedsheet'],
    images: [{ url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=800&auto=format&fit=crop' }],
    description: 'Crisp 5-star hotel 1cm satin weave stripe pattern offering silky smooth drape, deep corner pockets, and cooling airflow.',
  },
  {
    _id: 'prod-home-bed-4',
    name: 'Bohemian Mandala Indigo Blue Printed Queen Bedsheet',
    slug: 'bohemian-mandala-indigo-blue-printed-queen-bedsheet',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 1850,
    discountPrice: 1099,
    ratings: 4.7,
    numReviews: 95,
    isFeatured: false,
    tags: ['home', 'home & living', 'cotton bedsheets', 'bedsheets', 'mandala', 'boho'],
    images: [{ url: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=800&auto=format&fit=crop' }],
    description: 'Intricate circular kaleidoscope mandala artwork in natural indigo and teal, pre-washed for zero shrinkage and ultra softness.',
  },
  {
    _id: 'prod-home-bed-5',
    name: 'All-Weather Microfiber Micro-Quilted Reversible AC Comforter',
    slug: 'all-weather-microfiber-quilted-reversible-comforter',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 2000,
    discountPrice: 1249,
    ratings: 4.9,
    numReviews: 168,
    isFeatured: true,
    tags: ['home', 'home & living', 'cotton bedsheets', 'blankets & quilts', 'comforter', 'ac quilt'],
    images: [{ url: 'https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?q=80&w=800&auto=format&fit=crop' }],
    description: 'Hypoallergenic 200 GSM hollow siliconized microfiber filling with diamond baffle box stitching to prevent clumping.',
  },

  // 3.2 Curtains & Window Drapes (5 items)
  {
    _id: 'prod-home-curt-1',
    name: 'Thermal Insulated Blackout Grommet Eyelet Window Curtains (Set of 2)',
    slug: 'thermal-insulated-blackout-eyelet-curtains-set-of-2',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 350,
    discountPrice: 239,
    ratings: 4.8,
    numReviews: 154,
    isFeatured: true,
    tags: ['home', 'home & living', 'curtains & drapes', 'curtains', 'blackout curtains', 'drapes'],
    images: [{ url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop' }],
    description: 'Triple weave high-density blackout fabric blocks 95% sunlight and UV rays, reduces outside noise, and balances room temperature.',
  },
  {
    _id: 'prod-home-curt-2',
    name: 'Sheer Linen Blend Textured Semi-Transparent Door Curtains (Set of 2)',
    slug: 'sheer-linen-blend-textured-door-curtains',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 700,
    discountPrice: 439,
    ratings: 4.9,
    numReviews: 120,
    isFeatured: true,
    tags: ['home', 'home & living', 'curtains & drapes', 'curtains', 'sheer curtains'],
    images: [{ url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop' }],
    description: 'Airy flax linen textured semi-sheer panels that gently filter harsh natural light while preserving living room daytime privacy.',
  },
  {
    _id: 'prod-home-curt-3',
    name: 'Lustrous Velvet Heavy Drape Bedroom Eyelet Curtains',
    slug: 'lustrous-velvet-heavy-drape-bedroom-curtains',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 1050,
    discountPrice: 639,
    ratings: 4.9,
    numReviews: 88,
    isFeatured: false,
    tags: ['home', 'home & living', 'curtains & drapes', 'curtains', 'velvet curtains'],
    images: [{ url: 'https://images.unsplash.com/photo-1615873968403-89e068629265?q=80&w=800&auto=format&fit=crop' }],
    description: 'Sumptuous plush velvet curtains in deep forest green with rust-proof silver eyelets, creating an ultra-luxurious palace ambience.',
  },
  {
    _id: 'prod-home-curt-4',
    name: 'Geometric Modern Jacquard Weave Living Room Long Drapes',
    slug: 'geometric-modern-jacquard-weave-living-room-drapes',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 1450,
    discountPrice: 839,
    ratings: 4.7,
    numReviews: 73,
    isFeatured: true,
    tags: ['home', 'home & living', 'curtains & drapes', 'curtains', 'jacquard'],
    images: [{ url: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?q=80&w=800&auto=format&fit=crop' }],
    description: 'Contemporary Scandinavian chevron metallic weave with weighted hem corners to guarantee flawless vertical draping.',
  },
  {
    _id: 'prod-home-curt-5',
    name: 'Embroidered Sheer Voile White Window Curtains with Rod Pocket',
    slug: 'embroidered-sheer-voile-white-window-curtains',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 1800,
    discountPrice: 1039,
    ratings: 4.8,
    numReviews: 65,
    isFeatured: false,
    tags: ['home', 'home & living', 'curtains & drapes', 'curtains', 'voile'],
    images: [{ url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?q=80&w=800&auto=format&fit=crop' }],
    description: 'Delicate white floral trail embroidery on crisp sheer voile fabric, creating a breezy, serene and sunlit room vibe.',
  },

  // 3.3 Cushions & Pillow Covers (5 items)
  {
    _id: 'prod-home-cush-1',
    name: 'Bohemian Tufted Cotton Throw Pillow Cushion Covers (Set of 5)',
    slug: 'bohemian-tufted-cotton-throw-pillow-cushion-covers',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 550,
    discountPrice: 299,
    ratings: 4.9,
    numReviews: 162,
    isFeatured: true,
    tags: ['home', 'home & living', 'cushions & covers', 'cushion covers', 'pillow covers', 'boho'],
    images: [{ url: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=800&auto=format&fit=crop' }],
    description: 'Handcrafted artisan woven textured tufts with chic corner fringe tassels, hidden invisible zipper, and thick canvas backing.',
  },
  {
    _id: 'prod-home-cush-2',
    name: 'Soft Velvet Solid Color Sofa Decorative Cushion Covers (Pack of 5)',
    slug: 'soft-velvet-solid-sofa-cushion-covers-pack-of-5',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 750,
    discountPrice: 499,
    ratings: 4.8,
    numReviews: 135,
    isFeatured: false,
    tags: ['home', 'home & living', 'cushions & covers', 'cushion covers', 'velvet cushions'],
    images: [{ url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Silky smooth high-grade velvet in opulent jewel tones (emerald, mustard, teal, ruby, navy) with robust surge overlock stitching.',
  },
  {
    _id: 'prod-home-cush-3',
    name: 'Embroidered Metallic Zari Silk Festive Cushion Covers (Pack of 5)',
    slug: 'embroidered-metallic-zari-silk-cushion-covers',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 1150,
    discountPrice: 699,
    ratings: 4.9,
    numReviews: 110,
    isFeatured: true,
    tags: ['home', 'home & living', 'cushions & covers', 'cushion covers', 'festive cushions'],
    images: [{ url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=800&auto=format&fit=crop' }],
    description: 'Raw silk dupion base adorned with traditional Mughal floral resham embroidery and golden cord piping for festive celebrations.',
  },
  {
    _id: 'prod-home-cush-4',
    name: 'Abstract Geometric Modern Canvas Couch Throw Pillows',
    slug: 'abstract-geometric-modern-canvas-throw-pillows',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 1550,
    discountPrice: 899,
    ratings: 4.7,
    numReviews: 74,
    isFeatured: false,
    tags: ['home', 'home & living', 'cushions & covers', 'cushion covers', 'modern decor'],
    images: [{ url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=800&auto=format&fit=crop' }],
    description: 'Contemporary minimalist mid-century Bauhaus graphic prints on thick eco-friendly combed cotton linen canvas.',
  },
  {
    _id: 'prod-home-cush-5',
    name: 'Faux Fur Fluffy Shaggy Luxury Accent Pillows with Inserts',
    slug: 'faux-fur-fluffy-shaggy-luxury-accent-pillows',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 2100,
    discountPrice: 1299,
    ratings: 4.9,
    numReviews: 95,
    isFeatured: true,
    tags: ['home', 'home & living', 'cushions & covers', 'cushion covers', 'faux fur'],
    images: [{ url: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=800&auto=format&fit=crop' }],
    description: 'Ultra-cuddly high-pile Mongolian faux fur with plush microfiber micro-cushion filler included for ultimate cozy comfort.',
  },

  // 3.4 Cookware Sets & Non-Stick Kitchenware (5 items)
  {
    _id: 'prod-home-cook-1',
    name: 'Granite Finish 5-Layer Induction Non-Stick Cookware Set (3 Pcs)',
    slug: 'granite-finish-5-layer-induction-cookware-set',
    brand: 'ZYRIVO CHEF',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 300,
    discountPrice: 199,
    ratings: 4.8,
    numReviews: 175,
    isFeatured: true,
    tags: ['home', 'home & living', 'cookware sets', 'kitchenware', 'non stick', 'cookware'],
    images: [{ url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=800&auto=format&fit=crop' }],
    description: 'Includes Frying Pan, Kadhai with Tempered Glass Lid, and Dosa Tawa coated with 100% PFOA-free Greblon German non-stick granite coating.',
  },
  {
    _id: 'prod-home-cook-2',
    name: 'Tri-Ply Heavy Gauge Stainless Steel Cooking Pot Casserole Set',
    slug: 'tri-ply-stainless-steel-cooking-pot-set',
    brand: 'ZYRIVO CHEF',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 650,
    discountPrice: 399,
    ratings: 4.9,
    numReviews: 130,
    isFeatured: true,
    tags: ['home', 'home & living', 'cookware sets', 'tri-ply', 'stainless steel'],
    images: [{ url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?q=80&w=800&auto=format&fit=crop' }],
    description: '3-layer construction (SS 304 inner + pure aluminum core + SS 430 outer) prevents food scorching and distributes heat 3X faster.',
  },
  {
    _id: 'prod-home-cook-3',
    name: 'Pre-Seasoned Heavy Cast Iron Dutch Oven Pot with Lid',
    slug: 'pre-seasoned-heavy-cast-iron-dutch-oven',
    brand: 'ZYRIVO CHEF',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 1000,
    discountPrice: 599,
    ratings: 4.9,
    numReviews: 92,
    isFeatured: false,
    tags: ['home', 'home & living', 'cookware sets', 'cast iron', 'dutch oven'],
    images: [{ url: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?q=80&w=800&auto=format&fit=crop' }],
    description: 'Naturally non-stick 100% pure cast iron oven enriched with 100% organic flaxseed oil seasoning, locks in flavors for stews, curries, and roasts.',
  },
  {
    _id: 'prod-home-cook-4',
    name: 'Hard Anodized Aluminum Pressure Cooker with Safety Valve (5 Liters)',
    slug: 'hard-anodized-aluminum-pressure-cooker-5-liters',
    brand: 'ZYRIVO CHEF',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 400,
    discountPrice: 249,
    ratings: 4.7,
    numReviews: 148,
    isFeatured: false,
    tags: ['home', 'home & living', 'cookware sets', 'pressure cooker', 'kitchen'],
    images: [{ url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800&auto=format&fit=crop' }],
    description: 'Black hard-anodized surface that never tarnishes or reacts with acidic ingredients, featuring stay-cool Bakelite heat-resistant handles.',
  },
  {
    _id: 'prod-home-cook-5',
    name: 'Silicone & Acacia Wood Non-Scratch Cooking Utensil Set (12 Pcs)',
    slug: 'silicone-acacia-wood-cooking-utensil-set-12-pcs',
    brand: 'ZYRIVO CHEF',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 1400,
    discountPrice: 799,
    ratings: 4.8,
    numReviews: 125,
    isFeatured: true,
    tags: ['home', 'home & living', 'cookware sets', 'utensil set', 'spatula'],
    images: [{ url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop' }],
    description: 'BPA-free heat-resistant silicone spoons and spatulas that safeguard non-stick pans from scuffs, complete with utensil holder.',
  },

  // 3.5 Dinnerware & Ceramic Crockery Sets (5 items)
  {
    _id: 'prod-home-din-1',
    name: 'Artisan Handcrafted Ceramic Stoneware Dinner Set (18 Pieces)',
    slug: 'artisan-handcrafted-ceramic-dinner-set-18-pcs',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 650,
    discountPrice: 349,
    ratings: 4.9,
    numReviews: 118,
    isFeatured: true,
    tags: ['home', 'home & living', 'dinnerware sets', 'dinner set', 'crockery', 'plates'],
    images: [{ url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?q=80&w=800&auto=format&fit=crop' }],
    description: 'Complete family dining set with full dinner plates, quarter snack plates, and soup bowls finished in a reactive speckled eggshell glaze.',
  },
  {
    _id: 'prod-home-din-2',
    name: '24K Real Gold Rimmed Royal Bone China Luxury Dinnerware Set',
    slug: '24k-gold-rimmed-royal-bone-china-dinnerware-set',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 1550,
    discountPrice: 999,
    ratings: 5.0,
    numReviews: 86,
    isFeatured: true,
    tags: ['home', 'home & living', 'dinnerware sets', 'bone china', 'luxury dining'],
    images: [{ url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=800&auto=format&fit=crop' }],
    description: 'Translucent high-strength bone china framed with genuine 24-karat gold filigree detailing, chip-resistant and lightweight.',
  },
  {
    _id: 'prod-home-din-3',
    name: 'Matte Black Minimalist Nordic Ceramic Pasta Bowls (Set of 6)',
    slug: 'matte-black-minimalist-ceramic-pasta-bowls',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 750,
    discountPrice: 449,
    ratings: 4.8,
    numReviews: 104,
    isFeatured: false,
    tags: ['home', 'home & living', 'dinnerware sets', 'pasta bowls', 'ceramic bowls'],
    images: [{ url: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?q=80&w=800&auto=format&fit=crop' }],
    description: 'Wide shallow lip design crafted for serving pasta, salads, curries, and grain bowls, microwave and dishwasher safe.',
  },
  {
    _id: 'prod-home-din-4',
    name: 'Vintage Blue Pottery Mughal Hand-Painted Coffee Mugs (Set of 6)',
    slug: 'vintage-blue-pottery-mughal-coffee-mugs',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 1200,
    discountPrice: 699,
    ratings: 4.8,
    numReviews: 130,
    isFeatured: true,
    tags: ['home', 'home & living', 'dinnerware sets', 'coffee mugs', 'mugs', 'blue pottery'],
    images: [{ url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop' }],
    description: '350ml glazed ceramic mugs hand-painted with cobalt blue traditional floral jaal motifs and comfortable ergonomic thumb rest handles.',
  },
  {
    _id: 'prod-home-din-5',
    name: 'Opalware Break-Resistant Everyday Lightweight Dinner Set (24 Pcs)',
    slug: 'opalware-break-resistant-everyday-dinner-set',
    brand: 'ZYRIVO HOME',
    categorySlug: 'home-living',
    categoryName: 'Home & Living',
    price: 500,
    discountPrice: 299,
    ratings: 4.7,
    numReviews: 155,
    isFeatured: false,
    tags: ['home', 'home & living', 'dinnerware sets', 'opalware', 'dinner set'],
    images: [{ url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800&auto=format&fit=crop' }],
    description: 'Tough thermal-shock resistant European opal glass tableware that does not absorb odors or food stains, perfect for daily family meals.',
  },

  // ═════════════════════════════════════════════════════════════
  // 4. BEAUTY & PERSONAL CARE (25 products: 5 Subcategories × 5 items)
  // ═════════════════════════════════════════════════════════════

  // 4.1 Face Wash & Cleansers (5 items)
  {
    _id: 'prod-beauty-cleanse-1',
    name: 'Salicylic Acid 2% + Tea Tree Gentle Foaming Cleanser for Acne',
    slug: 'salicylic-acid-tea-tree-foaming-cleanser',
    brand: 'ZYRIVO BOTANICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 850,
    discountPrice: 549,
    ratings: 4.9,
    numReviews: 240,
    isFeatured: true,
    tags: ['beauty', 'skincare', 'face wash & cleansers', 'face wash', 'cleanser', 'acne'],
    images: [{ url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop' }],
    description: 'Dermatologist-tested sulfate-free clarifying cleanser deep cleans pores, dissolves excess sebum, and soothes redness without stripping skin barrier.',
  },
  {
    _id: 'prod-beauty-cleanse-2',
    name: 'Hydrating Ceramide + Hyaluronic Acid Cream Cleanser for Dry Skin',
    slug: 'hydrating-ceramide-hyaluronic-acid-cream-cleanser',
    brand: 'ZYRIVO BOTANICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 1350,
    discountPrice: 849,
    ratings: 4.8,
    numReviews: 180,
    isFeatured: false,
    tags: ['beauty', 'skincare', 'face wash & cleansers', 'cleanser', 'ceramides'],
    images: [{ url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=800&auto=format&fit=crop' }],
    description: 'Non-foaming milky cleansing emulsion packed with 3 essential ceramides that retains natural moisture while melting makeup and pollution.',
  },
  {
    _id: 'prod-beauty-cleanse-3',
    name: 'Vitamin C Brightening Foaming Face Wash with Built-In Silicone Brush',
    slug: 'vitamin-c-brightening-foaming-face-wash-brush',
    brand: 'ZYRIVO BOTANICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 1800,
    discountPrice: 1099,
    ratings: 4.9,
    numReviews: 215,
    isFeatured: true,
    tags: ['beauty', 'skincare', 'face wash & cleansers', 'face wash', 'vitamin c', 'brightening'],
    images: [{ url: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop' }],
    description: 'Infused with Kakadu Plum Vitamin C and citrus extracts, the ergonomic micro-bristle brush micro-exfoliates dead skin cells for instant radiant glow.',
  },
  {
    _id: 'prod-beauty-cleanse-4',
    name: 'Centella Asiatica (Cica) Calming Low pH Gel Face Cleanser',
    slug: 'centella-asiatica-cica-calming-gel-cleanser',
    brand: 'ZYRIVO BOTANICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 1100,
    discountPrice: 649,
    ratings: 4.8,
    numReviews: 135,
    isFeatured: false,
    tags: ['beauty', 'skincare', 'face wash & cleansers', 'cleanser', 'cica', 'k-beauty'],
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop' }],
    description: 'Gentle pH 5.5 balancing gel formula enriched with pure Korean Centella Asiatica to restore stressed and irritated skin barriers.',
  },
  {
    _id: 'prod-beauty-cleanse-5',
    name: 'Activated Bamboo Charcoal Deep Pore Detox Face Wash',
    slug: 'activated-bamboo-charcoal-deep-pore-face-wash',
    brand: 'ZYRIVO BOTANICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 1300,
    discountPrice: 749,
    ratings: 4.7,
    numReviews: 158,
    isFeatured: true,
    tags: ['beauty', 'skincare', 'face wash & cleansers', 'face wash', 'charcoal'],
    images: [{ url: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=800&auto=format&fit=crop' }],
    description: 'Magnetic activated charcoal pulls out deep-seated micro-pollutants and blackheads, leaving skin refreshed and invigorated.',
  },

  // 4.2 Moisturizers & Serums (5 items)
  {
    _id: 'prod-beauty-serum-1',
    name: 'Pure Hyaluronic Acid 2% + B5 Intense Hydration Plumping Serum',
    slug: 'hyaluronic-acid-b5-intense-hydration-serum',
    brand: 'ZYRIVO BOTANICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 900,
    discountPrice: 499,
    ratings: 4.9,
    numReviews: 290,
    isFeatured: true,
    tags: ['beauty', 'skincare', 'moisturizers & serums', 'serums', 'hyaluronic acid', 'face serum'],
    images: [{ url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop' }],
    description: 'Multi-molecular weight hyaluronic acid penetrates multiple skin layers to deliver intense 72-hour moisture plumping and bounce.',
  },
  {
    _id: 'prod-beauty-serum-2',
    name: 'Niacinamide 10% + Zinc 1% Dark Spot Correcting Serum',
    slug: 'niacinamide-10-zinc-1-dark-spot-serum',
    brand: 'ZYRIVO BOTANICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 1400,
    discountPrice: 899,
    ratings: 4.9,
    numReviews: 310,
    isFeatured: true,
    tags: ['beauty', 'skincare', 'moisturizers & serums', 'serums', 'niacinamide', 'dark spots'],
    images: [{ url: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop' }],
    description: 'High-potency clinical formulation fades post-acne blemishes, tightens enlarged pores, and unifies uneven skin texture.',
  },
  {
    _id: 'prod-beauty-serum-3',
    name: 'Oil-Free Lightweight Hydro Gel Moisturizer with Aloe & Green Tea',
    slug: 'oil-free-hydro-gel-moisturizer-aloe-green-tea',
    brand: 'ZYRIVO BOTANICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 2000,
    discountPrice: 1199,
    ratings: 4.8,
    numReviews: 195,
    isFeatured: false,
    tags: ['beauty', 'skincare', 'moisturizers & serums', 'moisturizers', 'gel moisturizer'],
    images: [{ url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop' }],
    description: 'Zero-grease water-burst gel formulation absorbs in 3 seconds, delivering instant cooling hydration without clogging pores.',
  },
  {
    _id: 'prod-beauty-serum-4',
    name: 'Retinol 0.3% + Peptide Anti-Aging Night Renewal Cream',
    slug: 'retinol-peptide-anti-aging-night-cream',
    brand: 'ZYRIVO BOTANICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 600,
    discountPrice: 349,
    ratings: 4.9,
    numReviews: 172,
    isFeatured: true,
    tags: ['beauty', 'skincare', 'moisturizers & serums', 'retinol', 'night cream', 'anti aging'],
    images: [{ url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=800&auto=format&fit=crop' }],
    description: 'Encapsulated gentle retinol stimulates overnight cellular turnover to smooth fine lines and improve skin firmness.',
  },
  {
    _id: 'prod-beauty-serum-5',
    name: 'Rosehip Seed + Argan Luxury Organic Facial Glow Oil',
    slug: 'rosehip-seed-argan-luxury-facial-glow-oil',
    brand: 'ZYRIVO BOTANICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 1500,
    discountPrice: 949,
    ratings: 4.8,
    numReviews: 128,
    isFeatured: false,
    tags: ['beauty', 'skincare', 'moisturizers & serums', 'facial oil', 'glow oil'],
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop' }],
    description: 'Cold-pressed 100% pure botanical elixir loaded with essential fatty acids and antioxidants for a healthy, lit-from-within complexion.',
  },

  // 4.3 Broad Spectrum Sunscreens (5 items)
  {
    _id: 'prod-beauty-sun-1',
    name: 'SPF 50+ PA++++ Ultra-Light Dewy Sunscreen with Zero White Cast',
    slug: 'spf-50-pa-dewy-sunscreen-zero-white-cast',
    brand: 'ZYRIVO BOTANICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 450,
    discountPrice: 279,
    ratings: 5.0,
    numReviews: 320,
    isFeatured: true,
    tags: ['beauty', 'skincare', 'sunscreens', 'sunscreen', 'spf 50', 'sunblock'],
    images: [{ url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop' }],
    description: 'Next-generation hybrid chemical-mineral UV filters leave a non-sticky invisible satin finish, perfect under daily makeup.',
  },
  {
    _id: 'prod-beauty-sun-2',
    name: 'Matte Finish Silicone Gel SPF 50 Water-Resistant Sunscreen',
    slug: 'matte-finish-silicone-gel-spf-50-sunscreen',
    brand: 'ZYRIVO BOTANICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 750,
    discountPrice: 479,
    ratings: 4.9,
    numReviews: 240,
    isFeatured: false,
    tags: ['beauty', 'skincare', 'sunscreens', 'sunscreen', 'matte sunscreen'],
    images: [{ url: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop' }],
    description: 'Velvety pore-blurring primer finish with 80-minute sweat resistance, custom formulated for oily and combination Indian skin.',
  },
  {
    _id: 'prod-beauty-sun-3',
    name: '100% Mineral Zinc Oxide Tinted Sunscreen with Broad Spectrum Defense',
    slug: '100-mineral-zinc-oxide-tinted-sunscreen',
    brand: 'ZYRIVO BOTANICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 1100,
    discountPrice: 679,
    ratings: 4.8,
    numReviews: 165,
    isFeatured: true,
    tags: ['beauty', 'skincare', 'sunscreens', 'sunscreen', 'mineral sunscreen', 'tinted'],
    images: [{ url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=800&auto=format&fit=crop' }],
    description: 'Universal tint prevents ashiness while non-nano zinc oxide provides reef-safe, irritation-free defense for sensitive skin.',
  },
  {
    _id: 'prod-beauty-sun-4',
    name: 'Vitamin C Glow Sunscreen Serum SPF 50 with Niacinamide',
    slug: 'vitamin-c-glow-sunscreen-serum-spf-50',
    brand: 'ZYRIVO BOTANICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 1500,
    discountPrice: 879,
    ratings: 4.9,
    numReviews: 190,
    isFeatured: false,
    tags: ['beauty', 'skincare', 'sunscreens', 'sunscreen', 'glow sunscreen'],
    images: [{ url: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=800&auto=format&fit=crop' }],
    description: 'Dual protection combines potent antioxidants with broad-spectrum photostable UV shields to combat tanning and sun spots.',
  },
  {
    _id: 'prod-beauty-sun-5',
    name: 'On-The-Go Sunscreen Stick SPF 50+ Easy Reapplication Bar',
    slug: 'on-the-go-sunscreen-stick-spf-50-reapplication',
    brand: 'ZYRIVO BOTANICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 1850,
    discountPrice: 1049,
    ratings: 4.8,
    numReviews: 175,
    isFeatured: true,
    tags: ['beauty', 'skincare', 'sunscreens', 'sunscreen', 'sun stick'],
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop' }],
    description: 'Mess-free pocket twist stick glides easily over makeup without smudging, offering seamless two-finger UV touchups everywhere.',
  },

  // 4.4 Matte Lipsticks & Lip Gloss (5 items)
  {
    _id: 'prod-beauty-lip-1',
    name: 'Velvet Matte Long-Wear Transfer-Proof Liquid Lipstick (Royal Crimson)',
    slug: 'velvet-matte-transfer-proof-liquid-lipstick-royal-crimson',
    brand: 'ZYRIVO COSMETICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 600,
    discountPrice: 329,
    ratings: 4.9,
    numReviews: 280,
    isFeatured: true,
    tags: ['beauty', 'makeup', 'lipsticks & lip gloss', 'lipstick', 'matte lipstick', 'liquid lipstick'],
    images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800&auto=format&fit=crop' }],
    description: 'Intensely pigmented 16-hour stay formula with infused vitamin E and avocado oil that prevents lip drying and flaking.',
  },
  {
    _id: 'prod-beauty-lip-2',
    name: 'Nude Brown Satin Hydrating Bullet Lipstick with Shea Butter',
    slug: 'nude-brown-satin-hydrating-bullet-lipstick',
    brand: 'ZYRIVO COSMETICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 800,
    discountPrice: 529,
    ratings: 4.8,
    numReviews: 215,
    isFeatured: false,
    tags: ['beauty', 'makeup', 'lipsticks & lip gloss', 'lipstick', 'nude lipstick'],
    images: [{ url: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=800&auto=format&fit=crop' }],
    description: 'Everyday flattering nude for Indian skin tones, enriched with rich shea butter for a cushiony satin pillow glide.',
  },
  {
    _id: 'prod-beauty-lip-3',
    name: 'Glass-Shine Hydrating Non-Sticky Lip Gloss with Hyaluronic Acid',
    slug: 'glass-shine-hydrating-lip-gloss-hyaluronic-acid',
    brand: 'ZYRIVO COSMETICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 1200,
    discountPrice: 729,
    ratings: 4.9,
    numReviews: 198,
    isFeatured: true,
    tags: ['beauty', 'makeup', 'lipsticks & lip gloss', 'lip gloss', 'gloss'],
    images: [{ url: 'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?q=80&w=800&auto=format&fit=crop' }],
    description: 'Ultra-glossy mirrored finish with fine multidimensional micro-pearls and plumping hyaluronic filling spheres.',
  },
  {
    _id: 'prod-beauty-lip-4',
    name: 'Berry Plum Matte Lip Crayon with Built-In Precision Sharpener',
    slug: 'berry-plum-matte-lip-crayon-built-in-sharpener',
    brand: 'ZYRIVO COSMETICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 1650,
    discountPrice: 979,
    ratings: 4.7,
    numReviews: 135,
    isFeatured: false,
    tags: ['beauty', 'makeup', 'lipsticks & lip gloss', 'lip crayon', 'lipstick'],
    images: [{ url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=800&auto=format&fit=crop' }],
    description: 'Chubby precision crayon outlines and fills in a single swipe with lightweight suede finish and smudge-proof hold.',
  },
  {
    _id: 'prod-beauty-lip-5',
    name: 'pH Tinted Nourishing Magic Lip Oil (Blush Pink Tint)',
    slug: 'ph-tinted-nourishing-magic-lip-oil-blush-pink',
    brand: 'ZYRIVO COSMETICS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 1850,
    discountPrice: 1149,
    ratings: 4.9,
    numReviews: 245,
    isFeatured: true,
    tags: ['beauty', 'makeup', 'lipsticks & lip gloss', 'lip oil', 'lip tint'],
    images: [{ url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?q=80&w=800&auto=format&fit=crop' }],
    description: 'Reacts to personal lip pH to deliver a bespoke natural rose-pink flush, packed with jojoba and cherry seed oil.',
  },

  // 4.5 Luxury Perfumes & Eau de Parfum (5 items)
  {
    _id: 'prod-beauty-perf-1',
    name: 'Oud & Amber Royal Extrait de Parfum (100 ml Luxury Spray)',
    slug: 'oud-amber-royal-extrait-de-parfum-100ml',
    brand: 'ZYRIVO PARFUMS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 350,
    discountPrice: 219,
    ratings: 5.0,
    numReviews: 310,
    isFeatured: true,
    tags: ['beauty', 'fragrances', 'eau de parfum', 'perfume', 'oud perfume', 'fragrance'],
    images: [{ url: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=800&auto=format&fit=crop' }],
    description: 'Regal oriental woody symphony blending smoky Cambodian agarwood, velvety amber, and Damascus rose with 24-hour longevity.',
  },
  {
    _id: 'prod-beauty-perf-2',
    name: 'French Vanilla & Jasmine Eau de Parfum for Women (100 ml)',
    slug: 'french-vanilla-jasmine-eau-de-parfum-women',
    brand: 'ZYRIVO PARFUMS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 650,
    discountPrice: 419,
    ratings: 4.9,
    numReviews: 260,
    isFeatured: true,
    tags: ['beauty', 'fragrances', 'eau de parfum', 'perfume', 'women perfume', 'vanilla'],
    images: [{ url: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?q=80&w=800&auto=format&fit=crop' }],
    description: 'Sensual gourmand fragrance opening with sweet Madagascar vanilla bean and blooming white night-jasmine.',
  },
  {
    _id: 'prod-beauty-perf-3',
    name: 'Aqua Marine & Italian Bergamot Citrus Eau de Parfum (100 ml)',
    slug: 'aqua-marine-italian-bergamot-citrus-parfum',
    brand: 'ZYRIVO PARFUMS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 1000,
    discountPrice: 619,
    ratings: 4.8,
    numReviews: 185,
    isFeatured: false,
    tags: ['beauty', 'fragrances', 'eau de parfum', 'perfume', 'men perfume', 'citrus'],
    images: [{ url: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?q=80&w=800&auto=format&fit=crop' }],
    description: 'Crisp invigorating oceanic breeze with zesty Calabrian bergamot, sea salt accords, and a dry-down of cedarwood.',
  },
  {
    _id: 'prod-beauty-perf-4',
    name: 'Smoked Tobacco & Tonka Bean Dark Unisex Eau de Parfum',
    slug: 'smoked-tobacco-tonka-bean-unisex-parfum',
    brand: 'ZYRIVO PARFUMS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 1400,
    discountPrice: 819,
    ratings: 4.9,
    numReviews: 195,
    isFeatured: true,
    tags: ['beauty', 'fragrances', 'eau de parfum', 'perfume', 'tobacco perfume', 'unisex perfume'],
    images: [{ url: 'https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=800&auto=format&fit=crop' }],
    description: 'Mysterious evening scent with sweet blonde tobacco leaf, roasted tonka bean, and spicy cardamom wrapped in cacao.',
  },
  {
    _id: 'prod-beauty-perf-5',
    name: 'Blooming Peony & Blush Suede Floral Eau de Toilette (100 ml)',
    slug: 'blooming-peony-blush-suede-floral-toilette',
    brand: 'ZYRIVO PARFUMS',
    categorySlug: 'beauty-personal-care',
    categoryName: 'Beauty & Personal Care',
    price: 1800,
    discountPrice: 1019,
    ratings: 4.7,
    numReviews: 140,
    isFeatured: false,
    tags: ['beauty', 'fragrances', 'eau de parfum', 'perfume', 'floral perfume'],
    images: [{ url: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=800&auto=format&fit=crop' }],
    description: 'Airy romantic springtime bouquet with blooming pink peonies, crisp red apple, and tender blush suede texture.',
  },
];


