const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Category = require('../models/Category');
const Product = require('../models/Product');
const menProductsData = require('./menProductsData');
const footwearBagsData = require('./footwearBagsData');
const newCategoriesData = require('./newCategoriesData');
const expandedCatalogData = require('./expandedCatalogData');

dotenv.config();

const seedAll = async () => {
  try {
    const mongoUri = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/ZYRIVO';
    await mongoose.connect(mongoUri);
    console.log('Connected to MongoDB for Complete Catalog seeding...');

    // 1. Define Categories
    const categoriesData = [
      {
        name: 'Women Ethnic Wear',
        slug: 'women-ethnic-wear',
        description: 'Kurtas, Kurtis, Sarees, Lehengas, and festive ethnic wear for women.',
        image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop',
      },
      {
        name: 'Women Western Wear',
        slug: 'women-western-wear',
        description: 'Dresses, Jumpsuits, Tops, Jeans, Trousers, and Blazers for women.',
        image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop',
      },
      {
        name: 'Women Footwear & Bags',
        slug: 'women-footwear-bags',
        description: 'Heels, flats, juttis, handbags, clutches, and tote bags.',
        image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800&auto=format&fit=crop',
      },
      {
        name: 'Women Lingerie & Sleepwear',
        slug: 'women-lingerie-sleepwear',
        description: 'Bras, panties, satin nightsuits, loungewear, and shapewear.',
        image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
      },
      {
        name: 'Men Top Wear',
        slug: 'men-top-wear',
        description: 'T-Shirts, Polos, Casual Shirts, and Formal Shirts for men.',
        image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=800&auto=format&fit=crop',
      },
      {
        name: 'Men Bottom Wear',
        slug: 'men-bottom-wear',
        description: 'Jeans, chinos, trousers, and joggers for men.',
        image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=800&auto=format&fit=crop',
      },
      {
        name: 'Footwear & Sneakers',
        slug: 'footwear-sneakers',
        description: 'Handcrafted leather loafers, dress shoes, and luxury sneakers.',
        image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=800&auto=format&fit=crop',
      },
      {
        name: 'Watches & Timepieces',
        slug: 'watches-timepieces',
        description: 'Automatic chronographs and heritage Swiss wristwatches.',
        image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop',
      },
      {
        name: 'Bags & Leather',
        slug: 'bags-leather',
        description: 'Tote bags, crossbody leather satchels, and premium weekender duffels.',
        image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop',
      },
      {
        name: 'Accessories & Jewelry',
        slug: 'accessories-jewelry',
        description: 'Bracelets, polarized eyewear, and minimal pendants.',
        image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800&auto=format&fit=crop',
      },
      {
        name: 'Kids Wear',
        slug: 'kids-wear',
        description: 'Trendy clothing, frocks, t-shirts, and footwear for boys and girls.',
        image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=800&auto=format&fit=crop',
      },
      {
        name: 'Home & Living',
        slug: 'home-living',
        description: 'Cotton bedsheets, curtains, cookware sets, and home decor.',
        image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=800&auto=format&fit=crop',
      },
      {
        name: 'Beauty & Personal Care',
        slug: 'beauty-personal-care',
        description: 'Dermatologically tested skincare, luxury fragrances, and makeup.',
        image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop',
      },
    ];

    const categoryMap = {};
    for (const catData of categoriesData) {
      let cat = await Category.findOne({ slug: catData.slug });
      if (!cat) {
        cat = await Category.create(catData);
      }
      categoryMap[catData.slug] = cat._id;
    }
    console.log('Categories initialized.');

    // 2. Comprehensive Products List (100 Women Ethnic & Western Products + Accessories/Men)
    const allProducts = [
      // ═════════════════════════════════════════════════════════════
      // 1. WOMEN ETHNIC: 10 Subcategories × 5 Distinct Products = 50
      // ═════════════════════════════════════════════════════════════

      // 1.1 Kurtas & Kurtis (5 items)
      {
        name: 'ZYRIVO Gold Foil Printed Straight Chanderi Kurta',
        slug: 'ZYRIVO-gold-foil-printed-straight-chanderi-kurta',
        description: 'Lustrous festive Chanderi straight kurta with metallic gold foil block print, Mandarin collar, and three-quarter sleeves.',
        price: 1550,
        discountPrice: 999,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Ethnic',
        stock: 50,
        isFeatured: true,
        tags: ['women', 'ethnic', 'kurtas & kurtis', 'kurta', 'kurti', 'festive'],
        images: [{ url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 48,
      },
      {
        name: 'Floral Embroidered Flared Rayon A-Line Kurti',
        slug: 'floral-embroidered-flared-rayon-a-line-kurti',
        description: 'Flowy premium rayon A-line kurti with delicate Kashmiri multi-colored floral embroidery around the round neckline.',
        price: 750,
        discountPrice: 449,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Ethnic',
        stock: 40,
        isFeatured: false,
        tags: ['women', 'ethnic', 'kurtas & kurtis', 'kurti', 'kurta', 'a-line'],
        images: [{ url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 35,
      },
      {
        name: 'Hand-Block Printed Kalamkari A-Line Tunic Kurta',
        slug: 'hand-block-printed-kalamkari-a-line-tunic-kurta',
        description: 'Traditional vegetable dye hand-block Kalamkari printed kurta crafted from breathable combed cotton with front wooden buttons.',
        price: 1200,
        discountPrice: 699,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Riwaaz',
        stock: 35,
        isFeatured: true,
        tags: ['women', 'ethnic', 'kurtas & kurtis', 'kurta', 'kurti', 'kalamkari'],
        images: [{ url: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 62,
      },
      {
        name: 'Classic Mandarin Collar Embroidered Silk Blend Kurti',
        slug: 'classic-mandarin-collar-embroidered-silk-blend-kurti',
        description: 'Royal crimson red silk-blend festive kurti featuring antique zari needlework across the yoke and sleeve cuffs.',
        price: 500,
        discountPrice: 299,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Heritage',
        stock: 30,
        isFeatured: false,
        tags: ['women', 'ethnic', 'kurtas & kurtis', 'kurta', 'kurti', 'silk kurti'],
        images: [{ url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 41,
      },
      {
        name: 'Bandhani Print Cotton Slub Festive Long Kurta',
        slug: 'bandhani-print-cotton-slub-festive-long-kurta',
        description: 'Vibrant Gujarati Bandhani printed straight kurti accented with gota lace borders and handmade potli buttons.',
        price: 850,
        discountPrice: 549,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Daily',
        stock: 55,
        isFeatured: true,
        tags: ['women', 'ethnic', 'kurtas & kurtis', 'kurta', 'kurti', 'bandhani'],
        images: [{ url: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 29,
      },

      // 1.2 Anarkali Kurta Sets (5 items)
      {
        name: 'Embroidered Anarkali Kurta Set with Chiffon Dupatta',
        slug: 'embroidered-anarkali-kurta-set-chiffon-dupatta',
        description: 'Flowy Georgette Anarkali Kurta featuring intricate thread embroidery, matching churidar pants and a lightweight border dupatta.',
        price: 1350,
        discountPrice: 849,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Ethnic',
        stock: 35,
        isFeatured: true,
        tags: ['women', 'ethnic', 'anarkali kurta sets', 'anarkali', 'kurta set', 'festive'],
        images: [{ url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 52,
      },
      {
        name: 'Royal Georgette Mirror Work Flared Anarkali Suit',
        slug: 'royal-georgette-mirror-work-flared-anarkali-suit',
        description: 'Grand 32-kali flared floor-length anarkali suit decorated with authentic Abhla mirror-work and heavy zari borders.',
        price: 1800,
        discountPrice: 1099,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Couture',
        stock: 25,
        isFeatured: true,
        tags: ['women', 'ethnic', 'anarkali kurta sets', 'anarkali', 'mirror work', 'wedding'],
        images: [{ url: 'https://images.unsplash.com/photo-1621600411688-4be93cd68504?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 44,
      },
      {
        name: 'Angrakha Style Gota Patti Chanderi Anarkali Set',
        slug: 'angrakha-style-gota-patti-chanderi-anarkali-set',
        description: 'Overlapping Angrakha neckline with traditional Rajasthani gota patti tassels, paired with printed cigarette pants and organza dupatta.',
        price: 1100,
        discountPrice: 649,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Riwaaz',
        stock: 28,
        isFeatured: false,
        tags: ['women', 'ethnic', 'anarkali kurta sets', 'anarkali', 'angrakha'],
        images: [{ url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 38,
      },
      {
        name: 'Floral Printed Organza Flared Anarkali with Pants',
        slug: 'floral-printed-organza-flared-anarkali-pants',
        description: 'Pastel blooming floral prints on sheer organza fabric with soft cotton lining, sweetheart neck, and silk straight pants.',
        price: 1300,
        discountPrice: 749,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Ethnic',
        stock: 30,
        isFeatured: true,
        tags: ['women', 'ethnic', 'anarkali kurta sets', 'anarkali', 'organza'],
        images: [{ url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 49,
      },
      {
        name: 'Zari Thread Embroidered Floor-Length Silk Anarkali',
        slug: 'zari-thread-embroidered-floor-length-silk-anarkali',
        description: 'Bespoke royal festive ensemble with resham threadwork, golden dori waist tie, and voluminous can-can flared hemline.',
        price: 900,
        discountPrice: 499,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Couture',
        stock: 20,
        isFeatured: false,
        tags: ['women', 'ethnic', 'anarkali kurta sets', 'anarkali', 'silk gown'],
        images: [{ url: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 56,
      },

      // 1.3 Chikankari Kurtis (5 items)
      {
        name: 'Handcrafted Lucknowi Chikankari Georgette Kurti with Slip',
        slug: 'handcrafted-lucknowi-chikankari-georgette-kurti-slip',
        description: 'Authentic handcrafted Chikankari needlework with Bakhiya and Phanda stitches on sheer georgette with tonal inner slip.',
        price: 1400,
        discountPrice: 899,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Ethnic',
        stock: 45,
        isFeatured: true,
        tags: ['women', 'ethnic', 'chikankari kurtis', 'chikankari', 'kurti', 'lucknowi'],
        images: [{ url: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 64,
      },
      {
        name: 'Pastel Modal Cotton Mukaish Work Chikankari Kurti',
        slug: 'pastel-modal-cotton-mukaish-work-chikankari-kurti',
        description: 'Ultra-soft modal cotton fabric infused with subtle silver mukaish badla dots and detailed artisan floral neck embroidery.',
        price: 2000,
        discountPrice: 1199,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Ethnic',
        stock: 40,
        isFeatured: true,
        tags: ['women', 'ethnic', 'chikankari kurtis', 'chikankari', 'kurti', 'modal'],
        images: [{ url: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 51,
      },
      {
        name: 'Ivory Pure Mulmul Shadow Needlework Chikankari Kurti',
        slug: 'ivory-pure-mulmul-shadow-needlework-chikankari-kurti',
        description: 'Heritage ivory mulmul cotton kurti with Tepchi and shadow needlework, side slits, and comfortable straight silhouette.',
        price: 600,
        discountPrice: 349,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Riwaaz',
        stock: 35,
        isFeatured: false,
        tags: ['women', 'ethnic', 'chikankari kurtis', 'chikankari', 'mulmul'],
        images: [{ url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 37,
      },
      {
        name: 'Lavender Hand-Embroidered Short Chikankari Tunic Kurti',
        slug: 'lavender-hand-embroidered-short-chikankari-tunic-kurti',
        description: 'Contemporary hip-length short chikankari kurti in soothing lavender, tailor-made for pairing with denim jeans or palazzos.',
        price: 1500,
        discountPrice: 949,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Studio',
        stock: 50,
        isFeatured: true,
        tags: ['women', 'ethnic', 'chikankari kurtis', 'chikankari', 'short kurti'],
        images: [{ url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 42,
      },
      {
        name: 'Peach Silk Blend Heavy Floral Embroidered Chikankari Kurti',
        slug: 'peach-silk-blend-heavy-floral-chikankari-kurti',
        description: 'Festive pure silk-georgette blend featuring all-over dense floral jaal chikankari motifs and scalloped hand-cut borders.',
        price: 450,
        discountPrice: 279,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Couture',
        stock: 25,
        isFeatured: false,
        tags: ['women', 'ethnic', 'chikankari kurtis', 'chikankari', 'silk blend'],
        images: [{ url: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 58,
      },

      // 1.4 Cotton Daily Kurtas (5 items)
      {
        name: 'Pure Cotton Floral Print Straight Kurta with Palazzos',
        slug: 'pure-cotton-floral-print-straight-kurta-palazzos',
        description: 'Everyday comfortable 100% breathable cotton straight-fit kurta paired with flared palazzo pants featuring pocket details.',
        price: 750,
        discountPrice: 479,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Daily',
        stock: 60,
        isFeatured: true,
        tags: ['women', 'ethnic', 'cotton daily kurtas', 'cotton', 'kurta', 'daily wear'],
        images: [{ url: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 87,
      },
      {
        name: 'Jaipur Hand-Block Print Breathable Daily Cotton Kurta',
        slug: 'jaipur-hand-block-print-breathable-daily-cotton-kurta',
        description: 'Artisanal Sanganeri block-printed cotton kurta in natural indigo and rust hues, finished with wooden button placket.',
        price: 1100,
        discountPrice: 679,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Daily',
        stock: 55,
        isFeatured: true,
        tags: ['women', 'ethnic', 'cotton daily kurtas', 'cotton', 'daily wear', 'jaipuri'],
        images: [{ url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 73,
      },
      {
        name: 'Striped Indigo Kalamkari Cotton Casual Office Wear Kurta',
        slug: 'striped-indigo-kalamkari-cotton-office-kurta',
        description: 'Smart vertical stripes combined with Kalamkari border yoke. Crisp pure cotton keeps you cool throughout working hours.',
        price: 1500,
        discountPrice: 879,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Daily',
        stock: 45,
        isFeatured: false,
        tags: ['women', 'ethnic', 'cotton daily kurtas', 'cotton', 'office wear', 'kurta'],
        images: [{ url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.6,
        numReviews: 40,
      },
      {
        name: 'Pastel Mint Green Round-Neck Daily Wear Cotton Kurti',
        slug: 'pastel-mint-green-daily-wear-cotton-kurti',
        description: 'Lightweight slub cotton tunic kurti with three-quarter folded sleeves, minimal side pockets, and relaxed breezy fit.',
        price: 1850,
        discountPrice: 1049,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Daily',
        stock: 50,
        isFeatured: false,
        tags: ['women', 'ethnic', 'cotton daily kurtas', 'cotton', 'daily wear', 'kurti'],
        images: [{ url: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 33,
      },
      {
        name: 'Minimalist Khadi Cotton Button-Down Everyday Straight Kurta',
        slug: 'minimalist-khadi-cotton-button-down-straight-kurta',
        description: 'Eco-friendly textured khadi cotton straight kurta featuring round split neck, side slits, and durable double-stitch seams.',
        price: 600,
        discountPrice: 329,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Daily',
        stock: 40,
        isFeatured: true,
        tags: ['women', 'ethnic', 'cotton daily kurtas', 'cotton', 'khadi', 'daily wear'],
        images: [{ url: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 61,
      },

      // 1.5 Ethnic Co-ord Sets (5 items)
      {
        name: 'Woven Jacquard Tunic and Tapered Trouser Ethnic Co-ord Set',
        slug: 'woven-jacquard-tunic-trouser-ethnic-co-ord-set',
        description: 'Sophisticated 2-piece ethnic co-ord set featuring a woven metallic jacquard collared tunic paired with ankle-length matching trousers.',
        price: 800,
        discountPrice: 529,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Riwaaz',
        stock: 30,
        isFeatured: true,
        tags: ['women', 'ethnic', 'ethnic co-ord sets', 'co-ord', 'coord set', 'suit set'],
        images: [{ url: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 47,
      },
      {
        name: 'Bandhani Print Peplum Top with Flared Dhoti Pant Set',
        slug: 'bandhani-print-peplum-top-flared-dhoti-set',
        description: 'Contemporary ethnic silhouette comprising a flared Bandhani printed peplum top with mirror work belt and comfortable pleated dhoti pants.',
        price: 1200,
        discountPrice: 729,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Riwaaz',
        stock: 35,
        isFeatured: true,
        tags: ['women', 'ethnic', 'ethnic co-ord sets', 'co-ord', 'dhoti set', 'festive'],
        images: [{ url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 39,
      },
      {
        name: 'Embroidered Silk Asymmetric High-Low Ethnic Co-ord Set',
        slug: 'embroidered-silk-asymmetric-high-low-co-ord-set',
        description: 'Modern high-low tunic shirt adorned with sequin lapel embroidery, paired with high-waisted relaxed flared ethnic palazzos.',
        price: 1650,
        discountPrice: 979,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Couture',
        stock: 25,
        isFeatured: false,
        tags: ['women', 'ethnic', 'ethnic co-ord sets', 'co-ord', 'silk co-ord'],
        images: [{ url: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 53,
      },
      {
        name: 'Festive Mirror-Work Long Jacket with Crop Top & Palazzo Set',
        slug: 'festive-mirror-work-jacket-crop-top-palazzo-set',
        description: 'Showstopping 3-piece festive fusion set with an embroidered bustier crop top, wide-leg georgette palazzos, and full-length sheer cape jacket.',
        price: 1850,
        discountPrice: 1149,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Couture',
        stock: 22,
        isFeatured: true,
        tags: ['women', 'ethnic', 'ethnic co-ord sets', 'co-ord', 'jacket set', 'fusion'],
        images: [{ url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 68,
      },
      {
        name: 'Chevron Printed Chanderi Tunic with Wide-Leg Pants Set',
        slug: 'chevron-printed-chanderi-tunic-pants-set',
        description: 'Pastel festive Chanderi tunic with metallic chevron print, side tie-up dori, and matching comfortable elasticated wide trousers.',
        price: 350,
        discountPrice: 219,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Ethnic',
        stock: 32,
        isFeatured: false,
        tags: ['women', 'ethnic', 'ethnic co-ord sets', 'co-ord', 'chanderi set'],
        images: [{ url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 31,
      },

      // 1.6 Sarees (General & Handloom, 5 items)
      {
        name: 'Handloom Linen Cotton Saree with Silver Zari Pallu',
        slug: 'handloom-linen-cotton-saree-silver-zari-pallu',
        description: 'Eco-spun organic handloom linen saree enriched with metallic silver zari stripes on the pallu and contrasting running blouse fabric.',
        price: 650,
        discountPrice: 419,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Heritage',
        stock: 30,
        isFeatured: true,
        tags: ['women', 'ethnic', 'sarees', 'saree', 'linen saree', 'handloom'],
        images: [{ url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 55,
      },
      {
        name: 'Contrast Border Heritage Kanjivaram Soft Silk Saree',
        slug: 'contrast-border-heritage-kanjivaram-soft-silk-saree',
        description: 'South Indian heirloom aesthetic featuring exquisite temple zari borders, rich contrast pallu, and heavy jacquard weave.',
        price: 1000,
        discountPrice: 619,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Heritage',
        stock: 20,
        isFeatured: true,
        tags: ['women', 'ethnic', 'sarees', 'saree', 'silk saree', 'kanjivaram'],
        images: [{ url: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 61,
      },
      {
        name: 'Pastel Organza Floral Embroidered Scalloped Border Saree',
        slug: 'pastel-organza-floral-scalloped-saree',
        description: 'Semi-sheer lustrous organza silk saree finished with intricate floral threadwork and delicate scalloped embroidered borders.',
        price: 1400,
        discountPrice: 819,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Couture',
        stock: 22,
        isFeatured: true,
        tags: ['women', 'ethnic', 'sarees', 'saree', 'organza saree', 'scalloped'],
        images: [{ url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 45,
      },
      {
        name: 'Dual-Tone Shimmering Tissue Silk Festive Saree',
        slug: 'dual-tone-shimmering-tissue-silk-festive-saree',
        description: 'Mesmerizing champagne gold tissue saree with metallic woven finish, lightweight drape, and golden zari tasselled pallu.',
        price: 1800,
        discountPrice: 1019,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Couture',
        stock: 25,
        isFeatured: false,
        tags: ['women', 'ethnic', 'sarees', 'saree', 'tissue saree', 'festive'],
        images: [{ url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 32,
      },
      {
        name: 'Handwoven Tussar Silk Saree with Traditional Zari Motifs',
        slug: 'handwoven-tussar-silk-saree-zari-motifs',
        description: 'Authentic wild Tussar silk saree adorned with handwoven temple borders, earthy natural raw silk texture, and rich zari pallu.',
        price: 650,
        discountPrice: 369,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Heritage',
        stock: 18,
        isFeatured: true,
        tags: ['women', 'ethnic', 'sarees', 'saree', 'tussar silk', 'silk saree'],
        images: [{ url: 'https://images.unsplash.com/photo-1621600411688-4be93cd68504?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 48,
      },

      // 1.7 Banarasi Silk Sarees (5 items)
      {
        name: 'Regal Crimson Red Banarasi Katan Silk Zari Woven Saree',
        slug: 'regal-crimson-red-banarasi-katan-silk-zari-saree',
        description: 'Traditional Banarasi weave with regal floral kadwa motifs, broad golden zari border, and matching unstitched designer blouse piece.',
        price: 900,
        discountPrice: 569,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Heritage',
        stock: 25,
        isFeatured: true,
        tags: ['women', 'ethnic', 'banarasi silk sarees', 'banarasi', 'saree', 'silk saree', 'wedding'],
        images: [{ url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 76,
      },
      {
        name: 'Emerald Green Floral Kadwa Zari Weave Banarasi Saree',
        slug: 'emerald-green-kadwa-zari-banarasi-saree',
        description: 'Pure Katan silk in jewel emerald green, handloom kadwa floral jaal with real golden zari threads and grand floral pallu.',
        price: 1250,
        discountPrice: 769,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Heritage',
        stock: 20,
        isFeatured: true,
        tags: ['women', 'ethnic', 'banarasi silk sarees', 'banarasi', 'saree', 'kadwa'],
        images: [{ url: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?q=80&w=800&auto=format&fit=crop' }],
        ratings: 5.0,
        numReviews: 83,
      },
      {
        name: 'Midnight Navy Blue Antique Zari Bridal Banarasi Saree',
        slug: 'midnight-navy-blue-antique-zari-banarasi-saree',
        description: 'Deep royal navy blue katan silk saree woven with antique oxidized gold zari paisley butas and rich brocade pallu.',
        price: 1850,
        discountPrice: 1099,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Heritage',
        stock: 18,
        isFeatured: false,
        tags: ['women', 'ethnic', 'banarasi silk sarees', 'banarasi', 'saree', 'bridal'],
        images: [{ url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 59,
      },
      {
        name: 'Mustard Yellow Pure Katan Silk Meenakari Banarasi Saree',
        slug: 'mustard-yellow-meenakari-banarasi-saree',
        description: 'Festive turmeric yellow banarasi saree accented with colorful Meenakari floral detailing within golden zari butis.',
        price: 2000,
        discountPrice: 1249,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Heritage',
        stock: 22,
        isFeatured: true,
        tags: ['women', 'ethnic', 'banarasi silk sarees', 'banarasi', 'saree', 'meenakari'],
        images: [{ url: 'https://images.unsplash.com/photo-1621600411688-4be93cd68504?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 44,
      },
      {
        name: 'Blush Pink Floral Jaal Silver Zari Banarasi Silk Saree',
        slug: 'blush-pink-floral-jaal-silver-zari-banarasi-saree',
        description: 'Romantic pastel blush pink banarasi silk saree woven with radiant silver zari jaal work, ideal for daytime weddings.',
        price: 350,
        discountPrice: 239,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Heritage',
        stock: 24,
        isFeatured: false,
        tags: ['women', 'ethnic', 'banarasi silk sarees', 'banarasi', 'saree', 'silver zari'],
        images: [{ url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 67,
      },

      // 1.8 Georgette Printed Sarees (5 items)
      {
        name: 'Botanical Floral Digital Print Pure Georgette Saree',
        slug: 'botanical-floral-print-pure-georgette-saree',
        description: 'Feather-light flowing pure georgette saree printed with blooming pastel botanical flora and subtle lace border detail.',
        price: 700,
        discountPrice: 439,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Ethnic',
        stock: 35,
        isFeatured: true,
        tags: ['women', 'ethnic', 'georgette printed sarees', 'georgette', 'saree', 'floral saree'],
        images: [{ url: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 39,
      },
      {
        name: 'Ombre Sunset Dual-Tone Lightweight Georgette Party Saree',
        slug: 'ombre-sunset-dual-tone-georgette-party-saree',
        description: 'Stunning seamless gradient transition from coral peach to fiery dusk magenta, finished with micro-sequin border lace.',
        price: 1050,
        discountPrice: 639,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Ethnic',
        stock: 30,
        isFeatured: true,
        tags: ['women', 'ethnic', 'georgette printed sarees', 'georgette', 'saree', 'ombre'],
        images: [{ url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 52,
      },
      {
        name: 'Polka Dot Retro Bollywood Chiffon-Georgette Saree',
        slug: 'polka-dot-retro-bollywood-georgette-saree',
        description: 'Vintage 90s inspired black and white polka dot saree crafted from airy georgette-chiffon blend with solid contrast piping.',
        price: 1450,
        discountPrice: 839,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Studio',
        stock: 40,
        isFeatured: false,
        tags: ['women', 'ethnic', 'georgette printed sarees', 'georgette', 'saree', 'polka dot'],
        images: [{ url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.6,
        numReviews: 28,
      },
      {
        name: 'Abstract Geometric Multicolored Printed Georgette Saree',
        slug: 'abstract-geometric-printed-georgette-saree',
        description: 'Contemporary artwork on silk-georgette canvas featuring bold modern brush strokes and lightweight wrinkle-resistant drape.',
        price: 1800,
        discountPrice: 1039,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Studio',
        stock: 38,
        isFeatured: true,
        tags: ['women', 'ethnic', 'georgette printed sarees', 'georgette', 'saree', 'printed'],
        images: [{ url: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 36,
      },
      {
        name: 'Water-Color Floral Pastel Breeze Georgette Saree',
        slug: 'watercolor-floral-pastel-georgette-saree',
        description: 'Delicate watercolor blossom painting across powder blue georgette with golden cord-piped hem and unstiched blouse.',
        price: 550,
        discountPrice: 299,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Ethnic',
        stock: 33,
        isFeatured: false,
        tags: ['women', 'ethnic', 'georgette printed sarees', 'georgette', 'saree', 'pastel'],
        images: [{ url: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 43,
      },

      // 1.9 Lehengas & Cholis (5 items)
      {
        name: 'Velvet Heavy Embroidered Royal Bridal Lehenga Choli',
        slug: 'velvet-heavy-embroidered-royal-bridal-lehenga-choli',
        description: 'Regal maroon velvet lehenga choli set densely embroidered with zardozi, kora, and sequin work. Includes dual sheer net dupattas.',
        price: 750,
        discountPrice: 499,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Couture',
        stock: 15,
        isFeatured: true,
        tags: ['women', 'ethnic', 'lehengas & cholis', 'lehenga', 'bridal', 'velvet'],
        images: [{ url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 5.0,
        numReviews: 49,
      },
      {
        name: 'Pastel Blush Pink Sequin Embellished Party Lehenga Set',
        slug: 'pastel-blush-pink-sequin-party-lehenga-set',
        description: 'Modern fairytale aesthetic featuring multi-layered georgette skirt with shimmering tonal sequins, designer padded blouse, and ruffled dupatta.',
        price: 1150,
        discountPrice: 699,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Couture',
        stock: 20,
        isFeatured: true,
        tags: ['women', 'ethnic', 'lehengas & cholis', 'lehenga', 'partywear', 'sequin'],
        images: [{ url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 63,
      },
      {
        name: 'Raw Silk Floral Printed Sangeet Flared Lehenga Choli',
        slug: 'raw-silk-floral-printed-sangeet-flared-lehenga-choli',
        description: 'Lustrous raw silk skirt in ivory and mint, printed with royal Mughal floral motifs, broad golden border, and matching sweetheart blouse.',
        price: 1550,
        discountPrice: 899,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Riwaaz',
        stock: 22,
        isFeatured: false,
        tags: ['women', 'ethnic', 'lehengas & cholis', 'lehenga', 'sangeet', 'raw silk'],
        images: [{ url: 'https://images.unsplash.com/photo-1621600411688-4be93cd68504?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 38,
      },
      {
        name: 'Mirror Work Multicolored Festive Navratri Flared Lehenga Set',
        slug: 'mirror-work-navratri-flared-lehenga-set',
        description: 'Authentic Kutch mirror needlework on pure cotton flared lehenga with vibrant bandhani print borders and embellished choli.',
        price: 2100,
        discountPrice: 1299,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Riwaaz',
        stock: 28,
        isFeatured: true,
        tags: ['women', 'ethnic', 'lehengas & cholis', 'lehenga', 'navratri', 'mirror work'],
        images: [{ url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 54,
      },
      {
        name: 'Royal Sapphire Blue Zardozi Work Reception Lehenga Choli',
        slug: 'royal-sapphire-blue-zardozi-reception-lehenga-choli',
        description: 'Exquisite silk lehenga with 24-kali flare, adorned with real dabka and zardozi threadwork, paired with scalloped embroidered veil dupatta.',
        price: 300,
        discountPrice: 199,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Couture',
        stock: 16,
        isFeatured: false,
        tags: ['women', 'ethnic', 'lehengas & cholis', 'lehenga', 'reception', 'zardozi'],
        images: [{ url: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 41,
      },

      // 1.10 Dupattas & Shawls (5 items)
      {
        name: 'Traditional Amritsari Phulkari Heavy Hand-Embroidered Dupatta',
        slug: 'amritsari-phulkari-heavy-hand-embroidered-dupatta',
        description: 'Heirloom authentic Punjab Phulkari dupatta crafted with vibrant geometric silk floss thread needlework on breathable chinon fabric.',
        price: 650,
        discountPrice: 399,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Riwaaz',
        stock: 35,
        isFeatured: true,
        tags: ['women', 'ethnic', 'dupattas & shawls', 'dupatta', 'phulkari'],
        images: [{ url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 57,
      },
      {
        name: 'Luxurious Fine Pashmina Cashmere Winter Sozni Shawl',
        slug: 'luxurious-fine-pashmina-cashmere-winter-sozni-shawl',
        description: '100% pure Himalayan Cashmere pashmina shawl detailed with traditional needlework Sozni borders, ultra-soft, warm, and lightweight.',
        price: 1000,
        discountPrice: 599,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Heritage',
        stock: 20,
        isFeatured: true,
        tags: ['women', 'ethnic', 'dupattas & shawls', 'shawl', 'pashmina', 'cashmere'],
        images: [{ url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=800&auto=format&fit=crop' }],
        ratings: 5.0,
        numReviews: 71,
      },
      {
        name: 'Banarasi Brocade Woven Golden Zari Tissue Dupatta',
        slug: 'banarasi-brocade-woven-golden-zari-tissue-dupatta',
        description: 'Glamorous metallic tissue golden dupatta woven with Banarasi floral motifs and heavy pallu tassels, ideal for elevating simple suits.',
        price: 400,
        discountPrice: 249,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Heritage',
        stock: 40,
        isFeatured: false,
        tags: ['women', 'ethnic', 'dupattas & shawls', 'dupatta', 'banarasi dupatta'],
        images: [{ url: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 46,
      },
      {
        name: 'Kalamkari Hand-Painted Pure Tussar Silk Dupatta',
        slug: 'kalamkari-hand-painted-pure-tussar-silk-dupatta',
        description: 'Authentic pen Kalamkari storytelling artwork painted by master artisans using organic dyes on textured handloom Tussar silk.',
        price: 1400,
        discountPrice: 799,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Heritage',
        stock: 25,
        isFeatured: true,
        tags: ['women', 'ethnic', 'dupattas & shawls', 'dupatta', 'kalamkari', 'silk'],
        images: [{ url: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 38,
      },
      {
        name: 'Festive Chanderi Silk Gota Patti Border Dupatta with Latkans',
        slug: 'festive-chanderi-silk-gota-patti-border-dupatta',
        description: 'Pastel festive Chanderi dupatta bordered with intricate golden gota patti lace and finished with handcrafted silk latkans.',
        price: 650,
        discountPrice: 349,
        category: categoryMap['women-ethnic-wear'],
        brand: 'ZYRIVO Riwaaz',
        stock: 45,
        isFeatured: false,
        tags: ['women', 'ethnic', 'dupattas & shawls', 'dupatta', 'chanderi', 'gota patti'],
        images: [{ url: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 33,
      },

      // ═════════════════════════════════════════════════════════════
      // 2. WOMEN WESTERN: 10 Subcategories × 5 Distinct Products = 50
      // ═════════════════════════════════════════════════════════════

      // 2.1 Tops & Blouses (5 items)
      {
        name: 'Satin V-Neck Ruched Wrap Blouse Top',
        slug: 'satin-v-neck-ruched-wrap-blouse-top',
        description: 'Lustrous satin wrap blouse with cuffed bishop sleeves, flattering wrap waist tie, and subtle shoulder gathering.',
        price: 1550,
        discountPrice: 999,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 50,
        isFeatured: true,
        tags: ['women', 'western', 'tops & blouses', 'tops', 'top', 'blouse', 'satin'],
        images: [{ url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 62,
      },
      {
        name: 'Puff Sleeve Tiered Poplin Cotton Blouse Top',
        slug: 'puff-sleeve-tiered-poplin-cotton-blouse-top',
        description: 'Crisp 100% poplin cotton blouse with dramatic puff shoulders, square neckline, and flattering flared peplum waist.',
        price: 750,
        discountPrice: 449,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 45,
        isFeatured: true,
        tags: ['women', 'western', 'tops & blouses', 'tops', 'top', 'blouse', 'cotton'],
        images: [{ url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 49,
      },
      {
        name: 'Classic French Cuff Tailored Silk Office Shirt Blouse',
        slug: 'french-cuff-tailored-silk-office-shirt-blouse',
        description: 'Executive tailored silk button-down blouse with hidden placket, pointed collar, and French double-cuffs.',
        price: 1200,
        discountPrice: 699,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Paris',
        stock: 35,
        isFeatured: false,
        tags: ['women', 'western', 'tops & blouses', 'tops', 'top', 'blouse', 'formal shirt'],
        images: [{ url: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 58,
      },
      {
        name: 'Victorian High-Neck Ruffled Chiffon Party Blouse',
        slug: 'victorian-high-neck-ruffled-chiffon-blouse',
        description: 'Semi-sheer chiffon evening blouse with delicate pleated ruffles around the high neck, keyhole back button, and lined body.',
        price: 500,
        discountPrice: 299,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Paris',
        stock: 30,
        isFeatured: true,
        tags: ['women', 'western', 'tops & blouses', 'tops', 'top', 'blouse', 'partywear'],
        images: [{ url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 41,
      },
      {
        name: 'Cowl Neck Fluid Drape Sleeveless Evening Blouse Top',
        slug: 'cowl-neck-fluid-drape-sleeveless-evening-blouse',
        description: 'Ultra-soft slinky jersey knit top with elegant draped cowl neckline, tailored for layering beneath blazers or wearing solo.',
        price: 850,
        discountPrice: 549,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 42,
        isFeatured: false,
        tags: ['women', 'western', 'tops & blouses', 'tops', 'top', 'blouse', 'evening'],
        images: [{ url: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 36,
      },

      // 2.2 T-Shirts (5 items)
      {
        name: 'Parisian Typography Vintage Washed Graphic Cotton T-Shirt',
        slug: 'parisian-typography-vintage-washed-graphic-tee',
        description: 'Bio-washed 100% cotton relaxed fit tee featuring subtle retro Parisian typography across the chest. Pre-shrunk and durable.',
        price: 1350,
        discountPrice: 849,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Street',
        stock: 60,
        isFeatured: true,
        tags: ['women', 'western', 't-shirts', 't-shirt', 'tshirt', 'graphic tee'],
        images: [{ url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 88,
      },
      {
        name: 'Relaxed Boyfriend Fit Supima Cotton Minimalist T-Shirt',
        slug: 'relaxed-boyfriend-fit-supima-cotton-tee',
        description: 'Buttery-soft 200 GSM long-staple Supima cotton tee with dropped shoulders, ribbed crewneck, and laid-back boyfriend cut.',
        price: 1800,
        discountPrice: 1099,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Basics',
        stock: 55,
        isFeatured: true,
        tags: ['women', 'western', 't-shirts', 't-shirt', 'tshirt', 'basics'],
        images: [{ url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 95,
      },
      {
        name: 'Ribbed Knit Slim Fit Scoop Neck Basic T-Shirt',
        slug: 'ribbed-knit-slim-fit-scoop-neck-basic-tee',
        description: 'Stretch-cotton ribbed knit tee with flattering deep scoop neckline and contoured silhouette. Great for tucking into denim.',
        price: 1100,
        discountPrice: 649,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Basics',
        stock: 65,
        isFeatured: false,
        tags: ['women', 'western', 't-shirts', 't-shirt', 'tshirt', 'ribbed'],
        images: [{ url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 54,
      },
      {
        name: 'Striped Breton Nautical Long Sleeve Cotton Tee',
        slug: 'striped-breton-nautical-long-sleeve-cotton-tee',
        description: 'Timeless French nautical navy and white striped long-sleeve tee with boatneck collar and reinforced cuffs.',
        price: 1300,
        discountPrice: 749,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Paris',
        stock: 45,
        isFeatured: true,
        tags: ['women', 'western', 't-shirts', 't-shirt', 'tshirt', 'striped'],
        images: [{ url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 61,
      },
      {
        name: 'Acid Wash Boxy Crop Streetwear Cotton T-Shirt',
        slug: 'acid-wash-boxy-crop-streetwear-cotton-tee',
        description: 'Vintage mineral-washed charcoal tee featuring raw-edge cropped hemline and relaxed boxy chest fit.',
        price: 900,
        discountPrice: 499,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Street',
        stock: 40,
        isFeatured: false,
        tags: ['women', 'western', 't-shirts', 't-shirt', 'tshirt', 'crop tee'],
        images: [{ url: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.6,
        numReviews: 39,
      },

      // 2.3 Crop Tops (5 items)
      {
        name: 'Ribbed Knit Square Neck Sleeveless Crop Top',
        slug: 'ribbed-knit-square-neck-sleeveless-crop-top',
        description: 'Thick sculpting ribbed knit crop top with architectural square neckline and wide bra-friendly shoulder straps.',
        price: 1400,
        discountPrice: 899,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 55,
        isFeatured: true,
        tags: ['women', 'western', 'crop tops', 'crop top', 'top', 'ribbed'],
        images: [{ url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 53,
      },
      {
        name: 'Halter Neck Seamless Butter-Soft Basic Crop Top',
        slug: 'halter-neck-seamless-butter-soft-basic-crop-top',
        description: 'Double-lined seamless microfiber crop top with elegant tie-back halter neck and wire-free gentle support.',
        price: 2000,
        discountPrice: 1199,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Basics',
        stock: 60,
        isFeatured: false,
        tags: ['women', 'western', 'crop tops', 'crop top', 'halter', 'seamless'],
        images: [{ url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 46,
      },
      {
        name: 'Faux Leather Corset Boned Sleeveless Crop Top',
        slug: 'faux-leather-corset-boned-sleeveless-crop-top',
        description: 'Edgy night-out faux leather crop top equipped with supportive internal boning, curved hem, and back zip closure.',
        price: 600,
        discountPrice: 349,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Couture',
        stock: 35,
        isFeatured: true,
        tags: ['women', 'western', 'crop tops', 'crop top', 'corset', 'leather'],
        images: [{ url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 67,
      },
      {
        name: 'Embroidered Linen Tie-Front Sweetheart Summer Crop Top',
        slug: 'embroidered-linen-tie-front-summer-crop-top',
        description: 'Breezy natural linen crop top with sweet floral eyelet embroidery, self-tie center knot, and ruched elasticated back.',
        price: 1500,
        discountPrice: 949,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 45,
        isFeatured: true,
        tags: ['women', 'western', 'crop tops', 'crop top', 'linen', 'summer'],
        images: [{ url: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 41,
      },
      {
        name: 'Long Sleeve Wrap-Front Twisted Ribbed Crop Top',
        slug: 'long-sleeve-wrap-front-twisted-ribbed-crop-top',
        description: 'Chic fall-winter crop top with cross-over twisted front detail and fitted long sleeves in stretch knit fabric.',
        price: 450,
        discountPrice: 279,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 40,
        isFeatured: false,
        tags: ['women', 'western', 'crop tops', 'crop top', 'long sleeve', 'knit'],
        images: [{ url: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 38,
      },

      // 2.4 Floral Peplum Tops (5 items)
      {
        name: 'Floral Smocked Peplum Summer Top',
        slug: 'floral-smocked-peplum-summer-top',
        description: 'Delicate floral ditsy print top with smocked elasticated bodice and ruffled peplum hemline. Lightweight and breathable.',
        price: 750,
        discountPrice: 479,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 50,
        isFeatured: true,
        tags: ['women', 'western', 'floral peplum tops', 'peplum', 'top', 'floral'],
        images: [{ url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 57,
      },
      {
        name: 'Ditsy Botanical Print Sweetheart Ruffle Peplum Blouse',
        slug: 'ditsy-botanical-print-sweetheart-peplum-blouse',
        description: 'Romantic botanical wildflower print top with sweetheart neck, cap sleeves, and gently flared tiered peplum hem.',
        price: 1100,
        discountPrice: 679,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 45,
        isFeatured: true,
        tags: ['women', 'western', 'floral peplum tops', 'peplum', 'blouse', 'floral'],
        images: [{ url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 43,
      },
      {
        name: 'Smocked Bodice Puff Sleeve Chiffon Floral Peplum Top',
        slug: 'smocked-bodice-puff-sleeve-chiffon-peplum-top',
        description: 'Pastel peach and lavender chiffon floral blouse with flexible smocked body, sheer puff sleeves, and frill details.',
        price: 1500,
        discountPrice: 879,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Paris',
        stock: 35,
        isFeatured: false,
        tags: ['women', 'western', 'floral peplum tops', 'peplum', 'chiffon', 'floral'],
        images: [{ url: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 51,
      },
      {
        name: 'V-Neck Tie-Waist Flared Floral Peplum Shirt Top',
        slug: 'v-neck-tie-waist-flared-floral-peplum-top',
        description: 'Sophisticated collared floral shirt with wrap-around sash belt that cinches the waist into a flared peplum silhouette.',
        price: 1850,
        discountPrice: 1049,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 40,
        isFeatured: true,
        tags: ['women', 'western', 'floral peplum tops', 'peplum', 'tie waist', 'floral'],
        images: [{ url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 36,
      },
      {
        name: 'Tiered Ruffle Hem Pastel Floral Peplum Top',
        slug: 'tiered-ruffle-hem-pastel-floral-peplum-top',
        description: 'Sunny spring floral sleeveless top featuring a double-tiered ruffled peplum hem and button-back fastening.',
        price: 600,
        discountPrice: 329,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 48,
        isFeatured: false,
        tags: ['women', 'western', 'floral peplum tops', 'peplum', 'ruffle', 'floral'],
        images: [{ url: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.6,
        numReviews: 32,
      },

      // 2.5 Casual Tunics (5 items)
      {
        name: 'Bohemian Embroidered Rayon Tunic Top',
        slug: 'bohemian-embroidered-rayon-tunic-top',
        description: 'Relaxed bohemian tunic featuring multi-colored geometric threadwork across the V-neck placket, 3/4 sleeves, and side vents.',
        price: 800,
        discountPrice: 529,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 45,
        isFeatured: true,
        tags: ['women', 'western', 'casual tunics', 'tunic', 'top', 'boho'],
        images: [{ url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 44,
      },
      {
        name: 'High-Low Asymmetric Flowy Linen Relaxed Tunic',
        slug: 'high-low-asymmetric-linen-relaxed-tunic',
        description: 'Pure breathable linen blend tunic with contemporary high-low curved hemline, dropped shoulder seams, and relaxed fit.',
        price: 1200,
        discountPrice: 729,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 40,
        isFeatured: true,
        tags: ['women', 'western', 'casual tunics', 'tunic', 'linen', 'high-low'],
        images: [{ url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 53,
      },
      {
        name: 'Roll-Up Sleeve Mandarin Collar Button-Down Tunic',
        slug: 'roll-up-sleeve-mandarin-collar-button-down-tunic',
        description: 'Crisp cotton-poplin tunic shirt with mandarin collar, chest patch pocket, and convertible roll-up button tabs.',
        price: 1650,
        discountPrice: 979,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Basics',
        stock: 50,
        isFeatured: false,
        tags: ['women', 'western', 'casual tunics', 'tunic', 'shirt tunic'],
        images: [{ url: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 38,
      },
      {
        name: 'Relaxed Striped Slub Cotton Side-Slit Everyday Tunic',
        slug: 'relaxed-striped-slub-cotton-everyday-tunic',
        description: 'Muted grey and ivory horizontal textured slub stripes, crewneck line, deep side-slits, and hip-covering tunic length.',
        price: 1850,
        discountPrice: 1149,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Basics',
        stock: 42,
        isFeatured: true,
        tags: ['women', 'western', 'casual tunics', 'tunic', 'striped'],
        images: [{ url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 47,
      },
      {
        name: 'Embroidered Split-Neck Breezy Bohemian Summer Tunic',
        slug: 'embroidered-split-neck-bohemian-summer-tunic',
        description: 'Crinkle gauze cotton tunic with tassel-tie split neckline, bell cuffs, and artisan floral embroidery detail.',
        price: 350,
        discountPrice: 219,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 35,
        isFeatured: false,
        tags: ['women', 'western', 'casual tunics', 'tunic', 'summer tunic'],
        images: [{ url: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.6,
        numReviews: 31,
      },

      // 2.6 Dresses & Jumpsuits (5 items)
      {
        name: 'Ribbed Knit Bodycon Side-Slit Midi Dress',
        slug: 'ribbed-knit-bodycon-side-slit-midi-dress',
        description: 'Figure-hugging medium-weight stretch ribbed knit midi dress with crewneck collar and subtle knee-height side leg slit.',
        price: 650,
        discountPrice: 419,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 40,
        isFeatured: true,
        tags: ['women', 'western', 'dresses & jumpsuits', 'dress', 'bodycon', 'midi dress'],
        images: [{ url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 53,
      },
      {
        name: 'Tailored Wide-Leg Belted Minimalist Utility Jumpsuit',
        slug: 'tailored-wide-leg-belted-utility-jumpsuit',
        description: 'Sophisticated day-to-night jumpsuit crafted from structured fluid crepe, featuring notch lapels, removable D-ring belt, and wide leg cut.',
        price: 1000,
        discountPrice: 619,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Paris',
        stock: 30,
        isFeatured: true,
        tags: ['women', 'western', 'dresses & jumpsuits', 'jumpsuit', 'wide-leg'],
        images: [{ url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 66,
      },
      {
        name: 'Satin Cowl Back Evening Slip Midi Cocktail Dress',
        slug: 'satin-cowl-back-evening-slip-midi-dress',
        description: 'Lustrous bias-cut heavyweight satin slip dress featuring spaghetti shoulder straps and a show-stopping low draped cowl back.',
        price: 1400,
        discountPrice: 819,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Couture',
        stock: 25,
        isFeatured: true,
        tags: ['women', 'western', 'dresses & jumpsuits', 'dress', 'satin dress', 'slip dress'],
        images: [{ url: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 72,
      },
      {
        name: 'Structured Double-Breasted Tailored Blazer Dress',
        slug: 'structured-double-breasted-blazer-dress',
        description: 'Power-dressing redefined: sharp padded shoulders, satin-faced peak lapels, and tailored double-breasted horn buttons.',
        price: 1800,
        discountPrice: 1019,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Paris',
        stock: 22,
        isFeatured: false,
        tags: ['women', 'western', 'dresses & jumpsuits', 'dress', 'blazer dress'],
        images: [{ url: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 45,
      },
      {
        name: 'Off-Shoulder Flared Party Evening Jumpsuit with Belt',
        slug: 'off-shoulder-flared-party-evening-jumpsuit',
        description: 'Dramatic fold-over off-shoulder neckline paired with a cinched gold buckle waist and sweeping flared trousers in rich noir crepe.',
        price: 650,
        discountPrice: 369,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Couture',
        stock: 28,
        isFeatured: false,
        tags: ['women', 'western', 'dresses & jumpsuits', 'jumpsuit', 'partywear'],
        images: [{ url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 39,
      },

      // 2.7 Floral Maxi Dresses (5 items)
      {
        name: 'Floral Print Tiered Georgette Maxi Dress',
        slug: 'floral-print-tiered-georgette-maxi-dress',
        description: 'Vibrant botanical print maxi dress with sweetheart neckline, smocked elasticated waist, and tiered A-line skirt with flutter sleeves.',
        price: 900,
        discountPrice: 569,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 45,
        isFeatured: true,
        tags: ['women', 'western', 'floral maxi dresses', 'maxi dress', 'dress', 'floral'],
        images: [{ url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 76,
      },
      {
        name: 'Bohemian Botanical Print Off-Shoulder Ruffle Maxi Dress',
        slug: 'bohemian-botanical-off-shoulder-ruffle-maxi-dress',
        description: 'Breezy tropical floral maxi featuring an elasticated bardot neckline with wide ruffled trim and a flowy side thigh slit.',
        price: 1250,
        discountPrice: 769,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 35,
        isFeatured: true,
        tags: ['women', 'western', 'floral maxi dresses', 'maxi dress', 'off-shoulder', 'floral'],
        images: [{ url: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 64,
      },
      {
        name: 'Sweetheart Neckline Tiered Slit Summer Sundress Maxi',
        slug: 'sweetheart-neckline-tiered-slit-summer-sundress-maxi',
        description: 'Pastel yellow wildflower print sundress with underwire sweetheart bustier, adjustable tie straps, and breezy tiered skirt.',
        price: 1850,
        discountPrice: 1099,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 40,
        isFeatured: false,
        tags: ['women', 'western', 'floral maxi dresses', 'maxi dress', 'sundress', 'floral'],
        images: [{ url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 48,
      },
      {
        name: 'Watercolor Pastel Floral Chiffon A-Line Holiday Maxi Dress',
        slug: 'watercolor-pastel-floral-chiffon-maxi-dress',
        description: 'Artistic blush pink watercolor blossoms on flowing sheer chiffon with opaque inner slip, halter neckline, and keyhole tie.',
        price: 2000,
        discountPrice: 1249,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Paris',
        stock: 30,
        isFeatured: true,
        tags: ['women', 'western', 'floral maxi dresses', 'maxi dress', 'chiffon', 'floral'],
        images: [{ url: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 57,
      },
      {
        name: 'Vintage Cottagecore Puff Sleeve Shirred Bodice Maxi Dress',
        slug: 'vintage-cottagecore-puff-sleeve-shirred-maxi-dress',
        description: 'Enchanting meadow flower print cotton maxi with voluminous elasticated puff sleeves, stretchy smocked bodice, and gathered hem.',
        price: 350,
        discountPrice: 239,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 38,
        isFeatured: false,
        tags: ['women', 'western', 'floral maxi dresses', 'maxi dress', 'cottagecore', 'floral'],
        images: [{ url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 42,
      },

      // 2.8 Denim Jeans (5 items)
      {
        name: 'High-Rise Vintage Wide Leg Denim Jeans',
        slug: 'high-rise-vintage-wide-leg-denim-jeans',
        description: 'Classic 5-pocket high-waisted denim jeans crafted from rigid-feel stretch cotton denim with authentic vintage fading.',
        price: 700,
        discountPrice: 439,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Denim',
        stock: 55,
        isFeatured: true,
        tags: ['women', 'western', 'denim jeans', 'jeans', 'denim', 'wide leg'],
        images: [{ url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 82,
      },
      {
        name: 'Classic 90s Straight Leg Light Wash Cotton Denim Jeans',
        slug: 'classic-90s-straight-leg-light-wash-denim-jeans',
        description: 'Effortless retro aesthetic featuring straight-cut leg opening, silver rivet hardware, and authentic whiskering wash.',
        price: 1050,
        discountPrice: 639,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Denim',
        stock: 60,
        isFeatured: true,
        tags: ['women', 'western', 'denim jeans', 'jeans', 'denim', 'straight leg'],
        images: [{ url: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 69,
      },
      {
        name: 'High-Waisted Ankle Grazer Stretch Skinny Jeans',
        slug: 'high-waisted-ankle-grazer-stretch-skinny-jeans',
        description: 'Ultra-flexible sculpting power-stretch denim hugs your contours while retaining shape all day. Raw cut ankle-length hem.',
        price: 1450,
        discountPrice: 839,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Denim',
        stock: 50,
        isFeatured: false,
        tags: ['women', 'western', 'denim jeans', 'jeans', 'denim', 'skinny'],
        images: [{ url: 'https://images.unsplash.com/photo-1551803091-e20673f15770?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 74,
      },
      {
        name: 'Retro 70s Flared Bell Bottom Raw Hem Denim Jeans',
        slug: 'retro-70s-flared-bell-bottom-raw-hem-denim-jeans',
        description: 'Statement bell-bottom flared jeans fitted smoothly through the thigh and opening widely at the knees. Deep indigo wash.',
        price: 1800,
        discountPrice: 1039,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Denim',
        stock: 35,
        isFeatured: true,
        tags: ['women', 'western', 'denim jeans', 'jeans', 'denim', 'flare'],
        images: [{ url: 'https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 58,
      },
      {
        name: 'Relaxed Boyfriend Distressed Multi-Pocket Cargo Jeans',
        slug: 'relaxed-boyfriend-distressed-multi-pocket-cargo-jeans',
        description: 'Urban streetwear cargo denim equipped with roomy utility flap pockets, relaxed slouchy rise, and subtle distressed knees.',
        price: 550,
        discountPrice: 299,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Street',
        stock: 40,
        isFeatured: false,
        tags: ['women', 'western', 'denim jeans', 'jeans', 'denim', 'cargo'],
        images: [{ url: 'https://images.unsplash.com/photo-1554412933-514a83d2f3c8?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 49,
      },

      // 2.9 Formal Trousers (5 items)
      {
        name: 'Pleated High-Waisted Straight Leg Work Trousers',
        slug: 'pleated-high-waisted-straight-leg-work-trousers',
        description: 'Impeccably tailored business trousers with double front pleats, crisp pressed center creases, and slant side pockets.',
        price: 750,
        discountPrice: 499,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Paris',
        stock: 45,
        isFeatured: true,
        tags: ['women', 'western', 'formal trousers', 'trousers', 'formal pants', 'workwear'],
        images: [{ url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 63,
      },
      {
        name: 'Tailored Ankle-Length Slim Cigarette Office Pants',
        slug: 'tailored-ankle-length-slim-cigarette-office-pants',
        description: 'Sleek 7/8 ankle cigarette trousers tailored in bi-stretch cotton blend with waistband belt loops and clean back welt pockets.',
        price: 1150,
        discountPrice: 699,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Paris',
        stock: 50,
        isFeatured: true,
        tags: ['women', 'western', 'formal trousers', 'trousers', 'cigarette pants', 'office'],
        images: [{ url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 54,
      },
      {
        name: 'Paperbag Waist Belted Fluid Drape Formal Trousers',
        slug: 'paperbag-waist-belted-fluid-drape-formal-trousers',
        description: 'High-rise paperbag waist with self-fabric buckle belt, relaxed tapered legs, and breathable fluid twill fabric.',
        price: 1550,
        discountPrice: 899,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Studio',
        stock: 35,
        isFeatured: false,
        tags: ['women', 'western', 'formal trousers', 'trousers', 'paperbag'],
        images: [{ url: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 41,
      },
      {
        name: 'Minimalist Front-Seam Crepe Flare Formal Pants',
        slug: 'minimalist-front-seam-crepe-flare-formal-pants',
        description: 'Flattering vertical pintuck front seams elongate the silhouette on these subtle bootcut stretch crepe dress trousers.',
        price: 2100,
        discountPrice: 1299,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Paris',
        stock: 38,
        isFeatured: true,
        tags: ['women', 'western', 'formal trousers', 'trousers', 'crepe pants'],
        images: [{ url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 58,
      },
      {
        name: 'Wide-Leg Palazzo Cut Tailored Business Trousers',
        slug: 'wide-leg-palazzo-cut-tailored-business-trousers',
        description: 'Wide-leg flowing trousers featuring a structured flat waistband, concealed zip fly, and rich navy suiting drape.',
        price: 300,
        discountPrice: 199,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Paris',
        stock: 32,
        isFeatured: false,
        tags: ['women', 'western', 'formal trousers', 'trousers', 'wide leg'],
        images: [{ url: 'https://images.unsplash.com/photo-1551803091-e20673f15770?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 47,
      },

      // 2.10 Blazers & Jackets (5 items)
      {
        name: 'Tailored Double-Breasted Formal Structured Blazer',
        slug: 'tailored-double-breasted-formal-structured-blazer',
        description: 'Impeccably tailored double-breasted suit blazer with sharp peak lapels, tortoiseshell buttons, and silky satin inner lining.',
        price: 650,
        discountPrice: 399,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Paris',
        stock: 30,
        isFeatured: true,
        tags: ['women', 'western', 'blazers & jackets', 'blazer', 'jacket', 'formal'],
        images: [{ url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 73,
      },
      {
        name: 'Oversized Houndstooth Wool Blend Winter Blazer',
        slug: 'oversized-houndstooth-wool-blend-winter-blazer',
        description: 'Classic monochrome houndstooth check pattern woven with warm wool-blend yarn in an effortlessly chic relaxed oversized cut.',
        price: 1000,
        discountPrice: 599,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Atelier',
        stock: 22,
        isFeatured: true,
        tags: ['women', 'western', 'blazers & jackets', 'blazer', 'wool', 'winter'],
        images: [{ url: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 81,
      },
      {
        name: 'Buttery Soft Vegan Faux Leather Moto Biker Jacket',
        slug: 'buttery-soft-vegan-faux-leather-moto-biker-jacket',
        description: 'Asymmetric front zipper, notched lapel snap buttons, zippered cuffs, and belted waist in supple pebble-grain vegan leather.',
        price: 400,
        discountPrice: 249,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Street',
        stock: 28,
        isFeatured: true,
        tags: ['women', 'western', 'blazers & jackets', 'jacket', 'leather jacket', 'biker'],
        images: [{ url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 69,
      },
      {
        name: 'Classic Vintage Wash Denim Trucker Jacket with Metal Buttons',
        slug: 'classic-vintage-wash-denim-trucker-jacket',
        description: 'Heritage medium blue wash cotton denim trucker jacket with twin flap chest pockets, adjustable waist tabs, and copper buttons.',
        price: 1400,
        discountPrice: 799,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Denim',
        stock: 40,
        isFeatured: false,
        tags: ['women', 'western', 'blazers & jackets', 'jacket', 'denim jacket'],
        images: [{ url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 52,
      },
      {
        name: 'Boucle Tweed Gold Button Luxury Fringe-Trim Jacket',
        slug: 'boucle-tweed-gold-button-luxury-jacket',
        description: 'Chanel-inspired ivory and gold textured boucle tweed jacket featuring braided fringe trims and ornate embossed crested buttons.',
        price: 650,
        discountPrice: 349,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Atelier',
        stock: 20,
        isFeatured: true,
        tags: ['women', 'western', 'blazers & jackets', 'jacket', 'tweed', 'luxury'],
        images: [{ url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=800&auto=format&fit=crop' }],
        ratings: 5.0,
        numReviews: 64,
      },

      // ═════════════════════════════════════════════════════════════
      // 3. SHOES, BAGS, WATCHES & MEN (Essential Complementary Catalog)
      // ═════════════════════════════════════════════════════════════
      {
        name: 'Breathable Lightweight Mesh Running Sneakers',
        slug: 'breathable-lightweight-mesh-running-sneakers',
        description: 'Engineered breathable mesh upper with cushioned responsive EVA sole for all-day athletic performance.',
        price: 1550,
        discountPrice: 999,
        category: categoryMap['footwear-sneakers'],
        brand: 'ZYRIVO Sport',
        stock: 60,
        isFeatured: true,
        tags: ['shoes', 'sports shoes', 'running shoes', 'footwear', 'sports'],
        images: [{ url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 114,
      },
      {
        name: 'Pointed-Toe Classic Stiletto Pumps',
        slug: 'pointed-toe-classic-stiletto-pumps',
        description: 'Sleek 3-inch stiletto heels with anti-skid rubber sole and padded footbed.',
        price: 750,
        discountPrice: 449,
        category: categoryMap['women-footwear-bags'],
        brand: 'ZYRIVO Steps',
        stock: 35,
        isFeatured: true,
        tags: ['women', 'shoes', 'footwear', 'heels & wedges', 'heels'],
        images: [{ url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 40,
      },
      {
        name: 'Classic Suede Tassel Penny Loafers',
        slug: 'classic-suede-tassel-penny-loafers',
        description: 'Hand-burnished Italian suede loafers with cushioned footbed and classic front tassel accent.',
        price: 1200,
        discountPrice: 699,
        category: categoryMap['footwear-sneakers'],
        brand: 'ZYRIVO Footwear',
        stock: 30,
        isFeatured: false,
        tags: ['men', 'shoes', 'loafers', 'footwear', 'casual shoes'],
        images: [{ url: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 53,
      },
      {
        name: 'Embroidered Punjabi Juttis with Zardozi Work',
        slug: 'embroidered-punjabi-juttis-zardozi-work',
        description: 'Pure genuine leather sole Punjabi juttis accented with genuine zari and mirror embroidery.',
        price: 500,
        discountPrice: 299,
        category: categoryMap['women-footwear-bags'],
        brand: 'ZYRIVO Steps',
        stock: 45,
        isFeatured: false,
        tags: ['women', 'shoes', 'footwear', 'flats & sandals', 'juttis'],
        images: [{ url: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 38,
      },
      {
        name: 'Strappy Metallic Ankle-Wrap Block Heels',
        slug: 'strappy-metallic-ankle-wrap-block-heels',
        description: 'Shimmering metallic gold strappy block heels featuring adjustable ankle buckle and comfort arch.',
        price: 850,
        discountPrice: 549,
        category: categoryMap['women-footwear-bags'],
        brand: 'ZYRIVO Steps',
        stock: 30,
        isFeatured: true,
        tags: ['women', 'shoes', 'heels', 'sandals', 'footwear'],
        images: [{ url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 48,
      },
      {
        name: 'Structured Canvas & Vegan Leather Tote Bag',
        slug: 'structured-canvas-vegan-leather-tote-bag',
        description: 'Spacious everyday tote bag with laptop sleeve, inner zippered pouch, and reinforced dual shoulder straps.',
        price: 1350,
        discountPrice: 849,
        category: categoryMap['women-footwear-bags'],
        brand: 'ZYRIVO Bags',
        stock: 40,
        isFeatured: true,
        tags: ['women', 'bags', 'bag', 'tote bags', 'canvas tote'],
        images: [{ url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.7,
        numReviews: 52,
      },
      {
        name: 'Quilted Chain Strap Crossbody Handbag',
        slug: 'quilted-chain-strap-crossbody-handbag',
        description: 'Premium vegan leather with elegant diamond quilting, gold-tone twist-lock closure, and dual compartments.',
        price: 1800,
        discountPrice: 1099,
        category: categoryMap['women-footwear-bags'],
        brand: 'ZYRIVO Bags',
        stock: 35,
        isFeatured: true,
        tags: ['women', 'bags', 'bag', 'handbags & clutches', 'crossbody', 'handbag'],
        images: [{ url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 84,
      },
      {
        name: 'Pebbled Leather Minimalist Shoulder Hobo Bag',
        slug: 'pebbled-leather-minimalist-shoulder-hobo-bag',
        description: 'Supple full-grain pebbled faux leather shoulder bag with spacious magnetic-snap compartment and wide strap.',
        price: 1100,
        discountPrice: 649,
        category: categoryMap['women-footwear-bags'],
        brand: 'ZYRIVO Bags',
        stock: 28,
        isFeatured: true,
        tags: ['women', 'bags', 'bag', 'handbag', 'shoulder bag'],
        images: [{ url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 67,
      },
      {
        name: 'Multi-Pocket Water-Resistant Travel Laptop Backpack',
        slug: 'multi-pocket-water-resistant-laptop-backpack',
        description: 'Ergonomic urban backpack featuring padded 15.6-inch laptop compartment and water-repellent fabric.',
        price: 1300,
        discountPrice: 749,
        category: categoryMap['bags-leather'],
        brand: 'ZYRIVO Gear',
        stock: 45,
        isFeatured: false,
        tags: ['bags', 'bag', 'backpack', 'laptop bag', 'travel'],
        images: [{ url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 89,
      },
      {
        name: 'Glamour Crystal Box Evening Party Clutch',
        slug: 'glamour-crystal-box-evening-clutch',
        description: 'Dazzling rhinestone-encrusted evening minaudiere clutch with detachable golden chain strap.',
        price: 900,
        discountPrice: 499,
        category: categoryMap['women-footwear-bags'],
        brand: 'ZYRIVO Bags',
        stock: 25,
        isFeatured: true,
        tags: ['women', 'bags', 'bag', 'clutch', 'party wear'],
        images: [{ url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.8,
        numReviews: 36,
      },
      {
        name: 'Chronograph Eclipse Skeleton Watch',
        slug: 'chronograph-eclipse-skeleton-watch',
        description: 'Precision Swiss automatic movement encased in 316L aerospace-grade stainless steel with sapphire crystal glass.',
        price: 1400,
        discountPrice: 899,
        category: categoryMap['watches-timepieces'],
        brand: 'ZYRIVO Horology',
        stock: 20,
        isFeatured: true,
        tags: ['men', 'unisex', 'watches', 'watch', 'accessories'],
        images: [{ url: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=800&auto=format&fit=crop' }],
        ratings: 5.0,
        numReviews: 24,
      },
      {
        name: 'Rose Gold Minimalist Mesh Analog Watch',
        slug: 'rose-gold-minimalist-mesh-analog-watch',
        description: 'Ultra-thin 6mm case with clean sunray dial and adjustable stainless steel mesh strap.',
        price: 2000,
        discountPrice: 1199,
        category: categoryMap['watches-timepieces'],
        brand: 'ZYRIVO Horology',
        stock: 30,
        isFeatured: true,
        tags: ['women', 'unisex', 'watches', 'watch', 'accessories'],
        images: [{ url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 58,
      },
      {
        name: 'ZYRIVO Royal Cashmere Trench Coat',
        slug: 'ZYRIVO-royal-cashmere-trench-coat',
        description: 'Expertly crafted from pure Mongolian cashmere, this double-breasted trench features bespoke tortoiseshell buttons and silk satin lining.',
        price: 600,
        discountPrice: 349,
        category: categoryMap['women-western-wear'],
        brand: 'ZYRIVO Atelier',
        stock: 15,
        isFeatured: true,
        tags: ['coat', 'cashmere', 'winter', 'luxury', 'women', 'western', 'blazers & jackets'],
        images: [{ url: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?q=80&w=800&auto=format&fit=crop' }],
        ratings: 4.9,
        numReviews: 12,
      },
      // ═════════════════════════════════════════════════════════════
      // 50 COMPLETE MEN PRODUCTS (10 Subcategories × 5 Exact Products)
      // ═════════════════════════════════════════════════════════════
      ...menProductsData.map((p) => ({
        name: p.name,
        slug: p.slug,
        description: p.description,
        price: p.price,
        discountPrice: p.discountPrice,
        category: categoryMap[p.categorySlug],
        brand: p.brand,
        stock: 40,
        isFeatured: p.isFeatured,
        tags: p.tags,
        images: p.images,
        ratings: p.ratings,
        numReviews: p.numReviews,
      })),
      // ═════════════════════════════════════════════════════════════
      // 50 COMPLETE FOOTWEAR & BAGS PRODUCTS (10 Subcategories × 5 Exact Products)
      // ═════════════════════════════════════════════════════════════
      ...footwearBagsData.map((p) => ({
        name: p.name,
        slug: p.slug,
        description: p.description,
        price: p.price,
        discountPrice: p.discountPrice,
        category: categoryMap[p.categorySlug],
        brand: p.brand,
        stock: 40,
        isFeatured: p.isFeatured,
        tags: p.tags,
        images: p.images,
        ratings: p.ratings,
        numReviews: p.numReviews,
      })),
      // ═════════════════════════════════════════════════════════════
      // 100 COMPLETE PRODUCTS: WATCHES, KIDS, HOME & LIVING, BEAUTY
      // ═════════════════════════════════════════════════════════════
      ...newCategoriesData.map((p) => ({
        name: p.name,
        slug: p.slug,
        description: p.description,
        price: p.price,
        discountPrice: p.discountPrice,
        category: categoryMap[p.categorySlug],
        brand: p.brand,
        stock: 40,
        isFeatured: p.isFeatured,
        tags: p.tags,
        images: p.images,
        ratings: p.ratings,
        numReviews: p.numReviews,
      })),
      // ═════════════════════════════════════════════════════════════
      // 135 EXPANDED PRODUCTS (STANDARDIZED 50 PRODUCTS PER MAIN CATEGORY)
      // ═════════════════════════════════════════════════════════════
      ...expandedCatalogData.map((p) => ({
        name: p.name,
        slug: p.slug,
        description: p.description,
        price: p.price,
        discountPrice: p.discountPrice,
        category: categoryMap[p.categorySlug],
        brand: p.brand,
        stock: 40,
        isFeatured: p.isFeatured,
        tags: p.tags,
        images: p.images,
        ratings: p.ratings,
        numReviews: p.numReviews,
      })),
    ];

    // Clear old products and insert fresh catalog
    await Product.deleteMany({});
    console.log('Cleared old products collection.');

    const created = await Product.insertMany(allProducts);
    console.log(`✅ Successfully seeded ${created.length} Complete Catalog products into MongoDB!`);
    process.exit(0);
  } catch (error) {
    console.error('Error seeding all products:', error);
    process.exit(1);
  }
};

seedAll();


